#!/usr/bin/env python3
"""META (OWNER 2026-09-29 19:33, the Meta SDK in 1.0): the release-gate half of the Meta wiring (tools/bench/release_gates.sh).

    meta_sdk_check.py attrib <App.app>   JSON {relative path: why} of every bundle file PROVEN to be the pinned Facebook SDK's
                                        own (gates 2 / 2b / 7 attribute their hits in those files, and only there):
                                          - a framework binary under Frameworks/<Kit>.framework/ whose LC_UUIDs are all the
                                            pinned artifact's (<Kit>.xcframework, any slice) — survives re-signing;
                                          - any other file of those frameworks byte-identical to the artifact's same file;
                                          - the SPM resource bundles Facebook_Facebook*.bundle: Info.plist (generated by Xcode:
                                            platform names only) and PrivacyInfo.xcprivacy byte-identical to the checkout's.
                                        + "problems": what could not be proven (then nothing is attributed for that file).
    meta_sdk_check.py gate8 <App.app>    gate 8: FacebookCore is the ONLY third-party framework and it is the pinned one; no
                                        ad-SERVING SDK anywhere (frameworks, load commands, Info.plist keys, identifier
                                        strings); the Meta Info.plist keys hold their ruled values; the client token is
                                        present, well formed and the factory .env's own (never printed); the privacy manifest
                                        declares tracking with exactly ep1.facebook.com. A planted bundle with an ad SDK, an
                                        ad plist key, an ad string, a wrong SDK version and an empty token must be caught, or
                                        the gate FAILS (the checks can see what they look for).

The pinned artifacts: $FB_ARTIFACTS, default <DerivedData>/SourcePackages/artifacts/facebook-ios-sdk derived from the .app
path (<DD>/Build/Products/<config>/App.app); the SPM checkout: $FB_CHECKOUT, default <DD>/SourcePackages/checkouts/
facebook-ios-sdk. An archive built elsewhere (gym) passes both explicitly.
"""
import json
import os
import plistlib
import re
import subprocess
import sys
import tempfile

PINNED = "18.1.1"
KITS = ("FBSDKCoreKit", "FBSDKCoreKit_Basics", "FBAEMKit")                  # the FacebookCore product's dynamic frameworks
ALLOWED_FW = {k + ".framework" for k in KITS}
RES_BUNDLES = {"Facebook_FacebookCore.bundle": "FacebookCore", "Facebook_FacebookAEM.bundle": "FacebookAEM",
               "Facebook_FacebookBasics.bundle": "FacebookBasics"}
APP_ID = "2657116281470019"
SKAD = {"v9wttpbfk9.skadnetwork", "n38lu8286q.skadnetwork"}
TRACKING_DOMAINS = ["ep1.facebook.com"]
# ad-SERVING SDKs and the Facebook kits nobody ordered (frameworks / load-command names)
AD_FW = re.compile(r"(?i)GoogleMobileAds|GoogleAppMeasurement|Firebase|FBAudienceNetwork|AppLovin|UnityAds|IronSource|Vungle|"
                   r"Chartboost|InMobi|MoPub|AdColony|Mintegral|MTGSDK|BUAdSDK|Pangle|PAGAdSDK|CSJAdSDK|YandexMobileAds|StartApp|"
                   r"Tapjoy|iAd\.framework|FBSDKLoginKit|FBSDKShareKit|FBSDKGamingServicesKit")
# ad-serving identifiers (strings any such SDK or its setup carries)
AD_STR = re.compile(rb"GADApplicationIdentifier|ca-app-pub-[0-9]|GADMobileAds|GADBannerView|GADInterstitialAd|FBAdView|"
                    rb"FBInterstitialAd|FBRewardedVideoAd|FBAdSettings|AppLovinSdkKey|ALSdkSettings|UnityAdsInitialization|"
                    rb"IronSourceAds|VungleAds|ISNativeAd")
AD_PLIST_KEYS = ("GADApplicationIdentifier", "GADIsAdManagerApp", "AppLovinSdkKey", "IronSourceAppKey", "UnityAdsGameId",
                 "FacebookAutoInitEnabled")
MACHO = (b"\xcf\xfa\xed\xfe", b"\xca\xfe\xba\xbe", b"\xbe\xba\xfe\xca", b"\xce\xfa\xed\xfe")


def dd_of(app):
    return os.path.abspath(os.path.join(os.path.dirname(app), "..", "..", ".."))


def artifacts_dir(app):
    return os.environ.get("FB_ARTIFACTS") or os.path.join(dd_of(app), "SourcePackages", "artifacts", "facebook-ios-sdk")


def checkout_dir(app):
    return os.environ.get("FB_CHECKOUT") or os.path.join(dd_of(app), "SourcePackages", "checkouts", "facebook-ios-sdk")


def uuids(path):
    r = subprocess.run(["dwarfdump", "--uuid", path], capture_output=True, text=True)
    if r.returncode != 0:
        return None
    return set(re.findall(r"UUID: ([0-9A-F-]{36})", r.stdout)) or None


def slices(arts, kit):
    x = os.path.join(arts, kit, kit + ".xcframework")
    return [os.path.join(x, s, kit + ".framework") for s in (sorted(os.listdir(x)) if os.path.isdir(x) else [])
            if os.path.isdir(os.path.join(x, s, kit + ".framework"))]


def attrib(app):
    """-> ({rel: why}, [problems])."""
    arts, co = artifacts_dir(app), checkout_dir(app)
    out, problems = {}, []
    for kit in KITS:
        fw = os.path.join(app, "Frameworks", kit + ".framework")
        if not os.path.isdir(fw):
            continue
        sl = slices(arts, kit)
        if not sl:
            problems.append(f"{kit}: no pinned artifact at {arts} (set FB_ARTIFACTS): nothing of it can be attributed")
            continue
        for d, _, fs in os.walk(fw):
            for f in fs:
                p = os.path.join(d, f)
                rel = os.path.relpath(p, app)
                inner = os.path.relpath(p, fw)
                if inner.startswith("_CodeSignature"):
                    out[rel] = "the framework's code signature (Xcode re-signs an embedded framework)"
                    continue
                if inner == kit:
                    mine = uuids(p)
                    theirs = set().union(*[(uuids(os.path.join(s, kit)) or set()) for s in sl])
                    if mine and mine <= theirs:
                        out[rel] = f"{kit} {PINNED} binary (LC_UUID {', '.join(sorted(mine))[:37]}… = the pinned artifact's)"
                    else:
                        problems.append(f"{rel}: LC_UUIDs {sorted(mine or [])} are not the pinned {PINNED} artifact's")
                    continue
                data = open(p, "rb").read()
                if any(os.path.isfile(os.path.join(s, inner)) and open(os.path.join(s, inner), "rb").read() == data for s in sl):
                    out[rel] = f"{kit} {PINNED} file, byte-identical to the pinned artifact's {inner}"
                else:
                    problems.append(f"{rel}: not byte-identical to any pinned {kit} slice's {inner}")
    for b, target in RES_BUNDLES.items():
        bd = os.path.join(app, b)
        if not os.path.isdir(bd):
            continue
        for d, _, fs in os.walk(bd):
            for f in fs:
                p = os.path.join(d, f)
                rel = os.path.relpath(p, app)
                inner = os.path.relpath(p, bd)
                src = os.path.join(co, "Sources", target, "Resources", inner)
                if inner.startswith("_CodeSignature"):
                    out[rel] = "the resource bundle's code signature"
                elif inner == "Info.plist":
                    out[rel] = f"the SPM resource bundle of {target} (Xcode-generated: bundle id + platform names only)"
                elif os.path.isfile(src) and open(src, "rb").read() == open(p, "rb").read():
                    out[rel] = f"{target} {PINNED} resource, byte-identical to the checkout's Sources/{target}/Resources/{inner}"
                else:
                    problems.append(f"{rel}: not byte-identical to the checkout's Sources/{target}/Resources/{inner}")
    return out, problems


def env_token():
    """The factory .env's META_CLIENT_TOKEN (never printed) or None."""
    root = os.environ.get("PC_ROOT") or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    # RFIX 2026-09-29 (VERIFY F1): the same factory .env tools/meta_token.py injects from (PC_FACTORY_ENV, else the first
    # ancestor holding .env + apps/), so a snapshot tree compares against the token its build really used
    sys.path.insert(0, os.path.join(root, "tools"))
    try:
        import meta_token
        path = meta_token.factory_env(root)
    except Exception:  # noqa: BLE001 - an old tree without factory_env: the old spelling
        path = os.path.join(root, "..", "..", ".env")
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return None
    v = None
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("export "):
            s = s[7:].lstrip()
        if s.startswith("META_CLIENT_TOKEN="):
            v = s.split("=", 1)[1].strip().strip("\"'").strip()
    return v or None


def check(app, *, planted=False):
    """-> (problems, notes) for gate 8 on one bundle."""
    P, N = [], []
    fwdir = os.path.join(app, "Frameworks")
    embedded = sorted(os.listdir(fwdir)) if os.path.isdir(fwdir) else []
    for e in embedded:
        if e not in ALLOWED_FW:
            P.append(f"embedded {e}: not the FacebookCore product's framework" + (" (AN AD-SERVING SDK)" if AD_FW.search(e) else ""))
    missing = sorted(ALLOWED_FW - set(embedded))
    if missing:
        P.append("FacebookCore frameworks missing: " + ", ".join(missing) + " (the SDK is not linked: MetaAds would be dead)")
    # the version is proven by IDENTITY: Meta's frameworks all say CFBundleShortVersionString "1.0"; the embedded binary's
    # LC_UUIDs must be the pinned artifact's (SPM verified that zip against the checksum pinned in the SDK's Package.swift)
    fb, fbprob = attrib(app) if not planted else ({}, [])
    for kit in KITS:
        rel = os.path.join("Frameworks", kit + ".framework", kit)
        if not os.path.isfile(os.path.join(app, rel)):
            continue
        if rel in fb:
            N.append(f"{kit}.framework: {fb[rel]}")
        else:
            P.append(f"{kit}.framework: not proven the pinned {PINNED} artifact (LC_UUID mismatch or no artifact; FB_ARTIFACTS)")
    # load commands of the main binary (byte scan: the same code path reads the planted sample)
    binp = os.path.join(app, os.path.basename(app)[:-4])
    dbg = os.path.join(app, os.path.basename(app)[:-4] + ".debug.dylib")
    blob = b""
    for b in (binp, dbg):
        if os.path.isfile(b):
            blob += open(b, "rb").read()
    rpath = sorted(set(x.decode() for x in re.findall(rb"@rpath/[A-Za-z0-9_.+-]+\.framework/[A-Za-z0-9_.+-]+", blob)))
    sysfw = sorted(set(x.decode() for x in re.findall(rb"/System/Library/Frameworks/([A-Za-z0-9_]+)\.framework/", blob)))
    for r in rpath:
        name = r.split("/")[1]
        if name not in ALLOWED_FW:
            P.append(f"the binary loads {r}" + (" (AN AD-SERVING SDK)" if AD_FW.search(r) else " (not the FacebookCore product)"))
    for s in sysfw:
        if AD_FW.search(s + ".framework"):
            P.append(f"the binary links /System/Library/Frameworks/{s}.framework (ad serving)")
    apple = [s for s in sysfw if s in ("AppTrackingTransparency", "AdSupport", "AdServices")]
    N.append("Apple's consent / attribution APIs linked: " + (", ".join(apple) or "none")
             + " (ATT prompt; IDFA only after .authorized; AdServices = RevenueCat's Search Ads token, ruling 55a)")
    if not any(r.startswith("@rpath/FBSDKCoreKit.framework/") for r in rpath):
        P.append("the binary does not load @rpath/FBSDKCoreKit.framework (FacebookCore not linked)")
    # ad-serving identifier strings: our binary, every file outside the pinned SDK's own frameworks
    hits = []
    for d, _, fs in os.walk(app):
        for f in fs:
            p = os.path.join(d, f)
            rel = os.path.relpath(p, app)
            if rel in fb:
                continue
            for m in AD_STR.finditer(open(p, "rb").read()):
                hits.append(f"{rel}: {m.group(0).decode('latin-1')}")
    P += [f"ad-serving identifier {h}" for h in sorted(set(hits))[:20]]
    # Info.plist
    info = plistlib.load(open(os.path.join(app, "Info.plist"), "rb"))
    for k in AD_PLIST_KEYS:
        if k in info:
            P.append(f"Info.plist carries {k} (an ad-serving SDK key / an auto-init switch)")
    want = {"FacebookAppID": APP_ID, "FacebookAutoLogAppEventsEnabled": False, "FacebookAdvertiserIDCollectionEnabled": False}
    for k, v in want.items():
        if info.get(k) != v:
            P.append(f"Info.plist {k} = {info.get(k)!r} (ruled {v!r})")
    ids = {x.get("SKAdNetworkIdentifier") for x in info.get("SKAdNetworkItems", []) if isinstance(x, dict)}
    if not SKAD <= ids:
        P.append(f"Info.plist SKAdNetworkItems lack Meta's ids: {sorted(SKAD - ids)}")
    if not str(info.get("NSUserTrackingUsageDescription") or "").strip():
        P.append("Info.plist has no NSUserTrackingUsageDescription (iOS would answer .denied without a prompt)")
    tok = info.get("FacebookClientToken") or ""
    if not re.fullmatch(r"[0-9a-f]{32}", tok):
        P.append("FacebookClientToken is EMPTY or malformed (OWNER ACTION: META_CLIENT_TOKEN in the factory .env; a verification "
                 "build made with PC_META_VERIFICATION_BUILD=1 can never be the store build)")
    else:
        et = None if planted else env_token()
        if et is None:
            P.append("FacebookClientToken is well formed but the factory .env has no META_CLIENT_TOKEN to prove it is the store token")
        elif et != tok:
            P.append("FacebookClientToken differs from the factory .env's META_CLIENT_TOKEN (value not printed)")
        else:
            N.append("FacebookClientToken: 32 hex, equal to the factory .env's (value not printed)")
    # privacy manifest
    pi = os.path.join(app, "PrivacyInfo.xcprivacy")
    if not os.path.isfile(pi):
        P.append("no PrivacyInfo.xcprivacy at the bundle root")
    else:
        d = plistlib.load(open(pi, "rb"))
        if d.get("NSPrivacyTracking") is not True or d.get("NSPrivacyTrackingDomains") != TRACKING_DOMAINS:
            P.append(f"PrivacyInfo: tracking {d.get('NSPrivacyTracking')} domains {d.get('NSPrivacyTrackingDomains')} "
                     f"(ruled: true, exactly {TRACKING_DOMAINS})")
        else:
            N.append("PrivacyInfo: NSPrivacyTracking true, NSPrivacyTrackingDomains exactly ['ep1.facebook.com']")
    N.append("embedded frameworks: " + (", ".join(embedded) or "none"))
    N.append("@rpath frameworks the binary loads: " + (", ".join(rpath) or "none"))
    return P, N


def planted_control():
    """A bundle with an ad-serving SDK, its plist key and strings, a wrong FacebookCore version and an empty token."""
    with tempfile.TemporaryDirectory() as t:
        app = os.path.join(t, "Planted.app")
        os.makedirs(os.path.join(app, "Frameworks", "GoogleMobileAds.framework"))
        open(os.path.join(app, "Frameworks", "GoogleMobileAds.framework", "GoogleMobileAds"), "wb").write(b"\xcf\xfa\xed\xfe\0GADMobileAds\0")
        for kit in KITS:                                           # a FacebookCore that is not the pinned build
            os.makedirs(os.path.join(app, "Frameworks", kit + ".framework"))
            open(os.path.join(app, "Frameworks", kit + ".framework", kit), "wb").write(b"\xcf\xfa\xed\xfe\0not the pinned SDK\0")
        open(os.path.join(app, "Planted"), "wb").write(
            b"\xcf\xfa\xed\xfe\0@rpath/FBSDKCoreKit.framework/FBSDKCoreKit\0@rpath/GoogleMobileAds.framework/GoogleMobileAds\0"
            b"ca-app-pub-3940256099942544~1458002511\0")
        plistlib.dump({"FacebookAppID": APP_ID, "FacebookClientToken": "", "FacebookAutoLogAppEventsEnabled": False,
                       "FacebookAdvertiserIDCollectionEnabled": False, "GADApplicationIdentifier": "ca-app-pub-3940256099942544~1",
                       "SKAdNetworkItems": [{"SKAdNetworkIdentifier": s} for s in SKAD], "NSUserTrackingUsageDescription": "x"},
                      open(os.path.join(app, "Info.plist"), "wb"))
        plistlib.dump({"NSPrivacyTracking": True, "NSPrivacyTrackingDomains": TRACKING_DOMAINS}, open(os.path.join(app, "PrivacyInfo.xcprivacy"), "wb"))
        P, _ = check(app, planted=True)
        text = "\n".join(P)
        need = ["embedded GoogleMobileAds.framework", "loads @rpath/GoogleMobileAds.framework", "carries GADApplicationIdentifier",
                "ad-serving identifier Planted: ca-app-pub-3", "FBSDKCoreKit.framework: not proven the pinned", "FacebookClientToken is EMPTY"]
        missed = [n for n in need if n not in text]
        return not missed, missed


def main(argv):
    if len(argv) < 3 or argv[1] not in ("attrib", "gate8"):
        print(__doc__)
        return 2
    app = argv[2].rstrip("/")
    if argv[1] == "attrib":
        out, problems = attrib(app)
        json.dump({"files": out, "problems": problems}, sys.stdout, indent=1)
        return 0
    ok, missed = planted_control()
    print("  control (planted: GoogleMobileAds + its plist key + ca-app-pub string, a FacebookCore that is not the pinned build, empty token): "
          + ("caught" if ok else "NOT CAUGHT " + str(missed) + " -> the gate is blind"))
    P, N = check(app)
    _, aprob = attrib(app)
    for n in N:
        print("  ok    " + n)
    for p in P + aprob:
        print("  FAIL  " + p)
    print(f"  8: {len(P) + len(aprob)} problem(s) (must be 0)")
    return 0 if ok and not P and not aprob else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
