import Foundation

// SOC1 (SPEC-social §2.1-§2.6; reference design/social/tools/socialsim/data.py + population.py constants).
// The static tables of the simulated world. World constants are CODE (SPEC-social §7 "Tuning"): changing one changes
// the shared world on every device and breaks the golden fixtures on purpose.
//
// Three parameter sets exist:
//   * `.reference`  = the social designer's prototype exactly (design/social/fixtures/*.json pin it bit for bit);
//   * `.calibrated` = the v1 world of SOC1-SOC1c: the same model with the population re-calibrated to what the owner's phone
//                     showed on 25 Sep 2026 (research/meta.md §7, phone-meta-progress 04:31): World #1 14669 … #7 11386,
//                     #24 ≈ 8.4k, #89 5154, #132 ≈ 4.3k, #278 3096; Turkey rank 455 at Level 62; Turkey #2-#7 3323 … 1349.
//                     SPEC-social's reference world (calibrated to the older V2 video) had ~30× too many heavy players (#278
//                     = 9081, TR rank at L62 = 3042) — the phone wins (owner 02:55). Pinned by Tests/Fixtures/soc_v552_*.json
//                     (the fixture files keep their SOC1 names; tests only), generated by the SAME Python reference with only
//                     these parameters overridden (Tests/tools/soc_model.py). Symbol and name renamed by PUBLISH B2 (was
//                     `.v552` / "shipped"): it no longer ships.
//   * `.shipped`    = the v2 ("international") world that SHIPS (PUBLISH B2, owner item 13; social-intl §6): the calibrated
//                     world + M1-M11 (SocialIntl), pinned by Tests/Fixtures/soc_v2_*.json from socialsim/v2.py.

public struct SocialArchetype: Sendable, Equatable {
    public var key: String
    public var share: Double
    public var daily: Bool                     // one cohort per join DAY (tourists) instead of per join week
    public var lamX: [Double], lamY: [Double]  // levels per PLAYED day over the member quantile u
    public var lifeX: [Double], lifeY: [Double] // active life (days) over u; slope >= the join spread (containment)
    public var rho: Double                     // probability that a day is a play day
    public var sessMin: Int, sessMax: Int      // sessions on a play day
    public var firstLo: Double, firstHi: Double // install-session levels over u
    public var lapse: (lo: Double, hi: Double)? // lapsed phase after quitting (days over u)
    public var life2X: [Double]?, life2Y: [Double]?  // returners: second life (days over u)
    public var gap: (lo: Double, hi: Double)?  // returners: comeback gap (days, per cohort)
    public var custom: Double                  // share of members with a custom nickname
    public var avatarDefault: Double, avatarCustom: Double   // portrait probability (default name / custom name)
    /// Shipped model only (nil = the prototype): new members play (1 + beta) x their daily volume until `days` after the
    /// END of their cohort's join window (capped by each member's T1). One end per cohort keeps containment.
    public var honey: (beta: Double, days: Double)? = nil

    public static func == (a: SocialArchetype, b: SocialArchetype) -> Bool {
        a.key == b.key && a.share == b.share && a.daily == b.daily && a.lamX == b.lamX && a.lamY == b.lamY
            && a.lifeX == b.lifeX && a.lifeY == b.lifeY && a.rho == b.rho && a.sessMin == b.sessMin && a.sessMax == b.sessMax
            && a.firstLo == b.firstLo && a.firstHi == b.firstHi && a.lapse?.lo == b.lapse?.lo && a.lapse?.hi == b.lapse?.hi
            && a.life2X == b.life2X && a.life2Y == b.life2Y && a.gap?.lo == b.gap?.lo && a.gap?.hi == b.gap?.hi
            && a.custom == b.custom && a.avatarDefault == b.avatarDefault && a.avatarCustom == b.avatarCustom
            && a.honey?.beta == b.honey?.beta && a.honey?.days == b.honey?.days
    }
}

public struct SocialCountryRow: Sendable, Equatable {
    public var iso: String
    public var weight: Double
    public var offsetMinutes: Int
    public var culture: String
    public var bucket: String
    /// v2 (M5, PUBLISH B2): the row's culture mix, drawn per member (`culture` = its first culture); nil = the single
    /// `culture` (the v1 models).
    public var mix: [SocialCultureShare]? = nil
}

/// One culture of a v2 country row's mix (countries_v2.tsv "nl:0.6,fr:0.4").
public struct SocialCultureShare: Sendable, Equatable {
    public var culture: String
    public var weight: Double
}

/// How a device region code resolves on the v2 world (regions_v2.tsv): a table row, an alias of a row (a territory plays
/// on its parent's board: IC -> ES, GU -> US …) or a UN M.49 numeric region's representative row; `board` = the ISO of
/// the board it plays on.
public struct SocialRegion: Sendable, Equatable {
    public enum Kind: String, Sendable { case row, alias, numeric }
    public var kind: Kind
    public var board: String
}

/// PUBLISH B2 (PLAN-P §4.4, owner item 13; design/publish/social-intl.md §6): the v2 ("international") mechanisms of
/// design/social/tools/socialsim/v2.py, bit for bit. nil in the v1 models (reference, calibrated), which stay pinned by
/// their own fixtures.
///   M1 countryBlocks  a shared cohort no longer has ONE country: its members are split into contiguous blocks, one per row
///                     of its timezone band, apportioned inside `strata` equal strata (labels 'cblk' / 'cord'); a member's
///                     country and culture come from its block; levels and ids do not depend on the blocks
///   M2 jitter         u_j = (j + u01('uj', ck, j)) / n (u stays strictly increasing: containment and the binary searches
///                     stay exact, the evenly spaced ladders go)
///   M3 buckets/regions the country table v2 (200 rows, SocialIntlTables), 10 bands each with ONE schedule offset, and
///                     the region map (every isoRegions code -> a board)
///   M4 localByISO     the device-only LOCAL partition exists only for a 2-letter code no table knows; its cohort keys and
///                     name/avatar ids are salted with the 16-bit code; offset 0 and culture 'en' (never the device's)
///   M5 memberCulture  a member's name culture is drawn from its row's mix (label 'mcul' on the member's id)
///   M6/M7             native-script shares and the scaled popularity head live in the name style (SocialNameStyle.shipped)
///   M8 epoch          the world's own epoch (SocialWorldModel.epoch; the event calendar keeps SocialCalendar.epoch)
///   M9 shardTarget    a weekly cohort of E expected players is split into max(1, ⌊E / T + 0.5⌋) independent shards (key
///      minShards      ck + (k << 24)), at least `minShards[arch]` for regulars / returners
///   M10 lagMinutes    member j trails its cohort's clock by lag × (1 − u) minutes (0 = off, as shipped)
///   M11 rowTilt       inside M1's apportionment a row weighs weight × tilt[iso][archetype] (Turkey's archetype mix)
public struct SocialIntl: Sendable, Equatable {
    public var buckets: [String]
    public var bucketOffsets: [Int]
    public var regions: [String: SocialRegion]
    public var countryBlocks = true
    public var strata = 8
    public var jitter = true
    public var localByISO = true
    public var memberCulture = true
    public var shardTarget: [String: Double]? = nil
    public var minShards: [String: Int]? = nil
    public var lagMinutes = 0.0
    public var rowTilt: [String: [String: Double]] = [:]
}

/// One complete parameter set of the shared world.
public struct SocialWorldModel: Sendable, Equatable {
    public var name: String
    public var seed: UInt64
    public var archetypes: [SocialArchetype]
    public var countries: [SocialCountryRow]
    /// Nicknames longer than this (Unicode scalars) are replaced like blocked ones (nil = no cap, the reference). The
    /// shipped world caps at 16 = the player's own username rule (SPEC-social §2.8), so no simulated player shows a
    /// name the player could not choose (the reference emits 0.06 % of 17-20 character names).
    public var maxNameLength: Int? = nil
    /// Portraits a simulated player can carry: avatar 1…avatarCount (0 = the default silhouette). The reference drew
    /// from 14; the shipped world from the 8 portraits the app ships (CONSISTENCY V-24, SPEC §5.12 / §5.22).
    public var avatarCount = 14
    /// Extra blocked stems on top of the name data's lists (folded key, substring): the shipped world keeps the
    /// original's title word out of every nickname (the copying line: the word never appears in what we ship).
    /// FIX-3 B (SPEC.md ruling 55(c), V1A-G8-1): stored hashed (`SocialBlockedStem`), so the binary never spells it either;
    /// the verdict is the old `key.contains(stem)`'s (SocialNamesTests.testHashedStemIsThePlainContains).
    public var extraBlockedStems: [SocialBlockedStem] = []
    /// The nickname style mix and the shipped variants (Names.swift `SocialNameStyle`).
    public var nameStyle: SocialNameStyle = .reference
    /// The world's epoch (join period 0; M8). The v1 models: the event calendar's epoch (the original's launch day); the
    /// shipped v2 world: Monday 2026-09-07 07:00 UTC (ruling 39 OD9). Exactly whole weeks from SocialCalendar.epoch, so
    /// world weeks and event weeks share their boundaries.
    public var epoch: Int = SocialCalendar.epoch
    /// The v2 mechanisms (nil = a v1 model).
    public var intl: SocialIntl? = nil

    /// The timezone bands of this model (v1: the 9 of data.py; v2: buckets_v2.tsv).
    public var bucketNames: [String] { intl?.buckets ?? Self.buckets }

    // ---------------------------------------------------------------- constants shared by every model (data.py)
    public static let buckets = ["AMER_W", "AMER_E", "AMER_S", "EUR_W", "EUR_C", "EUR_E", "ASIA_S", "ASIA_SE", "ASIA_E"]
    public static let cultures = ["tr", "de", "fr", "es", "pt", "it", "nl", "nordic", "pl", "easteu", "in", "sea", "jp", "kr",
                                  "ar", "en"]
    /// v2 (M5): the reference's 16 cultures, then v2.py NEW_CULTURES APPENDED (a token's hash key uses the culture's index,
    /// so the 16 old indices never move; 'easteu' and 'sea' stay listed although no v2 row uses them).
    public static let intlCultures = cultures + ["sk", "sl", "cs", "hu", "ro", "el", "ru", "uk", "bg", "hr", "sr", "th", "vi", "id",
                                                 "ms", "tl", "zh", "he", "ptpt", "fi", "fa", "sq", "lt", "lv", "et", "ur", "hy", "ka",
                                                 "az", "kk", "uz", "af"]
    static let lapseDayP = 0.16             // share of a cohort's play days on which its LAPSED members come back
    static let lapseVolume = 0.5            // ... playing half their usual daily volume
    static let paceRange = (lo: 0.40, hi: 0.65)   // levels per minute inside a session, per cohort
    static let firstPace = 0.55             // levels per minute in the install session
    static let sessionGap = 10.0            // minutes between two sessions of one cohort-day
    static let dayBudget = 1200.0           // max minutes of play windows per cohort-day
    static let pattern = 28                 // days in a cohort's repeating daily-volume pattern (multiple of 7)
    static let weekdayVolume = [0.92, 0.90, 0.92, 0.95, 1.02, 1.22, 1.18]   // Mon..Sun
    static let volumeRange = (lo: 0.55, hi: 1.45)
    static let diurnalWeekday = [0.9, 0.5, 0.3, 0.2, 0.15, 0.2, 0.5, 1.2, 1.6, 1.4, 1.3, 1.4, 1.9, 1.8, 1.5, 1.5, 1.7, 2.0,
                                 2.3, 2.6, 2.9, 3.0, 2.6, 1.7]
    static let diurnalWeekend = [1.2, 0.8, 0.5, 0.3, 0.2, 0.2, 0.3, 0.6, 1.0, 1.5, 1.8, 2.0, 2.1, 2.1, 2.0, 2.0, 2.0, 2.1,
                                 2.3, 2.5, 2.7, 2.8, 2.5, 1.9]
    static func cdf(_ ws: [Double]) -> [Double] {
        var c = [0.0]
        for w in ws { c.append(c[c.count - 1] + w) }
        let tot = c[c.count - 1]
        return c.map { $0 / tot }
    }
    static let diurnalCDF = [cdf(diurnalWeekday), cdf(diurnalWeekend)]
    static let baseDay = 20_552             // a local day number that is a multiple of PATTERN (734 · 28)
    static let minutes = 1440.0
    static let localShare = 0.003           // the device-only LOCAL partition (home country not in the table)
    public static let worldSeed: UInt64 = GameConfig.worldSeed     // the one shared world (game.yml social.world_seed)

    /// Culture for a home country that is not in the table (default "en").
    public static let extraCulture: [String: String] = [
        "VE": "es", "EC": "es", "UY": "es", "PY": "es", "BO": "es", "CR": "es", "PA": "es", "GT": "es", "DO": "es", "PR": "es",
        "SV": "es", "HN": "es", "NI": "es", "CU": "es", "AO": "pt", "MZ": "pt", "LU": "fr", "MC": "fr", "SN": "fr", "CI": "fr",
        "MA": "ar", "DZ": "ar", "TN": "ar", "JO": "ar", "LB": "ar", "KW": "ar", "QA": "ar", "BH": "ar", "OM": "ar", "IQ": "ar",
        "SK": "pl", "SI": "easteu", "HR": "easteu", "RS": "easteu", "BG": "easteu", "LT": "easteu", "LV": "easteu", "EE": "nordic",
        "IS": "nordic", "BY": "easteu", "KZ": "easteu", "AZ": "tr", "CY": "easteu", "PK": "in", "BD": "in", "LK": "in", "NP": "in",
        "MM": "sea", "KH": "sea", "LA": "sea", "CN": "en", "MO": "en", "NG": "en", "KE": "en", "GH": "en", "JM": "en", "TT": "en",
    ]

    /// New players in join period p (7 days from the epoch + p weeks): a launch bump, then a slowly growing plateau.
    static func weeklyJoins(_ p: Int) -> Double {
        let pf = Double(p)
        let plateau = 12000.0 * (1.0 + 0.6 * pf / (pf + 40.0))
        let bump = 2.0 / (2.0 + pf)
        return plateau + 18000.0 * bump * bump
    }

    // ---------------------------------------------------------------- the reference tables (data.py, countries.tsv)

    /// design/social/data/countries.tsv, row for row (a test compares them).
    public static let referenceCountries: [SocialCountryRow] = referenceCountryTuples.map {
        SocialCountryRow(iso: $0.0, weight: $0.1, offsetMinutes: $0.2, culture: $0.3, bucket: $0.4)
    }
    static let referenceCountryTuples: [(String, Double, Int, String, String)] = [
        ("US", 21.0, -300, "en", "AMER_E"), ("US", 9.0, -480, "en", "AMER_W"), ("CA", 5.0, -300, "en", "AMER_E"),
        ("MX", 2.5, -360, "es", "AMER_E"), ("CO", 0.8, -300, "es", "AMER_E"), ("PE", 0.3, -300, "es", "AMER_E"),
        ("BR", 4.0, -180, "pt", "AMER_S"), ("AR", 1.0, -180, "es", "AMER_S"), ("CL", 0.6, -240, "es", "AMER_S"),
        ("GB", 7.0, 0, "en", "EUR_W"), ("IE", 0.8, 0, "en", "EUR_W"), ("PT", 0.6, 0, "pt", "EUR_W"),
        ("DE", 4.5, 60, "de", "EUR_C"), ("AT", 0.6, 60, "de", "EUR_C"), ("CH", 0.6, 60, "de", "EUR_C"),
        ("FR", 3.5, 60, "fr", "EUR_C"), ("BE", 0.8, 60, "nl", "EUR_C"), ("NL", 1.5, 60, "nl", "EUR_C"),
        ("ES", 2.0, 60, "es", "EUR_C"), ("IT", 2.0, 60, "it", "EUR_C"), ("SE", 1.0, 60, "nordic", "EUR_C"),
        ("NO", 0.6, 60, "nordic", "EUR_C"), ("DK", 0.6, 60, "nordic", "EUR_C"), ("PL", 1.5, 60, "pl", "EUR_C"),
        ("CZ", 0.4, 60, "easteu", "EUR_C"), ("HU", 0.3, 60, "easteu", "EUR_C"), ("FI", 0.5, 120, "nordic", "EUR_E"),
        ("RO", 0.5, 120, "easteu", "EUR_E"), ("GR", 0.4, 120, "easteu", "EUR_E"), ("UA", 0.4, 120, "easteu", "EUR_E"),
        ("IL", 0.5, 120, "en", "EUR_E"), ("EG", 0.4, 120, "ar", "EUR_E"), ("ZA", 0.8, 120, "en", "EUR_E"),
        ("RU", 0.5, 180, "easteu", "EUR_E"), ("TR", 2.0, 180, "tr", "EUR_E"), ("SA", 0.8, 180, "ar", "EUR_E"),
        ("AE", 0.6, 240, "ar", "ASIA_S"), ("IN", 2.0, 330, "in", "ASIA_S"), ("TH", 0.8, 420, "sea", "ASIA_SE"),
        ("VN", 0.3, 420, "sea", "ASIA_SE"), ("ID", 1.5, 420, "sea", "ASIA_SE"), ("PH", 2.0, 480, "sea", "ASIA_SE"),
        ("MY", 0.8, 480, "sea", "ASIA_SE"), ("SG", 0.6, 480, "sea", "ASIA_SE"), ("TW", 0.5, 480, "en", "ASIA_SE"),
        ("HK", 0.4, 480, "en", "ASIA_SE"), ("JP", 1.5, 540, "jp", "ASIA_E"), ("KR", 1.0, 540, "kr", "ASIA_E"),
        ("AU", 4.5, 600, "en", "ASIA_E"), ("NZ", 0.8, 720, "en", "ASIA_E"),
    ]

    static func arch(_ key: String, _ share: Double, daily: Bool = false, lam: ([Double], [Double]), life: ([Double], [Double]),
                     rho: Double, sess: (Int, Int), first: (Double, Double), lapse: (Double, Double)? = nil,
                     life2: ([Double], [Double])? = nil, gap: (Double, Double)? = nil, custom: Double,
                     avatar: (Double, Double)) -> SocialArchetype {
        SocialArchetype(key: key, share: share, daily: daily, lamX: lam.0, lamY: lam.1, lifeX: life.0, lifeY: life.1, rho: rho,
                        sessMin: sess.0, sessMax: sess.1, firstLo: first.0, firstHi: first.1,
                        lapse: lapse.map { (lo: $0.0, hi: $0.1) }, life2X: life2?.0, life2Y: life2?.1,
                        gap: gap.map { (lo: $0.0, hi: $0.1) }, custom: custom, avatarDefault: avatar.0, avatarCustom: avatar.1)
    }

    /// data.py ARCHETYPES, exactly.
    public static let referenceArchetypes: [SocialArchetype] = [
        arch("tourist", 0.400, daily: true, lam: ([0, 1], [4.0, 20.0]), life: ([0, 1], [0.005, 1.2]), rho: 1.0, sess: (1, 2),
             first: (2.0, 12.0), custom: 0.15, avatar: (0.08, 0.38)),
        arch("dabbler", 0.220, lam: ([0, 1], [6.0, 30.0]), life: ([0, 1], [1.5, 12.0]), rho: 0.55, sess: (1, 2),
             first: (5.0, 14.0), lapse: (20.0, 90.0), custom: 0.30, avatar: (0.10, 0.42)),
        arch("casual", 0.180, lam: ([0, 0.6, 0.9, 1], [5.0, 10.0, 18.0, 25.0]), life: ([0, 0.5, 1], [12.0, 35.0, 90.0]),
             rho: 0.45, sess: (1, 2), first: (6.0, 14.0), lapse: (45.0, 200.0), custom: 0.45, avatar: (0.12, 0.45)),
        arch("regular", 0.110, lam: ([0, 0.5, 0.9, 1], [10.0, 18.0, 32.0, 45.0]), life: ([0, 0.5, 1], [40.0, 140.0, 400.0]),
             rho: 0.70, sess: (1, 3), first: (6.0, 14.0), lapse: (60.0, 365.0), custom: 0.60, avatar: (0.12, 0.47)),
        arch("enthusiast", 0.045, lam: ([0, 0.5, 0.9, 1], [20.0, 35.0, 58.0, 75.0]), life: ([0, 0.5, 1], [150.0, 500.0, 1600.0]),
             rho: 0.88, sess: (2, 4), first: (8.0, 16.0), lapse: (90.0, 500.0), custom: 0.72, avatar: (0.14, 0.50)),
        arch("grinder", 0.006, lam: ([0, 0.5, 0.9, 0.98, 1], [42.0, 60.0, 79.0, 93.0, 128.0]),
             life: ([0, 0.5, 1], [250.0, 900.0, 3200.0]), rho: 0.97, sess: (3, 6), first: (8.0, 16.0), lapse: (90.0, 500.0),
             custom: 0.86, avatar: (0.15, 0.55)),
        arch("returner", 0.039, lam: ([0, 1], [8.0, 40.0]), life: ([0, 1], [3.0, 32.0]), rho: 0.55, sess: (1, 2),
             first: (6.0, 14.0), lapse: (30.0, 120.0), life2: ([0, 1], [30.0, 500.0]), gap: (15.0, 150.0), custom: 0.45,
             avatar: (0.12, 0.45)),
    ]

    /// The social designer's prototype, bit for bit (design/social/fixtures).
    public static let reference = SocialWorldModel(name: "reference", seed: worldSeed, archetypes: referenceArchetypes,
                                                   countries: referenceCountries)

    /// The calibrated v1 world: the reference re-calibrated to the owner's phone. Only these values differ; the Python
    /// reference applies the same patch (design/social/tools/socialsim/shipped.py), pinned by Tests/Fixtures/soc_v552_*.
    /// SOC1 (session 1, 25 Sep 11:27 — the boards' levels):
    ///   tourist    share 0.40 → 0.4844 (shares still sum to 1: the world keeps its size)
    ///   dabbler    λ 6→30 ⇒ 5→18, life 1.5→12 ⇒ 1→8 days, lapse 20→90 ⇒ 10→45 days
    ///   casual     share 0.18 → 0.16, λ 5/10/18/25 ⇒ 4/8/14/20, life 12/35/90 ⇒ 10/30/80, lapse 45→200 ⇒ 30→150
    ///   regular    share 0.11 → 0.09, λ 10/18/32/45 ⇒ 6/10/16/22, life 40/140/400 ⇒ 30/90/300
    ///   enthusiast share 0.045 → 0.006, λ 20/35/58/75 ⇒ 10/20/32/42, life 150/500/1600 ⇒ 60/200/600
    ///   grinder    share 0.006 → 0.0006, λ 42/60/79/93/128 ⇒ 25/50/88/100/108
    ///   names      longer than 16 characters → a fallback `player_` name; the stem "maze" is blocked too
    ///   avatars    1…8 (the 8 shipped portraits) instead of 1…14 (CONSISTENCY V-24)
    /// SOC1b (phone session 2, research/social-dynamics.md; build/soc1b/calibration.md):
    ///   custom     tourist .08, dabbler .80, casual .84, regular .86, enthusiast .88, grinder .90, returner .84 — the
    ///              phone's boards show ~14-18 % player_xxxxxxx, SOC1's 42 %; nickname mix + variants: SocialNameStyle.calibrated
    ///   honey      dabbler/casual/regular/returner play 2× until 5 days after their join week (Turkey: ~3.6 places per
    ///              level at L62-L84, SOC1's world 5.3)
    ///   sess       dabbler 1-4, casual 1-4, regular 2-5, enthusiast 3-6, returner 1-3 (Weekly rivals in bursts, ~40 %
    ///              idle all day), grinder 1-3 (World top rows static for hours, a few climb ~35 levels an hour)
    ///   countries  TR weight 0.5 → 0.30 (with the honeymoon more Turkish players pass L62; rank 430 at L62 vs 455)
    public static let calibrated: SocialWorldModel = {
        var a = referenceArchetypes
        func set(_ key: String, _ f: (inout SocialArchetype) -> Void) {
            if let i = a.firstIndex(where: { $0.key == key }) { f(&a[i]) }
        }
        set("tourist") { $0.share = 0.4844; $0.custom = 0.08 }
        set("dabbler") {
            $0.lamX = [0, 1]; $0.lamY = [5.0, 18.0]; $0.lifeX = [0, 1]; $0.lifeY = [1.0, 8.0]; $0.lapse = (10.0, 45.0)
            $0.custom = 0.80; $0.honey = (1.0, 5.0); $0.sessMin = 1; $0.sessMax = 4
        }
        set("casual") {
            $0.share = 0.16; $0.lamX = [0, 0.6, 0.9, 1]; $0.lamY = [4.0, 8.0, 14.0, 20.0]
            $0.lifeX = [0, 0.5, 1]; $0.lifeY = [10.0, 30.0, 80.0]; $0.lapse = (30.0, 150.0)
            $0.custom = 0.84; $0.honey = (1.0, 5.0); $0.sessMin = 1; $0.sessMax = 4
        }
        set("regular") {
            $0.share = 0.09; $0.lamX = [0, 0.5, 0.9, 1]; $0.lamY = [6.0, 10.0, 16.0, 22.0]
            $0.lifeX = [0, 0.5, 1]; $0.lifeY = [30.0, 90.0, 300.0]
            $0.custom = 0.86; $0.honey = (1.0, 5.0); $0.sessMin = 2; $0.sessMax = 5
        }
        set("enthusiast") {
            $0.share = 0.006; $0.lamX = [0, 0.5, 0.9, 1]; $0.lamY = [10.0, 20.0, 32.0, 42.0]
            $0.lifeX = [0, 0.5, 1]; $0.lifeY = [60.0, 200.0, 600.0]
            $0.custom = 0.88; $0.sessMin = 3; $0.sessMax = 6
        }
        set("grinder") {
            $0.share = 0.0006; $0.lamX = [0, 0.5, 0.9, 0.98, 1]; $0.lamY = [25.0, 50.0, 88.0, 100.0, 108.0]
            $0.custom = 0.90; $0.sessMin = 1; $0.sessMax = 3
        }
        set("returner") { $0.custom = 0.84; $0.honey = (1.0, 5.0); $0.sessMin = 1; $0.sessMax = 3 }
        var c = referenceCountries
        if let i = c.firstIndex(where: { $0.iso == "TR" }) { c[i].weight = 0.30 }
        // PUBLISH B0 (ruling 39 OD8) named it "shipped" (was "v552"); PUBLISH B2 (ruling 38 "one-time reshuffle accepted")
        // ships the v2 world below under that name, so this v1 world is "calibrated" (tests and its fixtures only). The name
        // selects, it seeds nothing.
        return SocialWorldModel(name: "calibrated", seed: worldSeed, archetypes: a, countries: c, maxNameLength: 16,
                                avatarCount: 8, extraBlockedStems: [SocialBlockedStem(length: 4, fnv: 0x1f20_5da2_ce68_3602)],
                                nameStyle: .calibrated)       // FIX-3 B: the title stem, hashed
    }()

    /// The SHIPPED world (PUBLISH B2; socialsim/v2.py = shipped.py's calibrated world + M1-M11). Archetypes, name cap,
    /// avatars and the extra stem are the calibrated world's; the country table, bands and region map are T6's v2 data
    /// (SocialIntlTables; Turkey's weight 0.39 re-fitted under M1 + M11 to the phone's rank 455 at L62); the nickname style
    /// adds the native-script shares and the scaled popularity head (SocialNameStyle.shipped). Pinned bit for bit by
    /// Tests/Fixtures/soc_v2_{world,events,intl}.json (design/social/tools/v2/fixtures_v2.py), Debug and -O.
    public static let shipped: SocialWorldModel = {
        var m = calibrated
        m.name = "shipped"
        m.countries = SocialIntlTables.countries
        m.nameStyle = .shipped
        m.epoch = GameConfig.worldEpoch                  // game.yml social.world_epoch: whole weeks after SocialCalendar.epoch
        m.intl = SocialIntl(
            buckets: SocialIntlTables.buckets.map(\.name), bucketOffsets: SocialIntlTables.buckets.map(\.offset),
            regions: SocialIntlTables.regions,
            countryBlocks: true, strata: 8, jitter: true, localByISO: true, memberCulture: true,
            // M9 (T6: the launch-week guards failed with M1-M8 alone): shard targets per archetype, >= 3 shards for regulars
            // and returners (India's launch-week board had 24 dead daytime hours; with >= 3 shards: 6)
            shardTarget: ["dabbler": 160.0, "casual": 80.0, "regular": 40.0, "returner": 40.0, "enthusiast": 40.0, "grinder": 40.0],
            minShards: ["regular": 3, "returner": 3],
            lagMinutes: 0.0,                              // M10 off (v2.py MEMBER_LAG_MIN = 0)
            // M11 (T6 fit_tr.py): Turkey's players lean dabbler / casual (the phone's Turkey board)
            rowTilt: ["TR": ["dabbler": 1.3, "casual": 1.3, "regular": 0.3, "returner": 0.3, "enthusiast": 0.3]])
        return m
    }()

    /// The world a config names: "reference" (the prototype), "calibrated" (the v1 phone-calibrated world), anything else
    /// ("shipped"; a legacy "v552") the shipped v2 world.
    public static func named(_ name: String) -> SocialWorldModel {
        switch name {
        case "reference": return .reference
        case "calibrated": return .calibrated
        default: return .shipped
        }
    }

    // ---------------------------------------------------------------- the home country (M3 + M4)

    /// The board a device region code plays on, and whether it needs a device-only LOCAL partition.
    ///   v2 (socialsim/v2.py world_for_home): a row, alias or numeric region plays on the shared world (two friends see the
    ///   same boards) under its board's ISO; a 2-letter code no table knows gets its own LOCAL partition; anything else
    ///   (nil, empty, a malformed code) the fallback country.
    ///   v1: any 2-letter code (LOCAL when the table has no row for it), else the fallback (SocialState.setHomeIfNeeded).
    public func homeBoard(forRegion code: String?, fallback: String = "US") -> (iso: String, local: Bool) {
        let c = (code ?? "").uppercased()
        if let intl {
            if let r = intl.regions[c] { return (r.board, false) }
            if c.count == 2 && c.allSatisfy(\.isLetter) { return (c, true) }
            return (fallback, false)
        }
        guard c.count == 2 else { return (fallback, false) }
        return (c, !countries.contains(where: { $0.iso == c }))
    }

    /// The ISO of the board a stored home country plays on (v2 resolves an alias / numeric code; v1 keeps it).
    public func boardCountry(_ code: String) -> String {
        let c = code.uppercased()
        if let r = intl?.regions[c] { return r.board }
        return c
    }

    /// SPEC-social §2.5 containment condition: every life table rises at least the cohort's join spread per unit of u,
    /// and λ, first, lapse, life2 never fall in u (=> level is non-decreasing in u; every query is a binary search).
    public func containmentHolds() -> Bool {
        for a in archetypes {
            let span = a.daily ? 1.0 : 7.0
            for i in 1..<a.lifeX.count where (a.lifeY[i] - a.lifeY[i - 1]) / (a.lifeX[i] - a.lifeX[i - 1]) < span { return false }
            func rising(_ ys: [Double]) -> Bool { zip(ys, ys.dropFirst()).allSatisfy { $0 <= $1 } }
            if !rising(a.lamY) || a.firstLo > a.firstHi { return false }
            if let l = a.lapse, l.lo > l.hi { return false }
            if let y = a.life2Y, !rising(y) { return false }
        }
        return true
    }
}

// ---------------------------------------------------------------------------------------------------------------------
// The v2 tables, parsed once from the generated TSV text (SocialIntlTables.swift). `Double(String)` / `Int(String)` restore
// exactly the values Python's float() / int() read from the same rows (data.use_countries_v2 / parse_mix).

extension SocialIntlTables {
    static func lines(_ tsv: String) -> [[String]] {
        tsv.split(separator: "\n").map { $0.split(separator: "\t", omittingEmptySubsequences: false).map(String.init) }
    }

    static let buckets: [(name: String, offset: Int)] = lines(bucketsTSV).map { ($0[0], Int($0[1])!) }

    /// data.parse_mix: 'nl:0.6,fr:0.4' -> [nl 0.6, fr 0.4]; 'en' -> [en 1.0].
    static func mix(_ s: String) -> [SocialCultureShare] {
        s.split(separator: ",").map { part in
            let kv = part.split(separator: ":")
            return kv.count == 2 ? SocialCultureShare(culture: String(kv[0]), weight: Double(String(kv[1]))!)
                : SocialCultureShare(culture: String(part), weight: 1.0)
        }
    }

    static let countries: [SocialCountryRow] = lines(countriesTSV).map { p in
        let m = mix(p[3])
        return SocialCountryRow(iso: p[0], weight: Double(p[1])!, offsetMinutes: Int(p[2])!, culture: m[0].culture, bucket: p[4],
                                mix: m)
    }

    static let regions: [String: SocialRegion] = {
        var out: [String: SocialRegion] = [:]
        for p in lines(regionsTSV) { out[p[0]] = SocialRegion(kind: SocialRegion.Kind(rawValue: p[1])!, board: p[2]) }
        return out
    }()
}
