// GENERATED by tools/game.py generate from the game's game.yml. Do not edit: edit game.yml, then run
// python3 tools/game.py generate --game <id> (doctor fails while this file is stale). No imports on purpose.
// swiftlint:disable all

/// The per-game constants of the genre-agnostic core (docs/TEMPLATE.md). The offline world is a pure function of these
/// + the clock, identical on every device: a different seed or epoch is a different world for every player.
public enum GameConfig {
    /// game.yml social.world_seed: every simulated player, name and country (SocialWorldModel.worldSeed).
    public static let worldSeed: UInt64 = 0x4152_4F57_204F_5554
    /// game.yml social.world_epoch (2026-09-07 07:00 UTC, a Monday): the shipped world's epoch (SocialWorldModel.shipped).
    public static let worldEpoch: Int = 1_788_764_400
    /// game.yml social.calendar_epoch (2026-04-27 07:00 UTC, a Monday): the event calendar's anchor (SocialCalendar.epoch,
    /// the EventRules calendar and rotation defaults; social.json events.rotation.epoch carries it too).
    public static let calendarEpoch: Int = 1_777_273_200
    /// game.yml social.rotation_seed: the weekly event rotation's seed (EventRules.Rotation default; social.json wins).
    public static let rotationSeed: String = "0x524F544154494F4E"
    public static let rotationSeedValue: UInt64 = 0x524F_5441_5449_4F4E
    /// game.yml identity.bundle_id + ".": the App Store product id prefix (ShopCatalog default; rules.json shop wins).
    public static let productPrefix: String = "com.manycode.arrowout."
}
