#!/usr/bin/env python3
"""soc_v2_tables.py — writes Sources/GameCore/Social/SocialIntlTables.swift, the v2 world's static tables, from the T6 data
(design/social/data_v2: buckets_v2.tsv, countries_v2.tsv, regions_v2.tsv; built by design/social/tools/v2/build_countries_v2.py).

PUBLISH B2 (PLAN-P §4.4, owner item 13): the Swift port reads the SAME rows the Python reference reads (data.use_countries_v2),
so the tables are embedded VERBATIM as TSV text (the documentation column `weight_basis` dropped) and parsed once at first
use with `Double(String)` / `Int(String)`, which restore the exact values Python's float() / int() read. A test
(SocialIntlTests.testTablesEqualTheTSVs) compares the compiled tables with the files row for row, so a stale generation
fails; the golden fixture soc_v2_intl.json pins them too.

    python3 Packages/PathCore/Tests/tools/soc_v2_tables.py          # (re)write the Swift file
    python3 Packages/PathCore/Tests/tools/soc_v2_tables.py --check  # exit 1 when the Swift file is not up to date
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.abspath(os.path.join(HERE, '..', '..'))
APP = os.path.abspath(os.path.join(PKG, '..', '..'))
DATA = os.path.join(APP, 'design', 'social', 'data_v2')
OUT = os.path.join(PKG, 'Sources', 'GameCore', 'Social', 'SocialIntlTables.swift')


def rows(name, ncols):
    out = []
    with open(os.path.join(DATA, name), encoding='utf-8') as f:
        for l in f:
            l = l.rstrip('\n')
            if not l or l.startswith('#'):
                continue
            p = l.split('\t')
            assert len(p) >= ncols, (name, l)
            for x in p[:ncols]:
                assert '"' not in x and '\\' not in x and x == x.strip(), (name, x)
            out.append('\t'.join(p[:ncols]))
    return out


def block(lines):
    return '\n'.join('        ' + l.replace('\t', '\\t') for l in lines)


def render():
    b = rows('buckets_v2.tsv', 2)
    c = rows('countries_v2.tsv', 5)
    r = rows('regions_v2.tsv', 3)
    return '''import Foundation

// GENERATED by Packages/PathCore/Tests/tools/soc_v2_tables.py from design/social/data_v2/{buckets_v2,countries_v2,regions_v2}.tsv
// (T6's build_countries_v2.py). Do not edit: rebuild the data and re-run the generator. PUBLISH B2 (social-intl §6 M3):
// the v2 world's timezone bands (%d), country rows (%d: iso, weight, standard offset in minutes, culture mix, band) and the
// region map (%d codes: every Locale.Region.isoRegions code -> row | alias | numeric, and the board it plays on).
// SocialIntlTests.testTablesEqualTheTSVs compares these rows with the files; soc_v2_intl.json pins them bit for bit.

enum SocialIntlTables {
    static let bucketsTSV = """
%s
        """

    static let countriesTSV = """
%s
        """

    static let regionsTSV = """
%s
        """
}
''' % (len(b), len(c), len(r), block(b), block(c), block(r))


def main():
    text = render()
    if '--check' in sys.argv[1:]:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        print('up to date' if cur == text else 'STALE: re-run soc_v2_tables.py')
        sys.exit(0 if cur == text else 1)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print('wrote', OUT, len(text), 'bytes')


if __name__ == '__main__':
    main()
