import CoreGraphics

// GENERATED by tools/skin/art.py from skin/scenes.json. Do not edit: edit the JSON, then run python3 tools/skin/art.py
// (docs/SKIN.md §4). No logic here: HomeView / LoadingScreen draw these lists.

/// The skin's scenes: what the home and Loading scenes draw, back to front, on the 393 x 852 reference canvas.
enum SkinScenes {
    /// One layer of a scene.
    struct Layer {
        enum Kind {
            case art(UIArt)             // a raster at `rect` (aspect fit; aspect fill over `rect` when `fill`)
            case rig(ArtRig)            // a puppet at its rig.json placement (its motion: ui.json puppet.<folder>)
            case centrepiece(ArtRig)    // home's centrepiece rig at `rect` (its idle loop and its refill steps)
        }
        let kind: Kind
        /// The ui.json frames key that places it ("" = `rect` as is); `rect` is that key's default (pt).
        let frameKey: String
        let rect: CGRect
        let fill: Bool
        /// The rig layers this stage draws (empty = every layer) or leaves out (skin/scenes.json rigParts).
        let only: [String]
        let excluding: [String]
    }

    /// A raster at a fixed rect (pt on the reference canvas).
    struct Placed {
        let art: UIArt
        let rect: CGRect
    }

    /// Home, behind the level controls: back to front.
    static let homeBack: [Layer] = [
        Layer(kind: .art(.homeBackdrop), frameKey: "", rect: CGRect(x: 0, y: 0, width: 393, height: 852), fill: true, only: [], excluding: []),
        Layer(kind: .rig(.homeCharacterMain), frameKey: "", rect: .zero, fill: false, only: [], excluding: ["armL", "armR", "armR_point"]),
        Layer(kind: .art(.homeStation), frameKey: "home.scene.console", rect: CGRect(x: 109, y: 176, width: 191, height: 192), fill: false, only: [], excluding: []),
        Layer(kind: .rig(.homeCharacterMain), frameKey: "", rect: .zero, fill: false, only: ["armL", "armR", "armR_point"], excluding: []),
        Layer(kind: .art(.homeFloor), frameKey: "home.scene.platform", rect: CGRect(x: 0, y: 576, width: 393, height: 182), fill: false, only: [], excluding: []),
        Layer(kind: .art(.homeStand), frameKey: "home.scene.capsuleMachine", rect: CGRect(x: 95, y: 365, width: 206, height: 215), fill: false, only: [], excluding: []),
        Layer(kind: .centrepiece(.homeCentrepiece), frameKey: "home.scene.arrowPile", rect: CGRect(x: 101.5, y: 385.96, width: 190, height: 128), fill: false, only: [], excluding: []),
    ]

    /// Home, in front of the level controls (behind the top bar).
    static let homeFront: [Layer] = [
        Layer(kind: .rig(.homeCharacterLeft), frameKey: "", rect: .zero, fill: false, only: [], excluding: []),
        Layer(kind: .rig(.homeCharacterRight), frameKey: "", rect: .zero, fill: false, only: [], excluding: []),
    ]

    /// Loading: the full-bleed backdrop (aspect fill), the logo (at ui.json frames.loading.logo) and the cast, back to front.
    static let loadingBackdrop: UIArt = .loadingBackdrop
    static let loadingLogo: UIArt = .logoMain
    static let loadingCast: [Placed] = [
        Placed(art: .loadingCast1, rect: CGRect(x: -6, y: 434, width: 96, height: 76)),
        Placed(art: .loadingCast2, rect: CGRect(x: 270.75, y: 399.56, width: 153, height: 144)),
        Placed(art: .loadingCast3, rect: CGRect(x: 81.26, y: 334.28, width: 210, height: 250)),
        Placed(art: .loadingCast4, rect: CGRect(x: 208.7, y: 153.69, width: 170, height: 160)),
        Placed(art: .loadingCast5, rect: CGRect(x: 208.55, y: 545.69, width: 180, height: 220)),
        Placed(art: .loadingCast6, rect: CGRect(x: -9.91, y: 573.89, width: 270, height: 280)),
    ]
}
