// GENERATED by tools/skin/build.py from skin/fonts.json and skin/names.json. Do not edit: edit the JSON
// (docs/SKIN.md), then run python3 tools/skin/build.py. No imports on purpose (plain constants).
// swiftlint:disable all

/// The text faces by `GameTextStyle.Face` role (skin/fonts.json): PostScript names, and the bundled files
/// (App/Resources/Fonts; Info.plist UIAppFonts lists them as "Fonts/<file>").
enum SkinFonts {
    static let black = "PCDisplay-Black"  // Fonts/PCDisplay-Black.ttf
    static let blackItalic = "PCDisplay-BlackItalic"  // Fonts/PCDisplay-BlackItalic.ttf
    /// Every face's PostScript name (the boot check and the font tests resolve each).
    static let postScriptNames: [String] = [black, blackItalic]
    /// The font files of the faces, in role order.
    static let files: [String] = ["PCDisplay-Black.ttf", "PCDisplay-BlackItalic.ttf"]
}

/// Names the skin shows that are not translated copy (skin/names.json).
enum SkinNames {
    /// the Weekly Cup intro podium's three sample players, left to right
    static let podiumSampleNames: [String] = ["Max", "Neo", "James"]
}
