import CoreGraphics

// GENERATED by tools/uiart_gen.py from art/MANIFEST.json — do not edit by hand (SPEC-architecture §6.11).
// 200 shipped raster ids (svg + 3d families). Loader + placeholder: ArtStore.swift.

enum UIArt: String, CaseIterable, Sendable {
    case avatarBoss
    case avatarConfetti
    case avatarDefault
    case avatarLunch
    case avatarMapper
    case avatarMiner
    case avatarSleepy
    case avatarSleuth
    case avatarStrong
    case badgeCloudHop
    case badgeHotStreak
    case badgeRocketRally
    case balloonCloudA
    case balloonCloudB
    case balloonHero
    case balloonLedge
    case balloonTowerFoot
    case balloonTowerShaft
    case balloonTowerTop
    case boardTrailStar
    case boosterFreeze
    case boosterHint
    case bossLoading
    case boxRing
    case boxSlab
    case bundleBag
    case bundleBarrel
    case bundleCart
    case bundleChest
    case bundleSafe
    case bundleSpecial
    case coinBowl
    case coinPackBig
    case coinPackGiant
    case coinPackMedium
    case coinPackSmall
    case coinPackSuper
    case coinPackTiny
    case coinPileSmall
    case coinStackReward
    case cornerDownLeftPlate
    case cornerDownLeftSpring
    case cornerDownRightPlate
    case cornerDownRightSpring
    case cornerUpLeftPlate
    case cornerUpLeftSpring
    case cornerUpRightPlate
    case cornerUpRightSpring
    case cornerWedge
    case cupPodium
    case digCart
    case digDockL
    case digFlyer
    case digPop1
    case digPop2
    case doorShards
    case doorW11H10
    case doorW13H4
    case doorW22H10
    case doorW4H12
    case doorW4H16
    case doorW4H20
    case doorW4H4
    case doorW4H8
    case doorW5H17
    case eventBadgeBalloon
    case fxFrostVignette
    case glyphBell
    case glyphGear
    case glyphHaptic
    case glyphHapticWhite
    case glyphMusic
    case glyphOffSlash
    case glyphSound
    case glyphSoundWhite
    case heartBig
    case heartBroken
    case heartGlossySmall
    case heartHUD
    case heartHUDHalves
    case heartHUDLost
    case heartInfinite
    case heartInfiniteSmall
    case heartLives
    case heartLivesBig
    case homeCabinet
    case homeFloor
    case homeScaffold
    case homeSignpost
    case homeWorkshop
    case hopBackdrop
    case hopDrum
    case hopIsland
    case hopIslandFar
    case hopIslandFar2
    case hopOfferScene
    case hopPad
    case iconCheck
    case iconCheckBadge
    case iconCheckeredFlag
    case iconCoin
    case iconPencil
    case iconPlusGreen
    case iconSkull
    case iconSkullBones
    case iconStopwatch
    case iconStopwatchFrozen
    case iconStopwatchSmall
    case infoPathIcon
    case keyOnArrow
    case loadingBackdrop
    case lockHex
    case logoArrowOut
    case logoLetterA
    case logoLetterAExt
    case logoLetterAFace
    case logoLetterAFlat
    case logoLetterO
    case logoLetterOExt
    case logoLetterOFace
    case logoLetterOFlat
    case logoLetterR1
    case logoLetterR1Ext
    case logoLetterR1Face
    case logoLetterR1Flat
    case logoLetterR2
    case logoLetterR2Ext
    case logoLetterR2Face
    case logoLetterR2Flat
    case logoLetterW
    case logoLetterWExt
    case logoLetterWFace
    case logoLetterWFlat
    case logoOut
    case logoOutBang
    case logoOutBangExt
    case logoOutBangFace
    case logoOutO
    case logoOutOExt
    case logoOutOFace
    case logoOutT
    case logoOutTExt
    case logoOutTFace
    case logoOutU
    case logoOutUExt
    case logoOutUFace
    case logoPegs
    case logoSignBlue
    case logoSignPurple
    case logoSignPurpleBend100
    case logoSignPurpleBend25
    case logoSignPurpleBend50
    case logoSignPurpleBend75
    case navCart
    case navCup
    case navLodge
    case padlockGold
    case pageBgPattern
    case pipeCounter
    case pipeMouth
    case pipeShards
    case planetStage1
    case planetStage2
    case planetStage3
    case pointerArrowDown
    case pointerArrowYellow
    case rallyBackdrop
    case rallyOfferScene
    case rallyRocketMine
    case rallyRocketOther
    case rankBadgeBronze
    case rankBadgeGold
    case rankBadgeSilver
    case rankWings1
    case scoreChip
    case shopSeal
    case sparkleTwinkle
    case stageChestBlue
    case stageChestGreen
    case stageChestPink
    case statFirstTryIcon
    case statWeeklyWinsIcon
    case stopwatchBig
    case streakHeader
    case sunburstRays
    case tapeH2
    case tapeH3
    case tapeH4
    case tapeV2
    case tapeV3
    case tapeV4
    case treasureHeader
    case treasureToken
    case tutorialHand
    case unlockIconBox
    case unlockIconCorner
    case unlockIconDoor
    case unlockIconElevator
    case unlockIconLinked
    case unlockIconPipe

    /// The file inside the app bundle (tools/sync_art.sh: art/ui/out -> UI/, art/out -> Art/).
    var path: String {
        switch self {
        case .avatarBoss: return "Art/char_avatarBoss@3x.png"
        case .avatarConfetti: return "Art/char_avatarConfetti@3x.png"
        case .avatarDefault: return "UI/avatarDefault@3x.png"
        case .avatarLunch: return "Art/char_avatarLunch@3x.png"
        case .avatarMapper: return "Art/char_avatarMapper@3x.png"
        case .avatarMiner: return "Art/char_avatarMiner@3x.png"
        case .avatarSleepy: return "Art/char_avatarSleepy@3x.png"
        case .avatarSleuth: return "Art/char_avatarSleuth@3x.png"
        case .avatarStrong: return "Art/char_avatarStrong@3x.png"
        case .badgeCloudHop: return "Art/badgeCloudHop@3x.png"
        case .badgeHotStreak: return "Art/badgeHotStreak@3x.png"
        case .badgeRocketRally: return "Art/badgeRocketRally@3x.png"
        case .balloonCloudA: return "UI/balloonCloudA@3x.png"
        case .balloonCloudB: return "UI/balloonCloudB@3x.png"
        case .balloonHero: return "Art/balloonHero@3x.png"
        case .balloonLedge: return "UI/balloonLedge@3x.png"
        case .balloonTowerFoot: return "Art/balloonTowerFoot@3x.png"
        case .balloonTowerShaft: return "UI/balloonTowerShaft@3x.png"
        case .balloonTowerTop: return "Art/balloonTowerTop@3x.png"
        case .boardTrailStar: return "UI/boardTrailStar@3x.png"
        case .boosterFreeze: return "UI/boosterFreeze@3x.png"
        case .boosterHint: return "UI/boosterHint@3x.png"
        case .bossLoading: return "Art/char_bossLoading@3x.png"
        case .boxRing: return "UI/boxRing@3x.png"
        case .boxSlab: return "UI/boxSlab@3x.png"
        case .bundleBag: return "UI/bundleBag@3x.png"
        case .bundleBarrel: return "UI/bundleBarrel@3x.png"
        case .bundleCart: return "UI/bundleCart@3x.png"
        case .bundleChest: return "UI/bundleChest@3x.png"
        case .bundleSafe: return "UI/bundleSafe@3x.png"
        case .bundleSpecial: return "UI/bundleSpecial@3x.png"
        case .coinBowl: return "UI/coinBowl@3x.png"
        case .coinPackBig: return "UI/coinPackBig@3x.png"
        case .coinPackGiant: return "UI/coinPackGiant@3x.png"
        case .coinPackMedium: return "UI/coinPackMedium@3x.png"
        case .coinPackSmall: return "UI/coinPackSmall@3x.png"
        case .coinPackSuper: return "UI/coinPackSuper@3x.png"
        case .coinPackTiny: return "UI/coinPackTiny@3x.png"
        case .coinPileSmall: return "UI/coinPileSmall@3x.png"
        case .coinStackReward: return "UI/coinStackReward@3x.png"
        case .cornerDownLeftPlate: return "UI/cornerDownLeftPlate@3x.png"
        case .cornerDownLeftSpring: return "UI/cornerDownLeftSpring@3x.png"
        case .cornerDownRightPlate: return "UI/cornerDownRightPlate@3x.png"
        case .cornerDownRightSpring: return "UI/cornerDownRightSpring@3x.png"
        case .cornerUpLeftPlate: return "UI/cornerUpLeftPlate@3x.png"
        case .cornerUpLeftSpring: return "UI/cornerUpLeftSpring@3x.png"
        case .cornerUpRightPlate: return "UI/cornerUpRightPlate@3x.png"
        case .cornerUpRightSpring: return "UI/cornerUpRightSpring@3x.png"
        case .cornerWedge: return "UI/cornerWedge@3x.png"
        case .cupPodium: return "Art/cupPodium@3x.png"
        case .digCart: return "Art/char_digCart@3x.png"
        case .digDockL: return "Art/char_digDockL@3x.png"
        case .digFlyer: return "Art/char_digFlyer@3x.png"
        case .digPop1: return "Art/char_digPop1@3x.png"
        case .digPop2: return "Art/char_digPop2@3x.png"
        case .doorShards: return "UI/doorShards@3x.png"
        case .doorW11H10: return "UI/doorW11H10@3x.png"
        case .doorW13H4: return "UI/doorW13H4@3x.png"
        case .doorW22H10: return "UI/doorW22H10@3x.png"
        case .doorW4H12: return "UI/doorW4H12@3x.png"
        case .doorW4H16: return "UI/doorW4H16@3x.png"
        case .doorW4H20: return "UI/doorW4H20@3x.png"
        case .doorW4H4: return "UI/doorW4H4@3x.png"
        case .doorW4H8: return "UI/doorW4H8@3x.png"
        case .doorW5H17: return "UI/doorW5H17@3x.png"
        case .eventBadgeBalloon: return "Art/eventBadgeBalloon@3x.png"
        case .fxFrostVignette: return "UI/fxFrostVignette@3x.png"
        case .glyphBell: return "UI/glyphBell@3x.png"
        case .glyphGear: return "UI/glyphGear@3x.png"
        case .glyphHaptic: return "UI/glyphHaptic@3x.png"
        case .glyphHapticWhite: return "UI/glyphHapticWhite@3x.png"
        case .glyphMusic: return "UI/glyphMusic@3x.png"
        case .glyphOffSlash: return "UI/glyphOffSlash@3x.png"
        case .glyphSound: return "UI/glyphSound@3x.png"
        case .glyphSoundWhite: return "UI/glyphSoundWhite@3x.png"
        case .heartBig: return "UI/heartBig@3x.png"
        case .heartBroken: return "UI/heartBroken@3x.png"
        case .heartGlossySmall: return "UI/heartGlossySmall@3x.png"
        case .heartHUD: return "UI/heartHUD@3x.png"
        case .heartHUDHalves: return "UI/heartHUDHalves@3x.png"
        case .heartHUDLost: return "UI/heartHUDLost@3x.png"
        case .heartInfinite: return "UI/heartInfinite@3x.png"
        case .heartInfiniteSmall: return "UI/heartInfiniteSmall@3x.png"
        case .heartLives: return "UI/heartLives@3x.png"
        case .heartLivesBig: return "UI/heartLivesBig@3x.png"
        case .homeCabinet: return "Art/homeCabinet@3x.png"
        case .homeFloor: return "Art/homeFloor@3x.png"
        case .homeScaffold: return "Art/homeScaffold@3x.png"
        case .homeSignpost: return "Art/homeSignpost@3x.png"
        case .homeWorkshop: return "Art/homeWorkshop@3x.png"
        case .hopBackdrop: return "Art/hopBackdrop@3x.png"
        case .hopDrum: return "UI/hopDrum@3x.png"
        case .hopIsland: return "Art/hopIsland@3x.png"
        case .hopIslandFar: return "Art/hopIslandFar@3x.png"
        case .hopIslandFar2: return "Art/hopIslandFar2@3x.png"
        case .hopOfferScene: return "Art/hopOfferScene@3x.png"
        case .hopPad: return "Art/hopPad@3x.png"
        case .iconCheck: return "UI/iconCheck@3x.png"
        case .iconCheckBadge: return "UI/iconCheckBadge@3x.png"
        case .iconCheckeredFlag: return "UI/iconCheckeredFlag@3x.png"
        case .iconCoin: return "UI/iconCoin@3x.png"
        case .iconPencil: return "UI/iconPencil@3x.png"
        case .iconPlusGreen: return "UI/iconPlusGreen@3x.png"
        case .iconSkull: return "UI/iconSkull@3x.png"
        case .iconSkullBones: return "UI/iconSkullBones@3x.png"
        case .iconStopwatch: return "UI/iconStopwatch@3x.png"
        case .iconStopwatchFrozen: return "UI/iconStopwatchFrozen@3x.png"
        case .iconStopwatchSmall: return "UI/iconStopwatchSmall@3x.png"
        case .infoPathIcon: return "UI/infoPathIcon@3x.png"
        case .keyOnArrow: return "UI/keyOnArrow@3x.png"
        case .loadingBackdrop: return "Art/loadingBackdrop@3x.png"
        case .lockHex: return "UI/lockHex@3x.png"
        case .logoArrowOut: return "UI/logoArrowOut@3x.png"
        case .logoLetterA: return "UI/logoLetterA@3x.png"
        case .logoLetterAExt: return "UI/logoLetterAExt@3x.png"
        case .logoLetterAFace: return "UI/logoLetterAFace@3x.png"
        case .logoLetterAFlat: return "UI/logoLetterAFlat@3x.png"
        case .logoLetterO: return "UI/logoLetterO@3x.png"
        case .logoLetterOExt: return "UI/logoLetterOExt@3x.png"
        case .logoLetterOFace: return "UI/logoLetterOFace@3x.png"
        case .logoLetterOFlat: return "UI/logoLetterOFlat@3x.png"
        case .logoLetterR1: return "UI/logoLetterR1@3x.png"
        case .logoLetterR1Ext: return "UI/logoLetterR1Ext@3x.png"
        case .logoLetterR1Face: return "UI/logoLetterR1Face@3x.png"
        case .logoLetterR1Flat: return "UI/logoLetterR1Flat@3x.png"
        case .logoLetterR2: return "UI/logoLetterR2@3x.png"
        case .logoLetterR2Ext: return "UI/logoLetterR2Ext@3x.png"
        case .logoLetterR2Face: return "UI/logoLetterR2Face@3x.png"
        case .logoLetterR2Flat: return "UI/logoLetterR2Flat@3x.png"
        case .logoLetterW: return "UI/logoLetterW@3x.png"
        case .logoLetterWExt: return "UI/logoLetterWExt@3x.png"
        case .logoLetterWFace: return "UI/logoLetterWFace@3x.png"
        case .logoLetterWFlat: return "UI/logoLetterWFlat@3x.png"
        case .logoOut: return "UI/logoOut@3x.png"
        case .logoOutBang: return "UI/logoOutBang@3x.png"
        case .logoOutBangExt: return "UI/logoOutBangExt@3x.png"
        case .logoOutBangFace: return "UI/logoOutBangFace@3x.png"
        case .logoOutO: return "UI/logoOutO@3x.png"
        case .logoOutOExt: return "UI/logoOutOExt@3x.png"
        case .logoOutOFace: return "UI/logoOutOFace@3x.png"
        case .logoOutT: return "UI/logoOutT@3x.png"
        case .logoOutTExt: return "UI/logoOutTExt@3x.png"
        case .logoOutTFace: return "UI/logoOutTFace@3x.png"
        case .logoOutU: return "UI/logoOutU@3x.png"
        case .logoOutUExt: return "UI/logoOutUExt@3x.png"
        case .logoOutUFace: return "UI/logoOutUFace@3x.png"
        case .logoPegs: return "UI/logoPegs@3x.png"
        case .logoSignBlue: return "UI/logoSignBlue@3x.png"
        case .logoSignPurple: return "UI/logoSignPurple@3x.png"
        case .logoSignPurpleBend100: return "UI/logoSignPurpleBend100@3x.png"
        case .logoSignPurpleBend25: return "UI/logoSignPurpleBend25@3x.png"
        case .logoSignPurpleBend50: return "UI/logoSignPurpleBend50@3x.png"
        case .logoSignPurpleBend75: return "UI/logoSignPurpleBend75@3x.png"
        case .navCart: return "UI/navCart@3x.png"
        case .navCup: return "UI/navCup@3x.png"
        case .navLodge: return "UI/navLodge@3x.png"
        case .padlockGold: return "UI/padlockGold@3x.png"
        case .pageBgPattern: return "UI/pageBgPattern@3x.png"
        case .pipeCounter: return "UI/pipeCounter@3x.png"
        case .pipeMouth: return "UI/pipeMouth@3x.png"
        case .pipeShards: return "UI/pipeShards@3x.png"
        case .planetStage1: return "UI/planetStage1@3x.png"
        case .planetStage2: return "UI/planetStage2@3x.png"
        case .planetStage3: return "UI/planetStage3@3x.png"
        case .pointerArrowDown: return "UI/pointerArrowDown@3x.png"
        case .pointerArrowYellow: return "UI/pointerArrowYellow@3x.png"
        case .rallyBackdrop: return "Art/rallyBackdrop@3x.png"
        case .rallyOfferScene: return "Art/rallyOfferScene@3x.png"
        case .rallyRocketMine: return "UI/rallyRocketMine@3x.png"
        case .rallyRocketOther: return "UI/rallyRocketOther@3x.png"
        case .rankBadgeBronze: return "UI/rankBadgeBronze@3x.png"
        case .rankBadgeGold: return "UI/rankBadgeGold@3x.png"
        case .rankBadgeSilver: return "UI/rankBadgeSilver@3x.png"
        case .rankWings1: return "UI/rankWings1@3x.png"
        case .scoreChip: return "UI/scoreChip@3x.png"
        case .shopSeal: return "UI/shopSeal@3x.png"
        case .sparkleTwinkle: return "UI/sparkleTwinkle@3x.png"
        case .stageChestBlue: return "UI/stageChestBlue@3x.png"
        case .stageChestGreen: return "UI/stageChestGreen@3x.png"
        case .stageChestPink: return "UI/stageChestPink@3x.png"
        case .statFirstTryIcon: return "UI/statFirstTryIcon@3x.png"
        case .statWeeklyWinsIcon: return "UI/statWeeklyWinsIcon@3x.png"
        case .stopwatchBig: return "UI/stopwatchBig@3x.png"
        case .streakHeader: return "Art/streakHeader@3x.png"
        case .sunburstRays: return "UI/sunburstRays@3x.png"
        case .tapeH2: return "UI/tapeH2@3x.png"
        case .tapeH3: return "UI/tapeH3@3x.png"
        case .tapeH4: return "UI/tapeH4@3x.png"
        case .tapeV2: return "UI/tapeV2@3x.png"
        case .tapeV3: return "UI/tapeV3@3x.png"
        case .tapeV4: return "UI/tapeV4@3x.png"
        case .treasureHeader: return "Art/treasureHeader@3x.png"
        case .treasureToken: return "UI/treasureToken@3x.png"
        case .tutorialHand: return "UI/tutorialHand@3x.png"
        case .unlockIconBox: return "UI/unlockIconBox@3x.png"
        case .unlockIconCorner: return "UI/unlockIconCorner@3x.png"
        case .unlockIconDoor: return "UI/unlockIconDoor@3x.png"
        case .unlockIconElevator: return "UI/unlockIconElevator@3x.png"
        case .unlockIconLinked: return "UI/unlockIconLinked@3x.png"
        case .unlockIconPipe: return "UI/unlockIconPipe@3x.png"
        }
    }

    /// The manifest size in pt (the @3x file is 3x this).
    var sizePt: CGSize {
        switch self {
        case .avatarBoss: return CGSize(width: 64, height: 64)
        case .avatarConfetti: return CGSize(width: 64, height: 64)
        case .avatarDefault: return CGSize(width: 64, height: 64)
        case .avatarLunch: return CGSize(width: 64, height: 64)
        case .avatarMapper: return CGSize(width: 64, height: 64)
        case .avatarMiner: return CGSize(width: 64, height: 64)
        case .avatarSleepy: return CGSize(width: 64, height: 64)
        case .avatarSleuth: return CGSize(width: 64, height: 64)
        case .avatarStrong: return CGSize(width: 64, height: 64)
        case .badgeCloudHop: return CGSize(width: 80, height: 84)
        case .badgeHotStreak: return CGSize(width: 80, height: 84)
        case .badgeRocketRally: return CGSize(width: 80, height: 84)
        case .balloonCloudA: return CGSize(width: 150, height: 70)
        case .balloonCloudB: return CGSize(width: 100, height: 56)
        case .balloonHero: return CGSize(width: 150, height: 220)
        case .balloonLedge: return CGSize(width: 240, height: 150)
        case .balloonTowerFoot: return CGSize(width: 393, height: 700)
        case .balloonTowerShaft: return CGSize(width: 112, height: 340)
        case .balloonTowerTop: return CGSize(width: 393, height: 470)
        case .boardTrailStar: return CGSize(width: 12, height: 12)
        case .boosterFreeze: return CGSize(width: 56, height: 56)
        case .boosterHint: return CGSize(width: 56, height: 56)
        case .bossLoading: return CGSize(width: 210, height: 250)
        case .boxRing: return CGSize(width: 76, height: 76)
        case .boxSlab: return CGSize(width: 104, height: 104)
        case .bundleBag: return CGSize(width: 176, height: 102)
        case .bundleBarrel: return CGSize(width: 176, height: 102)
        case .bundleCart: return CGSize(width: 176, height: 102)
        case .bundleChest: return CGSize(width: 176, height: 102)
        case .bundleSafe: return CGSize(width: 176, height: 102)
        case .bundleSpecial: return CGSize(width: 176, height: 102)
        case .coinBowl: return CGSize(width: 74, height: 62)
        case .coinPackBig: return CGSize(width: 102, height: 66)
        case .coinPackGiant: return CGSize(width: 102, height: 66)
        case .coinPackMedium: return CGSize(width: 102, height: 66)
        case .coinPackSmall: return CGSize(width: 102, height: 66)
        case .coinPackSuper: return CGSize(width: 102, height: 66)
        case .coinPackTiny: return CGSize(width: 102, height: 66)
        case .coinPileSmall: return CGSize(width: 68, height: 56)
        case .coinStackReward: return CGSize(width: 110, height: 100)
        case .cornerDownLeftPlate: return CGSize(width: 64, height: 64)
        case .cornerDownLeftSpring: return CGSize(width: 64, height: 64)
        case .cornerDownRightPlate: return CGSize(width: 64, height: 64)
        case .cornerDownRightSpring: return CGSize(width: 64, height: 64)
        case .cornerUpLeftPlate: return CGSize(width: 64, height: 64)
        case .cornerUpLeftSpring: return CGSize(width: 64, height: 64)
        case .cornerUpRightPlate: return CGSize(width: 64, height: 64)
        case .cornerUpRightSpring: return CGSize(width: 64, height: 64)
        case .cornerWedge: return CGSize(width: 64, height: 64)
        case .cupPodium: return CGSize(width: 389, height: 206)
        case .digCart: return CGSize(width: 270, height: 280)
        case .digDockL: return CGSize(width: 96, height: 76)
        case .digFlyer: return CGSize(width: 180, height: 220)
        case .digPop1: return CGSize(width: 170, height: 160)
        case .digPop2: return CGSize(width: 170, height: 160)
        case .doorShards: return CGSize(width: 48, height: 48)
        case .doorW11H10: return CGSize(width: 358, height: 326)
        case .doorW13H4: return CGSize(width: 422, height: 134)
        case .doorW22H10: return CGSize(width: 710, height: 326)
        case .doorW4H12: return CGSize(width: 134, height: 390)
        case .doorW4H16: return CGSize(width: 134, height: 518)
        case .doorW4H20: return CGSize(width: 134, height: 646)
        case .doorW4H4: return CGSize(width: 134, height: 134)
        case .doorW4H8: return CGSize(width: 134, height: 262)
        case .doorW5H17: return CGSize(width: 166, height: 550)
        case .eventBadgeBalloon: return CGSize(width: 46, height: 46)
        case .fxFrostVignette: return CGSize(width: 393, height: 852)
        case .glyphBell: return CGSize(width: 30, height: 36)
        case .glyphGear: return CGSize(width: 26, height: 26)
        case .glyphHaptic: return CGSize(width: 34, height: 33)
        case .glyphHapticWhite: return CGSize(width: 42, height: 38)
        case .glyphMusic: return CGSize(width: 38, height: 36)
        case .glyphOffSlash: return CGSize(width: 56, height: 52)
        case .glyphSound: return CGSize(width: 30, height: 30)
        case .glyphSoundWhite: return CGSize(width: 42, height: 38)
        case .heartBig: return CGSize(width: 194, height: 164)
        case .heartBroken: return CGSize(width: 160, height: 132)
        case .heartGlossySmall: return CGSize(width: 46, height: 40)
        case .heartHUD: return CGSize(width: 31, height: 27)
        case .heartHUDHalves: return CGSize(width: 31, height: 27)
        case .heartHUDLost: return CGSize(width: 31, height: 27)
        case .heartInfinite: return CGSize(width: 92, height: 84)
        case .heartInfiniteSmall: return CGSize(width: 46, height: 42)
        case .heartLives: return CGSize(width: 42, height: 40)
        case .heartLivesBig: return CGSize(width: 100, height: 90)
        case .homeCabinet: return CGSize(width: 206, height: 215)
        case .homeFloor: return CGSize(width: 393, height: 182)
        case .homeScaffold: return CGSize(width: 191, height: 192)
        case .homeSignpost: return CGSize(width: 190, height: 128)
        case .homeWorkshop: return CGSize(width: 393, height: 852)
        case .hopBackdrop: return CGSize(width: 393, height: 852)
        case .hopDrum: return CGSize(width: 57, height: 52)
        case .hopIsland: return CGSize(width: 260, height: 256)
        case .hopIslandFar: return CGSize(width: 166, height: 158)
        case .hopIslandFar2: return CGSize(width: 144, height: 132)
        case .hopOfferScene: return CGSize(width: 330, height: 190)
        case .hopPad: return CGSize(width: 112, height: 104)
        case .iconCheck: return CGSize(width: 60, height: 54)
        case .iconCheckBadge: return CGSize(width: 40, height: 34)
        case .iconCheckeredFlag: return CGSize(width: 30, height: 32)
        case .iconCoin: return CGSize(width: 39, height: 39)
        case .iconPencil: return CGSize(width: 32, height: 32)
        case .iconPlusGreen: return CGSize(width: 24, height: 24)
        case .iconSkull: return CGSize(width: 30, height: 32)
        case .iconSkullBones: return CGSize(width: 38, height: 38)
        case .iconStopwatch: return CGSize(width: 33, height: 33)
        case .iconStopwatchFrozen: return CGSize(width: 34, height: 50)
        case .iconStopwatchSmall: return CGSize(width: 26, height: 28)
        case .infoPathIcon: return CGSize(width: 118, height: 118)
        case .keyOnArrow: return CGSize(width: 43, height: 78)
        case .loadingBackdrop: return CGSize(width: 393, height: 852)
        case .lockHex: return CGSize(width: 73, height: 68)
        case .logoArrowOut: return CGSize(width: 306, height: 236)
        case .logoLetterA: return CGSize(width: 54.8825, height: 82.3237)
        case .logoLetterAExt: return CGSize(width: 54.8825, height: 82.3237)
        case .logoLetterAFace: return CGSize(width: 54.8825, height: 82.3237)
        case .logoLetterAFlat: return CGSize(width: 54.8825, height: 82.3237)
        case .logoLetterO: return CGSize(width: 54.8825, height: 79.485)
        case .logoLetterOExt: return CGSize(width: 54.8825, height: 79.485)
        case .logoLetterOFace: return CGSize(width: 54.8825, height: 79.485)
        case .logoLetterOFlat: return CGSize(width: 54.8825, height: 79.485)
        case .logoLetterR1: return CGSize(width: 49.205, height: 78.5387)
        case .logoLetterR1Ext: return CGSize(width: 49.205, height: 78.5387)
        case .logoLetterR1Face: return CGSize(width: 49.205, height: 78.5387)
        case .logoLetterR1Flat: return CGSize(width: 49.205, height: 78.5387)
        case .logoLetterR2: return CGSize(width: 50.1512, height: 79.485)
        case .logoLetterR2Ext: return CGSize(width: 50.1512, height: 79.485)
        case .logoLetterR2Face: return CGSize(width: 50.1512, height: 79.485)
        case .logoLetterR2Flat: return CGSize(width: 50.1512, height: 79.485)
        case .logoLetterW: return CGSize(width: 61.5062, height: 82.3237)
        case .logoLetterWExt: return CGSize(width: 61.5062, height: 82.3237)
        case .logoLetterWFace: return CGSize(width: 61.5062, height: 82.3237)
        case .logoLetterWFlat: return CGSize(width: 61.5062, height: 82.3237)
        case .logoOut: return CGSize(width: 153.292, height: 64.9758)
        case .logoOutBang: return CGSize(width: 23.1529, height: 62.4122)
        case .logoOutBangExt: return CGSize(width: 23.1529, height: 62.4122)
        case .logoOutBangFace: return CGSize(width: 23.1529, height: 62.4122)
        case .logoOutO: return CGSize(width: 57.379, height: 63.4189)
        case .logoOutOExt: return CGSize(width: 57.379, height: 63.4189)
        case .logoOutOFace: return CGSize(width: 57.379, height: 63.4189)
        case .logoOutT: return CGSize(width: 52.3457, height: 63.4189)
        case .logoOutTExt: return CGSize(width: 52.3457, height: 63.4189)
        case .logoOutTFace: return CGSize(width: 52.3457, height: 63.4189)
        case .logoOutU: return CGSize(width: 51.3391, height: 63.4189)
        case .logoOutUExt: return CGSize(width: 51.3391, height: 63.4189)
        case .logoOutUFace: return CGSize(width: 51.3391, height: 63.4189)
        case .logoPegs: return CGSize(width: 112.745, height: 24.1596)
        case .logoSignBlue: return CGSize(width: 283.244, height: 133.737)
        case .logoSignPurple: return CGSize(width: 234.214, height: 134.22)
        case .logoSignPurpleBend100: return CGSize(width: 234.214, height: 134.22)
        case .logoSignPurpleBend25: return CGSize(width: 234.214, height: 134.22)
        case .logoSignPurpleBend50: return CGSize(width: 234.214, height: 134.22)
        case .logoSignPurpleBend75: return CGSize(width: 234.214, height: 134.22)
        case .navCart: return CGSize(width: 62, height: 62)
        case .navCup: return CGSize(width: 68, height: 62)
        case .navLodge: return CGSize(width: 80, height: 86)
        case .padlockGold: return CGSize(width: 44, height: 54)
        case .pageBgPattern: return CGSize(width: 145, height: 79)
        case .pipeCounter: return CGSize(width: 68, height: 53)
        case .pipeMouth: return CGSize(width: 47, height: 30)
        case .pipeShards: return CGSize(width: 48, height: 48)
        case .planetStage1: return CGSize(width: 60, height: 60)
        case .planetStage2: return CGSize(width: 60, height: 60)
        case .planetStage3: return CGSize(width: 104, height: 60)
        case .pointerArrowDown: return CGSize(width: 78, height: 104)
        case .pointerArrowYellow: return CGSize(width: 46, height: 50)
        case .rallyBackdrop: return CGSize(width: 393, height: 852)
        case .rallyOfferScene: return CGSize(width: 330, height: 504)
        case .rallyRocketMine: return CGSize(width: 68, height: 98)
        case .rallyRocketOther: return CGSize(width: 68, height: 98)
        case .rankBadgeBronze: return CGSize(width: 40, height: 40)
        case .rankBadgeGold: return CGSize(width: 40, height: 40)
        case .rankBadgeSilver: return CGSize(width: 40, height: 40)
        case .rankWings1: return CGSize(width: 52, height: 38)
        case .scoreChip: return CGSize(width: 40, height: 44)
        case .shopSeal: return CGSize(width: 66, height: 66)
        case .sparkleTwinkle: return CGSize(width: 16, height: 16)
        case .stageChestBlue: return CGSize(width: 56, height: 42)
        case .stageChestGreen: return CGSize(width: 56, height: 42)
        case .stageChestPink: return CGSize(width: 56, height: 42)
        case .statFirstTryIcon: return CGSize(width: 56, height: 54)
        case .statWeeklyWinsIcon: return CGSize(width: 48, height: 51)
        case .stopwatchBig: return CGSize(width: 225, height: 225)
        case .streakHeader: return CGSize(width: 393, height: 290)
        case .sunburstRays: return CGSize(width: 190, height: 86)
        case .tapeH2: return CGSize(width: 54, height: 39)
        case .tapeH3: return CGSize(width: 86, height: 39)
        case .tapeH4: return CGSize(width: 118, height: 39)
        case .tapeV2: return CGSize(width: 39, height: 54)
        case .tapeV3: return CGSize(width: 39, height: 86)
        case .tapeV4: return CGSize(width: 39, height: 118)
        case .treasureHeader: return CGSize(width: 393, height: 240)
        case .treasureToken: return CGSize(width: 40, height: 40)
        case .tutorialHand: return CGSize(width: 102, height: 136)
        case .unlockIconBox: return CGSize(width: 132, height: 134)
        case .unlockIconCorner: return CGSize(width: 100, height: 100)
        case .unlockIconDoor: return CGSize(width: 128, height: 128)
        case .unlockIconElevator: return CGSize(width: 164, height: 112)
        case .unlockIconLinked: return CGSize(width: 150, height: 106)
        case .unlockIconPipe: return CGSize(width: 156, height: 124)
        }
    }

    /// The manifest group (placeholder tint, preload sets).
    var group: String {
        switch self {
        case .avatarBoss: return "avatars"
        case .avatarConfetti: return "avatars"
        case .avatarDefault: return "avatars"
        case .avatarLunch: return "avatars"
        case .avatarMapper: return "avatars"
        case .avatarMiner: return "avatars"
        case .avatarSleepy: return "avatars"
        case .avatarSleuth: return "avatars"
        case .avatarStrong: return "avatars"
        case .badgeCloudHop: return "home"
        case .badgeHotStreak: return "home"
        case .badgeRocketRally: return "home"
        case .balloonCloudA: return "events-balloon"
        case .balloonCloudB: return "events-balloon"
        case .balloonHero: return "events-balloon"
        case .balloonLedge: return "events-balloon"
        case .balloonTowerFoot: return "events-balloon"
        case .balloonTowerShaft: return "events-balloon"
        case .balloonTowerTop: return "events-balloon"
        case .boardTrailStar: return "board"
        case .boosterFreeze: return "boosters"
        case .boosterHint: return "boosters"
        case .bossLoading: return "characters"
        case .boxRing: return "board"
        case .boxSlab: return "board"
        case .bundleBag: return "profile-shop-settings"
        case .bundleBarrel: return "profile-shop-settings"
        case .bundleCart: return "profile-shop-settings"
        case .bundleChest: return "profile-shop-settings"
        case .bundleSafe: return "profile-shop-settings"
        case .bundleSpecial: return "profile-shop-settings"
        case .coinBowl: return "events-streak"
        case .coinPackBig: return "profile-shop-settings"
        case .coinPackGiant: return "profile-shop-settings"
        case .coinPackMedium: return "profile-shop-settings"
        case .coinPackSmall: return "profile-shop-settings"
        case .coinPackSuper: return "profile-shop-settings"
        case .coinPackTiny: return "profile-shop-settings"
        case .coinPileSmall: return "events-claw"
        case .coinStackReward: return "popups"
        case .cornerDownLeftPlate: return "board"
        case .cornerDownLeftSpring: return "board"
        case .cornerDownRightPlate: return "board"
        case .cornerDownRightSpring: return "board"
        case .cornerUpLeftPlate: return "board"
        case .cornerUpLeftSpring: return "board"
        case .cornerUpRightPlate: return "board"
        case .cornerUpRightSpring: return "board"
        case .cornerWedge: return "board"
        case .cupPodium: return "leaderboard"
        case .digCart: return "characters"
        case .digDockL: return "characters"
        case .digFlyer: return "characters"
        case .digPop1: return "characters"
        case .digPop2: return "characters"
        case .doorShards: return "board"
        case .doorW11H10: return "board"
        case .doorW13H4: return "board"
        case .doorW22H10: return "board"
        case .doorW4H12: return "board"
        case .doorW4H16: return "board"
        case .doorW4H20: return "board"
        case .doorW4H4: return "board"
        case .doorW4H8: return "board"
        case .doorW5H17: return "board"
        case .eventBadgeBalloon: return "home"
        case .fxFrostVignette: return "fx"
        case .glyphBell: return "profile-shop-settings"
        case .glyphGear: return "home"
        case .glyphHaptic: return "popups"
        case .glyphHapticWhite: return "profile-shop-settings"
        case .glyphMusic: return "profile-shop-settings"
        case .glyphOffSlash: return "profile-shop-settings"
        case .glyphSound: return "popups"
        case .glyphSoundWhite: return "profile-shop-settings"
        case .heartBig: return "popups"
        case .heartBroken: return "popups"
        case .heartGlossySmall: return "popups"
        case .heartHUD: return "hud"
        case .heartHUDHalves: return "fx"
        case .heartHUDLost: return "hud"
        case .heartInfinite: return "popups"
        case .heartInfiniteSmall: return "popups"
        case .heartLives: return "home"
        case .heartLivesBig: return "popups"
        case .homeCabinet: return "home"
        case .homeFloor: return "home"
        case .homeScaffold: return "home"
        case .homeSignpost: return "home"
        case .homeWorkshop: return "home"
        case .hopBackdrop: return "events-skyjump"
        case .hopDrum: return "profile-shop-settings"
        case .hopIsland: return "events-skyjump"
        case .hopIslandFar: return "events-skyjump"
        case .hopIslandFar2: return "events-skyjump"
        case .hopOfferScene: return "events-skyjump"
        case .hopPad: return "events-skyjump"
        case .iconCheck: return "events-claw"
        case .iconCheckBadge: return "profile-shop-settings"
        case .iconCheckeredFlag: return "events-streak"
        case .iconCoin: return "hud"
        case .iconPencil: return "profile-shop-settings"
        case .iconPlusGreen: return "hud"
        case .iconSkull: return "loading-win"
        case .iconSkullBones: return "loading-win"
        case .iconStopwatch: return "hud"
        case .iconStopwatchFrozen: return "hud"
        case .iconStopwatchSmall: return "hud"
        case .infoPathIcon: return "popups"
        case .keyOnArrow: return "board"
        case .loadingBackdrop: return "loading-win"
        case .lockHex: return "board"
        case .logoArrowOut: return "loading-win"
        case .logoLetterA: return "logo"
        case .logoLetterAExt: return "logo"
        case .logoLetterAFace: return "logo"
        case .logoLetterAFlat: return "logo"
        case .logoLetterO: return "logo"
        case .logoLetterOExt: return "logo"
        case .logoLetterOFace: return "logo"
        case .logoLetterOFlat: return "logo"
        case .logoLetterR1: return "logo"
        case .logoLetterR1Ext: return "logo"
        case .logoLetterR1Face: return "logo"
        case .logoLetterR1Flat: return "logo"
        case .logoLetterR2: return "logo"
        case .logoLetterR2Ext: return "logo"
        case .logoLetterR2Face: return "logo"
        case .logoLetterR2Flat: return "logo"
        case .logoLetterW: return "logo"
        case .logoLetterWExt: return "logo"
        case .logoLetterWFace: return "logo"
        case .logoLetterWFlat: return "logo"
        case .logoOut: return "logo"
        case .logoOutBang: return "logo"
        case .logoOutBangExt: return "logo"
        case .logoOutBangFace: return "logo"
        case .logoOutO: return "logo"
        case .logoOutOExt: return "logo"
        case .logoOutOFace: return "logo"
        case .logoOutT: return "logo"
        case .logoOutTExt: return "logo"
        case .logoOutTFace: return "logo"
        case .logoOutU: return "logo"
        case .logoOutUExt: return "logo"
        case .logoOutUFace: return "logo"
        case .logoPegs: return "logo"
        case .logoSignBlue: return "logo"
        case .logoSignPurple: return "logo"
        case .logoSignPurpleBend100: return "logo"
        case .logoSignPurpleBend25: return "logo"
        case .logoSignPurpleBend50: return "logo"
        case .logoSignPurpleBend75: return "logo"
        case .navCart: return "home"
        case .navCup: return "home"
        case .navLodge: return "home"
        case .padlockGold: return "events-claw"
        case .pageBgPattern: return "profile-shop-settings"
        case .pipeCounter: return "board"
        case .pipeMouth: return "board"
        case .pipeShards: return "board"
        case .planetStage1: return "events-rocket"
        case .planetStage2: return "events-rocket"
        case .planetStage3: return "events-rocket"
        case .pointerArrowDown: return "popups"
        case .pointerArrowYellow: return "popups"
        case .rallyBackdrop: return "events-rocket"
        case .rallyOfferScene: return "events-rocket"
        case .rallyRocketMine: return "events-rocket"
        case .rallyRocketOther: return "events-rocket"
        case .rankBadgeBronze: return "events-streak"
        case .rankBadgeGold: return "events-streak"
        case .rankBadgeSilver: return "events-streak"
        case .rankWings1: return "events-rocket"
        case .scoreChip: return "events-streak"
        case .shopSeal: return "profile-shop-settings"
        case .sparkleTwinkle: return "fx"
        case .stageChestBlue: return "events-skyjump"
        case .stageChestGreen: return "events-skyjump"
        case .stageChestPink: return "events-skyjump"
        case .statFirstTryIcon: return "profile-shop-settings"
        case .statWeeklyWinsIcon: return "profile-shop-settings"
        case .stopwatchBig: return "popups"
        case .streakHeader: return "events-streak"
        case .sunburstRays: return "events-claw"
        case .tapeH2: return "board"
        case .tapeH3: return "board"
        case .tapeH4: return "board"
        case .tapeV2: return "board"
        case .tapeV3: return "board"
        case .tapeV4: return "board"
        case .treasureHeader: return "events-claw"
        case .treasureToken: return "home"
        case .tutorialHand: return "popups"
        case .unlockIconBox: return "popups"
        case .unlockIconCorner: return "popups"
        case .unlockIconDoor: return "popups"
        case .unlockIconElevator: return "popups"
        case .unlockIconLinked: return "popups"
        case .unlockIconPipe: return "popups"
        }
    }
}
