import CoreGraphics

// GENERATED by tools/skin/art.py from skin/art.json (slot -> art/MANIFEST.json id) and art/MANIFEST.json (file, size,
// group). Do not edit: edit skin/art.json, then run python3 tools/skin/art.py (docs/SKIN.md §4).
// 200 art slots (200 files), 8 rig slots. Loader + placeholder: ArtStore.swift.

/// An art SLOT: what a raster is for (`home.backdrop`, `currency.coin.icon`, `avatar.3` …). The raw value is the slot
/// id of skin/art.json; the file that fills it is the skin's (`path`), so no Swift names a file.
enum UIArt: String, CaseIterable, Sendable {
    case avatar0 = "avatar.0"
    case avatar1 = "avatar.1"
    case avatar2 = "avatar.2"
    case avatar3 = "avatar.3"
    case avatar4 = "avatar.4"
    case avatar5 = "avatar.5"
    case avatar6 = "avatar.6"
    case avatar7 = "avatar.7"
    case avatar8 = "avatar.8"
    case boosterFreezeIcon = "booster.freeze.icon"
    case boosterHintIcon = "booster.hint.icon"
    case currencyCoinIcon = "currency.coin.icon"
    case eventBalloonRiseBadge = "event.balloonRise.badge"
    case eventBalloonRiseCloudA = "event.balloonRise.cloudA"
    case eventBalloonRiseCloudB = "event.balloonRise.cloudB"
    case eventBalloonRiseHero = "event.balloonRise.hero"
    case eventBalloonRiseLedge = "event.balloonRise.ledge"
    case eventBalloonRiseTowerFoot = "event.balloonRise.towerFoot"
    case eventBalloonRiseTowerShaft = "event.balloonRise.towerShaft"
    case eventBalloonRiseTowerTop = "event.balloonRise.towerTop"
    case eventClawChallengeHeader = "event.clawChallenge.header"
    case eventClawChallengeToken = "event.clawChallenge.token"
    case eventRocketRaceBackdrop = "event.rocketRace.backdrop"
    case eventRocketRaceBadge = "event.rocketRace.badge"
    case eventRocketRaceOffer = "event.rocketRace.offer"
    case eventRocketRaceRacerMine = "event.rocketRace.racerMine"
    case eventRocketRaceRacerOther = "event.rocketRace.racerOther"
    case eventRocketRaceStage1 = "event.rocketRace.stage1"
    case eventRocketRaceStage2 = "event.rocketRace.stage2"
    case eventRocketRaceStage3 = "event.rocketRace.stage3"
    case eventSkyJumpBackdrop = "event.skyJump.backdrop"
    case eventSkyJumpBadge = "event.skyJump.badge"
    case eventSkyJumpIcon = "event.skyJump.icon"
    case eventSkyJumpOffer = "event.skyJump.offer"
    case eventSkyJumpPad = "event.skyJump.pad"
    case eventSkyJumpPlatform = "event.skyJump.platform"
    case eventSkyJumpPlatformFar = "event.skyJump.platformFar"
    case eventSkyJumpPlatformFar2 = "event.skyJump.platformFar2"
    case eventStreakRaceBadge = "event.streakRace.badge"
    case eventStreakRaceHeader = "event.streakRace.header"
    case fxFrostVignette = "fx.frostVignette"
    case fxSparkle = "fx.sparkle"
    case fxSunburst = "fx.sunburst"
    case homeBackdrop = "home.backdrop"
    case homeCentrepiece = "home.centrepiece"
    case homeFloor = "home.floor"
    case homeStand = "home.stand"
    case homeStation = "home.station"
    case hudHeartFull = "hud.heart.full"
    case hudHeartHalves = "hud.heart.halves"
    case hudHeartLost = "hud.heart.lost"
    case hudPlusBadge = "hud.plusBadge"
    case hudTimerIcon = "hud.timer.icon"
    case hudTimerIconFrozen = "hud.timer.iconFrozen"
    case hudTimerIconSmall = "hud.timer.iconSmall"
    case iconBell = "icon.bell"
    case iconCheck = "icon.check"
    case iconCheckBadge = "icon.checkBadge"
    case iconFinishFlag = "icon.finishFlag"
    case iconHaptic = "icon.haptic"
    case iconHapticLight = "icon.hapticLight"
    case iconInfo = "icon.info"
    case iconLock = "icon.lock"
    case iconMusic = "icon.music"
    case iconOffSlash = "icon.offSlash"
    case iconPencil = "icon.pencil"
    case iconPointer = "icon.pointer"
    case iconPointerDown = "icon.pointerDown"
    case iconSettings = "icon.settings"
    case iconSkull = "icon.skull"
    case iconSkullBones = "icon.skullBones"
    case iconSound = "icon.sound"
    case iconSoundLight = "icon.soundLight"
    case leaderboardPodium = "leaderboard.podium"
    case livesHeart = "lives.heart"
    case livesHeartBig = "lives.heartBig"
    case livesHeartGlossySmall = "lives.heartGlossySmall"
    case livesLost = "lives.lost"
    case livesUnlimited = "lives.unlimited"
    case livesUnlimitedSmall = "lives.unlimitedSmall"
    case loadingBackdrop = "loading.backdrop"
    case loadingCast1 = "loading.cast.1"
    case loadingCast2 = "loading.cast.2"
    case loadingCast3 = "loading.cast.3"
    case loadingCast4 = "loading.cast.4"
    case loadingCast5 = "loading.cast.5"
    case loadingCast6 = "loading.cast.6"
    case logoMain = "logo.main"
    case logoPartLogoLetterA = "logo.part.logoLetterA"
    case logoPartLogoLetterAExt = "logo.part.logoLetterAExt"
    case logoPartLogoLetterAFace = "logo.part.logoLetterAFace"
    case logoPartLogoLetterAFlat = "logo.part.logoLetterAFlat"
    case logoPartLogoLetterO = "logo.part.logoLetterO"
    case logoPartLogoLetterOExt = "logo.part.logoLetterOExt"
    case logoPartLogoLetterOFace = "logo.part.logoLetterOFace"
    case logoPartLogoLetterOFlat = "logo.part.logoLetterOFlat"
    case logoPartLogoLetterR1 = "logo.part.logoLetterR1"
    case logoPartLogoLetterR1Ext = "logo.part.logoLetterR1Ext"
    case logoPartLogoLetterR1Face = "logo.part.logoLetterR1Face"
    case logoPartLogoLetterR1Flat = "logo.part.logoLetterR1Flat"
    case logoPartLogoLetterR2 = "logo.part.logoLetterR2"
    case logoPartLogoLetterR2Ext = "logo.part.logoLetterR2Ext"
    case logoPartLogoLetterR2Face = "logo.part.logoLetterR2Face"
    case logoPartLogoLetterR2Flat = "logo.part.logoLetterR2Flat"
    case logoPartLogoLetterW = "logo.part.logoLetterW"
    case logoPartLogoLetterWExt = "logo.part.logoLetterWExt"
    case logoPartLogoLetterWFace = "logo.part.logoLetterWFace"
    case logoPartLogoLetterWFlat = "logo.part.logoLetterWFlat"
    case logoPartLogoOut = "logo.part.logoOut"
    case logoPartLogoOutBang = "logo.part.logoOutBang"
    case logoPartLogoOutBangExt = "logo.part.logoOutBangExt"
    case logoPartLogoOutBangFace = "logo.part.logoOutBangFace"
    case logoPartLogoOutO = "logo.part.logoOutO"
    case logoPartLogoOutOExt = "logo.part.logoOutOExt"
    case logoPartLogoOutOFace = "logo.part.logoOutOFace"
    case logoPartLogoOutT = "logo.part.logoOutT"
    case logoPartLogoOutTExt = "logo.part.logoOutTExt"
    case logoPartLogoOutTFace = "logo.part.logoOutTFace"
    case logoPartLogoOutU = "logo.part.logoOutU"
    case logoPartLogoOutUExt = "logo.part.logoOutUExt"
    case logoPartLogoOutUFace = "logo.part.logoOutUFace"
    case logoPartLogoPegs = "logo.part.logoPegs"
    case logoPartLogoSignBlue = "logo.part.logoSignBlue"
    case logoPartLogoSignPurple = "logo.part.logoSignPurple"
    case logoPartLogoSignPurpleBend100 = "logo.part.logoSignPurpleBend100"
    case logoPartLogoSignPurpleBend25 = "logo.part.logoSignPurpleBend25"
    case logoPartLogoSignPurpleBend50 = "logo.part.logoSignPurpleBend50"
    case logoPartLogoSignPurpleBend75 = "logo.part.logoSignPurpleBend75"
    case navHomeIcon = "nav.home.icon"
    case navLeaderboardIcon = "nav.leaderboard.icon"
    case navShopIcon = "nav.shop.icon"
    case pagePattern = "page.pattern"
    case popupOutOfTimeHeart = "popup.outOfTime.heart"
    case popupOutOfTimeStopwatch = "popup.outOfTime.stopwatch"
    case profileStatFirstTry = "profile.stat.firstTry"
    case profileStatWeeklyWins = "profile.stat.weeklyWins"
    case puzzleBoardTrailStar = "puzzle.boardTrailStar"
    case puzzleBoxRing = "puzzle.boxRing"
    case puzzleBoxSlab = "puzzle.boxSlab"
    case puzzleCornerDownLeftPlate = "puzzle.cornerDownLeftPlate"
    case puzzleCornerDownLeftSpring = "puzzle.cornerDownLeftSpring"
    case puzzleCornerDownRightPlate = "puzzle.cornerDownRightPlate"
    case puzzleCornerDownRightSpring = "puzzle.cornerDownRightSpring"
    case puzzleCornerUpLeftPlate = "puzzle.cornerUpLeftPlate"
    case puzzleCornerUpLeftSpring = "puzzle.cornerUpLeftSpring"
    case puzzleCornerUpRightPlate = "puzzle.cornerUpRightPlate"
    case puzzleCornerUpRightSpring = "puzzle.cornerUpRightSpring"
    case puzzleCornerWedge = "puzzle.cornerWedge"
    case puzzleDoorShards = "puzzle.doorShards"
    case puzzleDoorW11H10 = "puzzle.doorW11H10"
    case puzzleDoorW13H4 = "puzzle.doorW13H4"
    case puzzleDoorW22H10 = "puzzle.doorW22H10"
    case puzzleDoorW4H12 = "puzzle.doorW4H12"
    case puzzleDoorW4H16 = "puzzle.doorW4H16"
    case puzzleDoorW4H20 = "puzzle.doorW4H20"
    case puzzleDoorW4H4 = "puzzle.doorW4H4"
    case puzzleDoorW4H8 = "puzzle.doorW4H8"
    case puzzleDoorW5H17 = "puzzle.doorW5H17"
    case puzzleKeyOnArrow = "puzzle.keyOnArrow"
    case puzzleLockHex = "puzzle.lockHex"
    case puzzlePipeCounter = "puzzle.pipeCounter"
    case puzzlePipeMouth = "puzzle.pipeMouth"
    case puzzlePipeShards = "puzzle.pipeShards"
    case puzzleTapeH2 = "puzzle.tapeH2"
    case puzzleTapeH3 = "puzzle.tapeH3"
    case puzzleTapeH4 = "puzzle.tapeH4"
    case puzzleTapeV2 = "puzzle.tapeV2"
    case puzzleTapeV3 = "puzzle.tapeV3"
    case puzzleTapeV4 = "puzzle.tapeV4"
    case rank1Badge = "rank.1.badge"
    case rank1Wings = "rank.1.wings"
    case rank2Badge = "rank.2.badge"
    case rank3Badge = "rank.3.badge"
    case rewardChest1 = "reward.chest.1"
    case rewardChest2 = "reward.chest.2"
    case rewardChest3 = "reward.chest.3"
    case rewardCoinBowl = "reward.coinBowl"
    case rewardCoins = "reward.coins"
    case rewardCoinsSmall = "reward.coinsSmall"
    case shopBundleElite = "shop.bundle.elite"
    case shopBundleEpic = "shop.bundle.epic"
    case shopBundleLegendary = "shop.bundle.legendary"
    case shopBundleMega = "shop.bundle.mega"
    case shopBundleMini = "shop.bundle.mini"
    case shopBundleSpecial = "shop.bundle.special"
    case shopCoins1 = "shop.coins.1"
    case shopCoins2 = "shop.coins.2"
    case shopCoins3 = "shop.coins.3"
    case shopCoins4 = "shop.coins.4"
    case shopCoins5 = "shop.coins.5"
    case shopCoins6 = "shop.coins.6"
    case shopSeal = "shop.seal"
    case socialScoreChip = "social.scoreChip"
    case tutorialHand = "tutorial.hand"
    case unlockBoxIcon = "unlock.box.icon"
    case unlockCornerIcon = "unlock.corner.icon"
    case unlockDoorIcon = "unlock.door.icon"
    case unlockElevatorIcon = "unlock.elevator.icon"
    case unlockLinkedIcon = "unlock.linked.icon"
    case unlockPipeIcon = "unlock.pipe.icon"

    /// The art/MANIFEST.json id of the file the skin maps this slot to.
    var asset: String {
        switch self {
        case .avatar0: return "avatarDefault"
        case .avatar1: return "avatarMiner"
        case .avatar2: return "avatarMapper"
        case .avatar3: return "avatarSleuth"
        case .avatar4: return "avatarLunch"
        case .avatar5: return "avatarBoss"
        case .avatar6: return "avatarConfetti"
        case .avatar7: return "avatarSleepy"
        case .avatar8: return "avatarStrong"
        case .boosterFreezeIcon: return "boosterFreeze"
        case .boosterHintIcon: return "boosterHint"
        case .currencyCoinIcon: return "iconCoin"
        case .eventBalloonRiseBadge: return "eventBadgeBalloon"
        case .eventBalloonRiseCloudA: return "balloonCloudA"
        case .eventBalloonRiseCloudB: return "balloonCloudB"
        case .eventBalloonRiseHero: return "balloonHero"
        case .eventBalloonRiseLedge: return "balloonLedge"
        case .eventBalloonRiseTowerFoot: return "balloonTowerFoot"
        case .eventBalloonRiseTowerShaft: return "balloonTowerShaft"
        case .eventBalloonRiseTowerTop: return "balloonTowerTop"
        case .eventClawChallengeHeader: return "treasureHeader"
        case .eventClawChallengeToken: return "treasureToken"
        case .eventRocketRaceBackdrop: return "rallyBackdrop"
        case .eventRocketRaceBadge: return "badgeRocketRally"
        case .eventRocketRaceOffer: return "rallyOfferScene"
        case .eventRocketRaceRacerMine: return "rallyRocketMine"
        case .eventRocketRaceRacerOther: return "rallyRocketOther"
        case .eventRocketRaceStage1: return "planetStage1"
        case .eventRocketRaceStage2: return "planetStage2"
        case .eventRocketRaceStage3: return "planetStage3"
        case .eventSkyJumpBackdrop: return "hopBackdrop"
        case .eventSkyJumpBadge: return "badgeCloudHop"
        case .eventSkyJumpIcon: return "hopDrum"
        case .eventSkyJumpOffer: return "hopOfferScene"
        case .eventSkyJumpPad: return "hopPad"
        case .eventSkyJumpPlatform: return "hopIsland"
        case .eventSkyJumpPlatformFar: return "hopIslandFar"
        case .eventSkyJumpPlatformFar2: return "hopIslandFar2"
        case .eventStreakRaceBadge: return "badgeHotStreak"
        case .eventStreakRaceHeader: return "streakHeader"
        case .fxFrostVignette: return "fxFrostVignette"
        case .fxSparkle: return "sparkleTwinkle"
        case .fxSunburst: return "sunburstRays"
        case .homeBackdrop: return "homeWorkshop"
        case .homeCentrepiece: return "homeSignpost"
        case .homeFloor: return "homeFloor"
        case .homeStand: return "homeCabinet"
        case .homeStation: return "homeScaffold"
        case .hudHeartFull: return "heartHUD"
        case .hudHeartHalves: return "heartHUDHalves"
        case .hudHeartLost: return "heartHUDLost"
        case .hudPlusBadge: return "iconPlusGreen"
        case .hudTimerIcon: return "iconStopwatch"
        case .hudTimerIconFrozen: return "iconStopwatchFrozen"
        case .hudTimerIconSmall: return "iconStopwatchSmall"
        case .iconBell: return "glyphBell"
        case .iconCheck: return "iconCheck"
        case .iconCheckBadge: return "iconCheckBadge"
        case .iconFinishFlag: return "iconCheckeredFlag"
        case .iconHaptic: return "glyphHaptic"
        case .iconHapticLight: return "glyphHapticWhite"
        case .iconInfo: return "infoPathIcon"
        case .iconLock: return "padlockGold"
        case .iconMusic: return "glyphMusic"
        case .iconOffSlash: return "glyphOffSlash"
        case .iconPencil: return "iconPencil"
        case .iconPointer: return "pointerArrowYellow"
        case .iconPointerDown: return "pointerArrowDown"
        case .iconSettings: return "glyphGear"
        case .iconSkull: return "iconSkull"
        case .iconSkullBones: return "iconSkullBones"
        case .iconSound: return "glyphSound"
        case .iconSoundLight: return "glyphSoundWhite"
        case .leaderboardPodium: return "cupPodium"
        case .livesHeart: return "heartLives"
        case .livesHeartBig: return "heartLivesBig"
        case .livesHeartGlossySmall: return "heartGlossySmall"
        case .livesLost: return "heartBroken"
        case .livesUnlimited: return "heartInfinite"
        case .livesUnlimitedSmall: return "heartInfiniteSmall"
        case .loadingBackdrop: return "loadingBackdrop"
        case .loadingCast1: return "digDockL"
        case .loadingCast2: return "digPop1"
        case .loadingCast3: return "bossLoading"
        case .loadingCast4: return "digPop2"
        case .loadingCast5: return "digFlyer"
        case .loadingCast6: return "digCart"
        case .logoMain: return "logoArrowOut"
        case .logoPartLogoLetterA: return "logoLetterA"
        case .logoPartLogoLetterAExt: return "logoLetterAExt"
        case .logoPartLogoLetterAFace: return "logoLetterAFace"
        case .logoPartLogoLetterAFlat: return "logoLetterAFlat"
        case .logoPartLogoLetterO: return "logoLetterO"
        case .logoPartLogoLetterOExt: return "logoLetterOExt"
        case .logoPartLogoLetterOFace: return "logoLetterOFace"
        case .logoPartLogoLetterOFlat: return "logoLetterOFlat"
        case .logoPartLogoLetterR1: return "logoLetterR1"
        case .logoPartLogoLetterR1Ext: return "logoLetterR1Ext"
        case .logoPartLogoLetterR1Face: return "logoLetterR1Face"
        case .logoPartLogoLetterR1Flat: return "logoLetterR1Flat"
        case .logoPartLogoLetterR2: return "logoLetterR2"
        case .logoPartLogoLetterR2Ext: return "logoLetterR2Ext"
        case .logoPartLogoLetterR2Face: return "logoLetterR2Face"
        case .logoPartLogoLetterR2Flat: return "logoLetterR2Flat"
        case .logoPartLogoLetterW: return "logoLetterW"
        case .logoPartLogoLetterWExt: return "logoLetterWExt"
        case .logoPartLogoLetterWFace: return "logoLetterWFace"
        case .logoPartLogoLetterWFlat: return "logoLetterWFlat"
        case .logoPartLogoOut: return "logoOut"
        case .logoPartLogoOutBang: return "logoOutBang"
        case .logoPartLogoOutBangExt: return "logoOutBangExt"
        case .logoPartLogoOutBangFace: return "logoOutBangFace"
        case .logoPartLogoOutO: return "logoOutO"
        case .logoPartLogoOutOExt: return "logoOutOExt"
        case .logoPartLogoOutOFace: return "logoOutOFace"
        case .logoPartLogoOutT: return "logoOutT"
        case .logoPartLogoOutTExt: return "logoOutTExt"
        case .logoPartLogoOutTFace: return "logoOutTFace"
        case .logoPartLogoOutU: return "logoOutU"
        case .logoPartLogoOutUExt: return "logoOutUExt"
        case .logoPartLogoOutUFace: return "logoOutUFace"
        case .logoPartLogoPegs: return "logoPegs"
        case .logoPartLogoSignBlue: return "logoSignBlue"
        case .logoPartLogoSignPurple: return "logoSignPurple"
        case .logoPartLogoSignPurpleBend100: return "logoSignPurpleBend100"
        case .logoPartLogoSignPurpleBend25: return "logoSignPurpleBend25"
        case .logoPartLogoSignPurpleBend50: return "logoSignPurpleBend50"
        case .logoPartLogoSignPurpleBend75: return "logoSignPurpleBend75"
        case .navHomeIcon: return "navLodge"
        case .navLeaderboardIcon: return "navCup"
        case .navShopIcon: return "navCart"
        case .pagePattern: return "pageBgPattern"
        case .popupOutOfTimeHeart: return "heartBig"
        case .popupOutOfTimeStopwatch: return "stopwatchBig"
        case .profileStatFirstTry: return "statFirstTryIcon"
        case .profileStatWeeklyWins: return "statWeeklyWinsIcon"
        case .puzzleBoardTrailStar: return "boardTrailStar"
        case .puzzleBoxRing: return "boxRing"
        case .puzzleBoxSlab: return "boxSlab"
        case .puzzleCornerDownLeftPlate: return "cornerDownLeftPlate"
        case .puzzleCornerDownLeftSpring: return "cornerDownLeftSpring"
        case .puzzleCornerDownRightPlate: return "cornerDownRightPlate"
        case .puzzleCornerDownRightSpring: return "cornerDownRightSpring"
        case .puzzleCornerUpLeftPlate: return "cornerUpLeftPlate"
        case .puzzleCornerUpLeftSpring: return "cornerUpLeftSpring"
        case .puzzleCornerUpRightPlate: return "cornerUpRightPlate"
        case .puzzleCornerUpRightSpring: return "cornerUpRightSpring"
        case .puzzleCornerWedge: return "cornerWedge"
        case .puzzleDoorShards: return "doorShards"
        case .puzzleDoorW11H10: return "doorW11H10"
        case .puzzleDoorW13H4: return "doorW13H4"
        case .puzzleDoorW22H10: return "doorW22H10"
        case .puzzleDoorW4H12: return "doorW4H12"
        case .puzzleDoorW4H16: return "doorW4H16"
        case .puzzleDoorW4H20: return "doorW4H20"
        case .puzzleDoorW4H4: return "doorW4H4"
        case .puzzleDoorW4H8: return "doorW4H8"
        case .puzzleDoorW5H17: return "doorW5H17"
        case .puzzleKeyOnArrow: return "keyOnArrow"
        case .puzzleLockHex: return "lockHex"
        case .puzzlePipeCounter: return "pipeCounter"
        case .puzzlePipeMouth: return "pipeMouth"
        case .puzzlePipeShards: return "pipeShards"
        case .puzzleTapeH2: return "tapeH2"
        case .puzzleTapeH3: return "tapeH3"
        case .puzzleTapeH4: return "tapeH4"
        case .puzzleTapeV2: return "tapeV2"
        case .puzzleTapeV3: return "tapeV3"
        case .puzzleTapeV4: return "tapeV4"
        case .rank1Badge: return "rankBadgeGold"
        case .rank1Wings: return "rankWings1"
        case .rank2Badge: return "rankBadgeSilver"
        case .rank3Badge: return "rankBadgeBronze"
        case .rewardChest1: return "stageChestGreen"
        case .rewardChest2: return "stageChestBlue"
        case .rewardChest3: return "stageChestPink"
        case .rewardCoinBowl: return "coinBowl"
        case .rewardCoins: return "coinStackReward"
        case .rewardCoinsSmall: return "coinPileSmall"
        case .shopBundleElite: return "bundleChest"
        case .shopBundleEpic: return "bundleBarrel"
        case .shopBundleLegendary: return "bundleCart"
        case .shopBundleMega: return "bundleSafe"
        case .shopBundleMini: return "bundleBag"
        case .shopBundleSpecial: return "bundleSpecial"
        case .shopCoins1: return "coinPackTiny"
        case .shopCoins2: return "coinPackSmall"
        case .shopCoins3: return "coinPackMedium"
        case .shopCoins4: return "coinPackBig"
        case .shopCoins5: return "coinPackSuper"
        case .shopCoins6: return "coinPackGiant"
        case .shopSeal: return "shopSeal"
        case .socialScoreChip: return "scoreChip"
        case .tutorialHand: return "tutorialHand"
        case .unlockBoxIcon: return "unlockIconBox"
        case .unlockCornerIcon: return "unlockIconCorner"
        case .unlockDoorIcon: return "unlockIconDoor"
        case .unlockElevatorIcon: return "unlockIconElevator"
        case .unlockLinkedIcon: return "unlockIconLinked"
        case .unlockPipeIcon: return "unlockIconPipe"
        }
    }

    /// The file inside the app bundle (tools/sync_art.sh: art/ui/out -> UI/, art/out -> Art/).
    var path: String {
        switch self {
        case .avatar0: return "UI/avatarDefault@3x.png"
        case .avatar1: return "Art/char_avatarMiner@3x.png"
        case .avatar2: return "Art/char_avatarMapper@3x.png"
        case .avatar3: return "Art/char_avatarSleuth@3x.png"
        case .avatar4: return "Art/char_avatarLunch@3x.png"
        case .avatar5: return "Art/char_avatarBoss@3x.png"
        case .avatar6: return "Art/char_avatarConfetti@3x.png"
        case .avatar7: return "Art/char_avatarSleepy@3x.png"
        case .avatar8: return "Art/char_avatarStrong@3x.png"
        case .boosterFreezeIcon: return "UI/boosterFreeze@3x.png"
        case .boosterHintIcon: return "UI/boosterHint@3x.png"
        case .currencyCoinIcon: return "UI/iconCoin@3x.png"
        case .eventBalloonRiseBadge: return "Art/eventBadgeBalloon@3x.png"
        case .eventBalloonRiseCloudA: return "UI/balloonCloudA@3x.png"
        case .eventBalloonRiseCloudB: return "UI/balloonCloudB@3x.png"
        case .eventBalloonRiseHero: return "Art/balloonHero@3x.png"
        case .eventBalloonRiseLedge: return "UI/balloonLedge@3x.png"
        case .eventBalloonRiseTowerFoot: return "Art/balloonTowerFoot@3x.png"
        case .eventBalloonRiseTowerShaft: return "UI/balloonTowerShaft@3x.png"
        case .eventBalloonRiseTowerTop: return "Art/balloonTowerTop@3x.png"
        case .eventClawChallengeHeader: return "Art/treasureHeader@3x.png"
        case .eventClawChallengeToken: return "UI/treasureToken@3x.png"
        case .eventRocketRaceBackdrop: return "Art/rallyBackdrop@3x.png"
        case .eventRocketRaceBadge: return "Art/badgeRocketRally@3x.png"
        case .eventRocketRaceOffer: return "Art/rallyOfferScene@3x.png"
        case .eventRocketRaceRacerMine: return "UI/rallyRocketMine@3x.png"
        case .eventRocketRaceRacerOther: return "UI/rallyRocketOther@3x.png"
        case .eventRocketRaceStage1: return "UI/planetStage1@3x.png"
        case .eventRocketRaceStage2: return "UI/planetStage2@3x.png"
        case .eventRocketRaceStage3: return "UI/planetStage3@3x.png"
        case .eventSkyJumpBackdrop: return "Art/hopBackdrop@3x.png"
        case .eventSkyJumpBadge: return "Art/badgeCloudHop@3x.png"
        case .eventSkyJumpIcon: return "UI/hopDrum@3x.png"
        case .eventSkyJumpOffer: return "Art/hopOfferScene@3x.png"
        case .eventSkyJumpPad: return "Art/hopPad@3x.png"
        case .eventSkyJumpPlatform: return "Art/hopIsland@3x.png"
        case .eventSkyJumpPlatformFar: return "Art/hopIslandFar@3x.png"
        case .eventSkyJumpPlatformFar2: return "Art/hopIslandFar2@3x.png"
        case .eventStreakRaceBadge: return "Art/badgeHotStreak@3x.png"
        case .eventStreakRaceHeader: return "Art/streakHeader@3x.png"
        case .fxFrostVignette: return "UI/fxFrostVignette@3x.png"
        case .fxSparkle: return "UI/sparkleTwinkle@3x.png"
        case .fxSunburst: return "UI/sunburstRays@3x.png"
        case .homeBackdrop: return "Art/homeWorkshop@3x.png"
        case .homeCentrepiece: return "Art/homeSignpost@3x.png"
        case .homeFloor: return "Art/homeFloor@3x.png"
        case .homeStand: return "Art/homeCabinet@3x.png"
        case .homeStation: return "Art/homeScaffold@3x.png"
        case .hudHeartFull: return "UI/heartHUD@3x.png"
        case .hudHeartHalves: return "UI/heartHUDHalves@3x.png"
        case .hudHeartLost: return "UI/heartHUDLost@3x.png"
        case .hudPlusBadge: return "UI/iconPlusGreen@3x.png"
        case .hudTimerIcon: return "UI/iconStopwatch@3x.png"
        case .hudTimerIconFrozen: return "UI/iconStopwatchFrozen@3x.png"
        case .hudTimerIconSmall: return "UI/iconStopwatchSmall@3x.png"
        case .iconBell: return "UI/glyphBell@3x.png"
        case .iconCheck: return "UI/iconCheck@3x.png"
        case .iconCheckBadge: return "UI/iconCheckBadge@3x.png"
        case .iconFinishFlag: return "UI/iconCheckeredFlag@3x.png"
        case .iconHaptic: return "UI/glyphHaptic@3x.png"
        case .iconHapticLight: return "UI/glyphHapticWhite@3x.png"
        case .iconInfo: return "UI/infoPathIcon@3x.png"
        case .iconLock: return "UI/padlockGold@3x.png"
        case .iconMusic: return "UI/glyphMusic@3x.png"
        case .iconOffSlash: return "UI/glyphOffSlash@3x.png"
        case .iconPencil: return "UI/iconPencil@3x.png"
        case .iconPointer: return "UI/pointerArrowYellow@3x.png"
        case .iconPointerDown: return "UI/pointerArrowDown@3x.png"
        case .iconSettings: return "UI/glyphGear@3x.png"
        case .iconSkull: return "UI/iconSkull@3x.png"
        case .iconSkullBones: return "UI/iconSkullBones@3x.png"
        case .iconSound: return "UI/glyphSound@3x.png"
        case .iconSoundLight: return "UI/glyphSoundWhite@3x.png"
        case .leaderboardPodium: return "Art/cupPodium@3x.png"
        case .livesHeart: return "UI/heartLives@3x.png"
        case .livesHeartBig: return "UI/heartLivesBig@3x.png"
        case .livesHeartGlossySmall: return "UI/heartGlossySmall@3x.png"
        case .livesLost: return "UI/heartBroken@3x.png"
        case .livesUnlimited: return "UI/heartInfinite@3x.png"
        case .livesUnlimitedSmall: return "UI/heartInfiniteSmall@3x.png"
        case .loadingBackdrop: return "Art/loadingBackdrop@3x.png"
        case .loadingCast1: return "Art/char_digDockL@3x.png"
        case .loadingCast2: return "Art/char_digPop1@3x.png"
        case .loadingCast3: return "Art/char_bossLoading@3x.png"
        case .loadingCast4: return "Art/char_digPop2@3x.png"
        case .loadingCast5: return "Art/char_digFlyer@3x.png"
        case .loadingCast6: return "Art/char_digCart@3x.png"
        case .logoMain: return "UI/logoArrowOut@3x.png"
        case .logoPartLogoLetterA: return "UI/logoLetterA@3x.png"
        case .logoPartLogoLetterAExt: return "UI/logoLetterAExt@3x.png"
        case .logoPartLogoLetterAFace: return "UI/logoLetterAFace@3x.png"
        case .logoPartLogoLetterAFlat: return "UI/logoLetterAFlat@3x.png"
        case .logoPartLogoLetterO: return "UI/logoLetterO@3x.png"
        case .logoPartLogoLetterOExt: return "UI/logoLetterOExt@3x.png"
        case .logoPartLogoLetterOFace: return "UI/logoLetterOFace@3x.png"
        case .logoPartLogoLetterOFlat: return "UI/logoLetterOFlat@3x.png"
        case .logoPartLogoLetterR1: return "UI/logoLetterR1@3x.png"
        case .logoPartLogoLetterR1Ext: return "UI/logoLetterR1Ext@3x.png"
        case .logoPartLogoLetterR1Face: return "UI/logoLetterR1Face@3x.png"
        case .logoPartLogoLetterR1Flat: return "UI/logoLetterR1Flat@3x.png"
        case .logoPartLogoLetterR2: return "UI/logoLetterR2@3x.png"
        case .logoPartLogoLetterR2Ext: return "UI/logoLetterR2Ext@3x.png"
        case .logoPartLogoLetterR2Face: return "UI/logoLetterR2Face@3x.png"
        case .logoPartLogoLetterR2Flat: return "UI/logoLetterR2Flat@3x.png"
        case .logoPartLogoLetterW: return "UI/logoLetterW@3x.png"
        case .logoPartLogoLetterWExt: return "UI/logoLetterWExt@3x.png"
        case .logoPartLogoLetterWFace: return "UI/logoLetterWFace@3x.png"
        case .logoPartLogoLetterWFlat: return "UI/logoLetterWFlat@3x.png"
        case .logoPartLogoOut: return "UI/logoOut@3x.png"
        case .logoPartLogoOutBang: return "UI/logoOutBang@3x.png"
        case .logoPartLogoOutBangExt: return "UI/logoOutBangExt@3x.png"
        case .logoPartLogoOutBangFace: return "UI/logoOutBangFace@3x.png"
        case .logoPartLogoOutO: return "UI/logoOutO@3x.png"
        case .logoPartLogoOutOExt: return "UI/logoOutOExt@3x.png"
        case .logoPartLogoOutOFace: return "UI/logoOutOFace@3x.png"
        case .logoPartLogoOutT: return "UI/logoOutT@3x.png"
        case .logoPartLogoOutTExt: return "UI/logoOutTExt@3x.png"
        case .logoPartLogoOutTFace: return "UI/logoOutTFace@3x.png"
        case .logoPartLogoOutU: return "UI/logoOutU@3x.png"
        case .logoPartLogoOutUExt: return "UI/logoOutUExt@3x.png"
        case .logoPartLogoOutUFace: return "UI/logoOutUFace@3x.png"
        case .logoPartLogoPegs: return "UI/logoPegs@3x.png"
        case .logoPartLogoSignBlue: return "UI/logoSignBlue@3x.png"
        case .logoPartLogoSignPurple: return "UI/logoSignPurple@3x.png"
        case .logoPartLogoSignPurpleBend100: return "UI/logoSignPurpleBend100@3x.png"
        case .logoPartLogoSignPurpleBend25: return "UI/logoSignPurpleBend25@3x.png"
        case .logoPartLogoSignPurpleBend50: return "UI/logoSignPurpleBend50@3x.png"
        case .logoPartLogoSignPurpleBend75: return "UI/logoSignPurpleBend75@3x.png"
        case .navHomeIcon: return "UI/navLodge@3x.png"
        case .navLeaderboardIcon: return "UI/navCup@3x.png"
        case .navShopIcon: return "UI/navCart@3x.png"
        case .pagePattern: return "UI/pageBgPattern@3x.png"
        case .popupOutOfTimeHeart: return "UI/heartBig@3x.png"
        case .popupOutOfTimeStopwatch: return "UI/stopwatchBig@3x.png"
        case .profileStatFirstTry: return "UI/statFirstTryIcon@3x.png"
        case .profileStatWeeklyWins: return "UI/statWeeklyWinsIcon@3x.png"
        case .puzzleBoardTrailStar: return "UI/boardTrailStar@3x.png"
        case .puzzleBoxRing: return "UI/boxRing@3x.png"
        case .puzzleBoxSlab: return "UI/boxSlab@3x.png"
        case .puzzleCornerDownLeftPlate: return "UI/cornerDownLeftPlate@3x.png"
        case .puzzleCornerDownLeftSpring: return "UI/cornerDownLeftSpring@3x.png"
        case .puzzleCornerDownRightPlate: return "UI/cornerDownRightPlate@3x.png"
        case .puzzleCornerDownRightSpring: return "UI/cornerDownRightSpring@3x.png"
        case .puzzleCornerUpLeftPlate: return "UI/cornerUpLeftPlate@3x.png"
        case .puzzleCornerUpLeftSpring: return "UI/cornerUpLeftSpring@3x.png"
        case .puzzleCornerUpRightPlate: return "UI/cornerUpRightPlate@3x.png"
        case .puzzleCornerUpRightSpring: return "UI/cornerUpRightSpring@3x.png"
        case .puzzleCornerWedge: return "UI/cornerWedge@3x.png"
        case .puzzleDoorShards: return "UI/doorShards@3x.png"
        case .puzzleDoorW11H10: return "UI/doorW11H10@3x.png"
        case .puzzleDoorW13H4: return "UI/doorW13H4@3x.png"
        case .puzzleDoorW22H10: return "UI/doorW22H10@3x.png"
        case .puzzleDoorW4H12: return "UI/doorW4H12@3x.png"
        case .puzzleDoorW4H16: return "UI/doorW4H16@3x.png"
        case .puzzleDoorW4H20: return "UI/doorW4H20@3x.png"
        case .puzzleDoorW4H4: return "UI/doorW4H4@3x.png"
        case .puzzleDoorW4H8: return "UI/doorW4H8@3x.png"
        case .puzzleDoorW5H17: return "UI/doorW5H17@3x.png"
        case .puzzleKeyOnArrow: return "UI/keyOnArrow@3x.png"
        case .puzzleLockHex: return "UI/lockHex@3x.png"
        case .puzzlePipeCounter: return "UI/pipeCounter@3x.png"
        case .puzzlePipeMouth: return "UI/pipeMouth@3x.png"
        case .puzzlePipeShards: return "UI/pipeShards@3x.png"
        case .puzzleTapeH2: return "UI/tapeH2@3x.png"
        case .puzzleTapeH3: return "UI/tapeH3@3x.png"
        case .puzzleTapeH4: return "UI/tapeH4@3x.png"
        case .puzzleTapeV2: return "UI/tapeV2@3x.png"
        case .puzzleTapeV3: return "UI/tapeV3@3x.png"
        case .puzzleTapeV4: return "UI/tapeV4@3x.png"
        case .rank1Badge: return "UI/rankBadgeGold@3x.png"
        case .rank1Wings: return "UI/rankWings1@3x.png"
        case .rank2Badge: return "UI/rankBadgeSilver@3x.png"
        case .rank3Badge: return "UI/rankBadgeBronze@3x.png"
        case .rewardChest1: return "UI/stageChestGreen@3x.png"
        case .rewardChest2: return "UI/stageChestBlue@3x.png"
        case .rewardChest3: return "UI/stageChestPink@3x.png"
        case .rewardCoinBowl: return "UI/coinBowl@3x.png"
        case .rewardCoins: return "UI/coinStackReward@3x.png"
        case .rewardCoinsSmall: return "UI/coinPileSmall@3x.png"
        case .shopBundleElite: return "UI/bundleChest@3x.png"
        case .shopBundleEpic: return "UI/bundleBarrel@3x.png"
        case .shopBundleLegendary: return "UI/bundleCart@3x.png"
        case .shopBundleMega: return "UI/bundleSafe@3x.png"
        case .shopBundleMini: return "UI/bundleBag@3x.png"
        case .shopBundleSpecial: return "UI/bundleSpecial@3x.png"
        case .shopCoins1: return "UI/coinPackTiny@3x.png"
        case .shopCoins2: return "UI/coinPackSmall@3x.png"
        case .shopCoins3: return "UI/coinPackMedium@3x.png"
        case .shopCoins4: return "UI/coinPackBig@3x.png"
        case .shopCoins5: return "UI/coinPackSuper@3x.png"
        case .shopCoins6: return "UI/coinPackGiant@3x.png"
        case .shopSeal: return "UI/shopSeal@3x.png"
        case .socialScoreChip: return "UI/scoreChip@3x.png"
        case .tutorialHand: return "UI/tutorialHand@3x.png"
        case .unlockBoxIcon: return "UI/unlockIconBox@3x.png"
        case .unlockCornerIcon: return "UI/unlockIconCorner@3x.png"
        case .unlockDoorIcon: return "UI/unlockIconDoor@3x.png"
        case .unlockElevatorIcon: return "UI/unlockIconElevator@3x.png"
        case .unlockLinkedIcon: return "UI/unlockIconLinked@3x.png"
        case .unlockPipeIcon: return "UI/unlockIconPipe@3x.png"
        }
    }

    /// The manifest size in pt (the @3x file is 3x this).
    var sizePt: CGSize {
        switch self {
        case .avatar0: return CGSize(width: 64, height: 64)
        case .avatar1: return CGSize(width: 64, height: 64)
        case .avatar2: return CGSize(width: 64, height: 64)
        case .avatar3: return CGSize(width: 64, height: 64)
        case .avatar4: return CGSize(width: 64, height: 64)
        case .avatar5: return CGSize(width: 64, height: 64)
        case .avatar6: return CGSize(width: 64, height: 64)
        case .avatar7: return CGSize(width: 64, height: 64)
        case .avatar8: return CGSize(width: 64, height: 64)
        case .boosterFreezeIcon: return CGSize(width: 56, height: 56)
        case .boosterHintIcon: return CGSize(width: 56, height: 56)
        case .currencyCoinIcon: return CGSize(width: 39, height: 39)
        case .eventBalloonRiseBadge: return CGSize(width: 46, height: 46)
        case .eventBalloonRiseCloudA: return CGSize(width: 150, height: 70)
        case .eventBalloonRiseCloudB: return CGSize(width: 100, height: 56)
        case .eventBalloonRiseHero: return CGSize(width: 150, height: 220)
        case .eventBalloonRiseLedge: return CGSize(width: 240, height: 150)
        case .eventBalloonRiseTowerFoot: return CGSize(width: 393, height: 700)
        case .eventBalloonRiseTowerShaft: return CGSize(width: 112, height: 340)
        case .eventBalloonRiseTowerTop: return CGSize(width: 393, height: 470)
        case .eventClawChallengeHeader: return CGSize(width: 393, height: 240)
        case .eventClawChallengeToken: return CGSize(width: 40, height: 40)
        case .eventRocketRaceBackdrop: return CGSize(width: 393, height: 852)
        case .eventRocketRaceBadge: return CGSize(width: 80, height: 84)
        case .eventRocketRaceOffer: return CGSize(width: 330, height: 504)
        case .eventRocketRaceRacerMine: return CGSize(width: 68, height: 98)
        case .eventRocketRaceRacerOther: return CGSize(width: 68, height: 98)
        case .eventRocketRaceStage1: return CGSize(width: 60, height: 60)
        case .eventRocketRaceStage2: return CGSize(width: 60, height: 60)
        case .eventRocketRaceStage3: return CGSize(width: 104, height: 60)
        case .eventSkyJumpBackdrop: return CGSize(width: 393, height: 852)
        case .eventSkyJumpBadge: return CGSize(width: 80, height: 84)
        case .eventSkyJumpIcon: return CGSize(width: 57, height: 52)
        case .eventSkyJumpOffer: return CGSize(width: 330, height: 190)
        case .eventSkyJumpPad: return CGSize(width: 112, height: 104)
        case .eventSkyJumpPlatform: return CGSize(width: 260, height: 256)
        case .eventSkyJumpPlatformFar: return CGSize(width: 166, height: 158)
        case .eventSkyJumpPlatformFar2: return CGSize(width: 144, height: 132)
        case .eventStreakRaceBadge: return CGSize(width: 80, height: 84)
        case .eventStreakRaceHeader: return CGSize(width: 393, height: 290)
        case .fxFrostVignette: return CGSize(width: 393, height: 852)
        case .fxSparkle: return CGSize(width: 16, height: 16)
        case .fxSunburst: return CGSize(width: 190, height: 86)
        case .homeBackdrop: return CGSize(width: 393, height: 852)
        case .homeCentrepiece: return CGSize(width: 190, height: 128)
        case .homeFloor: return CGSize(width: 393, height: 182)
        case .homeStand: return CGSize(width: 206, height: 215)
        case .homeStation: return CGSize(width: 191, height: 192)
        case .hudHeartFull: return CGSize(width: 31, height: 27)
        case .hudHeartHalves: return CGSize(width: 31, height: 27)
        case .hudHeartLost: return CGSize(width: 31, height: 27)
        case .hudPlusBadge: return CGSize(width: 24, height: 24)
        case .hudTimerIcon: return CGSize(width: 33, height: 33)
        case .hudTimerIconFrozen: return CGSize(width: 34, height: 50)
        case .hudTimerIconSmall: return CGSize(width: 26, height: 28)
        case .iconBell: return CGSize(width: 30, height: 36)
        case .iconCheck: return CGSize(width: 60, height: 54)
        case .iconCheckBadge: return CGSize(width: 40, height: 34)
        case .iconFinishFlag: return CGSize(width: 30, height: 32)
        case .iconHaptic: return CGSize(width: 34, height: 33)
        case .iconHapticLight: return CGSize(width: 42, height: 38)
        case .iconInfo: return CGSize(width: 118, height: 118)
        case .iconLock: return CGSize(width: 44, height: 54)
        case .iconMusic: return CGSize(width: 38, height: 36)
        case .iconOffSlash: return CGSize(width: 56, height: 52)
        case .iconPencil: return CGSize(width: 32, height: 32)
        case .iconPointer: return CGSize(width: 46, height: 50)
        case .iconPointerDown: return CGSize(width: 78, height: 104)
        case .iconSettings: return CGSize(width: 26, height: 26)
        case .iconSkull: return CGSize(width: 30, height: 32)
        case .iconSkullBones: return CGSize(width: 38, height: 38)
        case .iconSound: return CGSize(width: 30, height: 30)
        case .iconSoundLight: return CGSize(width: 42, height: 38)
        case .leaderboardPodium: return CGSize(width: 389, height: 206)
        case .livesHeart: return CGSize(width: 42, height: 40)
        case .livesHeartBig: return CGSize(width: 100, height: 90)
        case .livesHeartGlossySmall: return CGSize(width: 46, height: 40)
        case .livesLost: return CGSize(width: 160, height: 132)
        case .livesUnlimited: return CGSize(width: 92, height: 84)
        case .livesUnlimitedSmall: return CGSize(width: 46, height: 42)
        case .loadingBackdrop: return CGSize(width: 393, height: 852)
        case .loadingCast1: return CGSize(width: 96, height: 76)
        case .loadingCast2: return CGSize(width: 170, height: 160)
        case .loadingCast3: return CGSize(width: 210, height: 250)
        case .loadingCast4: return CGSize(width: 170, height: 160)
        case .loadingCast5: return CGSize(width: 180, height: 220)
        case .loadingCast6: return CGSize(width: 270, height: 280)
        case .logoMain: return CGSize(width: 306, height: 236)
        case .logoPartLogoLetterA: return CGSize(width: 54.8825, height: 82.3237)
        case .logoPartLogoLetterAExt: return CGSize(width: 54.8825, height: 82.3237)
        case .logoPartLogoLetterAFace: return CGSize(width: 54.8825, height: 82.3237)
        case .logoPartLogoLetterAFlat: return CGSize(width: 54.8825, height: 82.3237)
        case .logoPartLogoLetterO: return CGSize(width: 54.8825, height: 79.485)
        case .logoPartLogoLetterOExt: return CGSize(width: 54.8825, height: 79.485)
        case .logoPartLogoLetterOFace: return CGSize(width: 54.8825, height: 79.485)
        case .logoPartLogoLetterOFlat: return CGSize(width: 54.8825, height: 79.485)
        case .logoPartLogoLetterR1: return CGSize(width: 49.205, height: 78.5387)
        case .logoPartLogoLetterR1Ext: return CGSize(width: 49.205, height: 78.5387)
        case .logoPartLogoLetterR1Face: return CGSize(width: 49.205, height: 78.5387)
        case .logoPartLogoLetterR1Flat: return CGSize(width: 49.205, height: 78.5387)
        case .logoPartLogoLetterR2: return CGSize(width: 50.1512, height: 79.485)
        case .logoPartLogoLetterR2Ext: return CGSize(width: 50.1512, height: 79.485)
        case .logoPartLogoLetterR2Face: return CGSize(width: 50.1512, height: 79.485)
        case .logoPartLogoLetterR2Flat: return CGSize(width: 50.1512, height: 79.485)
        case .logoPartLogoLetterW: return CGSize(width: 61.5062, height: 82.3237)
        case .logoPartLogoLetterWExt: return CGSize(width: 61.5062, height: 82.3237)
        case .logoPartLogoLetterWFace: return CGSize(width: 61.5062, height: 82.3237)
        case .logoPartLogoLetterWFlat: return CGSize(width: 61.5062, height: 82.3237)
        case .logoPartLogoOut: return CGSize(width: 153.292, height: 64.9758)
        case .logoPartLogoOutBang: return CGSize(width: 23.1529, height: 62.4122)
        case .logoPartLogoOutBangExt: return CGSize(width: 23.1529, height: 62.4122)
        case .logoPartLogoOutBangFace: return CGSize(width: 23.1529, height: 62.4122)
        case .logoPartLogoOutO: return CGSize(width: 57.379, height: 63.4189)
        case .logoPartLogoOutOExt: return CGSize(width: 57.379, height: 63.4189)
        case .logoPartLogoOutOFace: return CGSize(width: 57.379, height: 63.4189)
        case .logoPartLogoOutT: return CGSize(width: 52.3457, height: 63.4189)
        case .logoPartLogoOutTExt: return CGSize(width: 52.3457, height: 63.4189)
        case .logoPartLogoOutTFace: return CGSize(width: 52.3457, height: 63.4189)
        case .logoPartLogoOutU: return CGSize(width: 51.3391, height: 63.4189)
        case .logoPartLogoOutUExt: return CGSize(width: 51.3391, height: 63.4189)
        case .logoPartLogoOutUFace: return CGSize(width: 51.3391, height: 63.4189)
        case .logoPartLogoPegs: return CGSize(width: 112.745, height: 24.1596)
        case .logoPartLogoSignBlue: return CGSize(width: 283.244, height: 133.737)
        case .logoPartLogoSignPurple: return CGSize(width: 234.214, height: 134.22)
        case .logoPartLogoSignPurpleBend100: return CGSize(width: 234.214, height: 134.22)
        case .logoPartLogoSignPurpleBend25: return CGSize(width: 234.214, height: 134.22)
        case .logoPartLogoSignPurpleBend50: return CGSize(width: 234.214, height: 134.22)
        case .logoPartLogoSignPurpleBend75: return CGSize(width: 234.214, height: 134.22)
        case .navHomeIcon: return CGSize(width: 80, height: 86)
        case .navLeaderboardIcon: return CGSize(width: 68, height: 62)
        case .navShopIcon: return CGSize(width: 62, height: 62)
        case .pagePattern: return CGSize(width: 145, height: 79)
        case .popupOutOfTimeHeart: return CGSize(width: 194, height: 164)
        case .popupOutOfTimeStopwatch: return CGSize(width: 225, height: 225)
        case .profileStatFirstTry: return CGSize(width: 56, height: 54)
        case .profileStatWeeklyWins: return CGSize(width: 48, height: 51)
        case .puzzleBoardTrailStar: return CGSize(width: 12, height: 12)
        case .puzzleBoxRing: return CGSize(width: 76, height: 76)
        case .puzzleBoxSlab: return CGSize(width: 104, height: 104)
        case .puzzleCornerDownLeftPlate: return CGSize(width: 64, height: 64)
        case .puzzleCornerDownLeftSpring: return CGSize(width: 64, height: 64)
        case .puzzleCornerDownRightPlate: return CGSize(width: 64, height: 64)
        case .puzzleCornerDownRightSpring: return CGSize(width: 64, height: 64)
        case .puzzleCornerUpLeftPlate: return CGSize(width: 64, height: 64)
        case .puzzleCornerUpLeftSpring: return CGSize(width: 64, height: 64)
        case .puzzleCornerUpRightPlate: return CGSize(width: 64, height: 64)
        case .puzzleCornerUpRightSpring: return CGSize(width: 64, height: 64)
        case .puzzleCornerWedge: return CGSize(width: 64, height: 64)
        case .puzzleDoorShards: return CGSize(width: 48, height: 48)
        case .puzzleDoorW11H10: return CGSize(width: 358, height: 326)
        case .puzzleDoorW13H4: return CGSize(width: 422, height: 134)
        case .puzzleDoorW22H10: return CGSize(width: 710, height: 326)
        case .puzzleDoorW4H12: return CGSize(width: 134, height: 390)
        case .puzzleDoorW4H16: return CGSize(width: 134, height: 518)
        case .puzzleDoorW4H20: return CGSize(width: 134, height: 646)
        case .puzzleDoorW4H4: return CGSize(width: 134, height: 134)
        case .puzzleDoorW4H8: return CGSize(width: 134, height: 262)
        case .puzzleDoorW5H17: return CGSize(width: 166, height: 550)
        case .puzzleKeyOnArrow: return CGSize(width: 43, height: 78)
        case .puzzleLockHex: return CGSize(width: 73, height: 68)
        case .puzzlePipeCounter: return CGSize(width: 68, height: 53)
        case .puzzlePipeMouth: return CGSize(width: 47, height: 30)
        case .puzzlePipeShards: return CGSize(width: 48, height: 48)
        case .puzzleTapeH2: return CGSize(width: 54, height: 39)
        case .puzzleTapeH3: return CGSize(width: 86, height: 39)
        case .puzzleTapeH4: return CGSize(width: 118, height: 39)
        case .puzzleTapeV2: return CGSize(width: 39, height: 54)
        case .puzzleTapeV3: return CGSize(width: 39, height: 86)
        case .puzzleTapeV4: return CGSize(width: 39, height: 118)
        case .rank1Badge: return CGSize(width: 40, height: 40)
        case .rank1Wings: return CGSize(width: 52, height: 38)
        case .rank2Badge: return CGSize(width: 40, height: 40)
        case .rank3Badge: return CGSize(width: 40, height: 40)
        case .rewardChest1: return CGSize(width: 56, height: 42)
        case .rewardChest2: return CGSize(width: 56, height: 42)
        case .rewardChest3: return CGSize(width: 56, height: 42)
        case .rewardCoinBowl: return CGSize(width: 74, height: 62)
        case .rewardCoins: return CGSize(width: 110, height: 100)
        case .rewardCoinsSmall: return CGSize(width: 68, height: 56)
        case .shopBundleElite: return CGSize(width: 176, height: 102)
        case .shopBundleEpic: return CGSize(width: 176, height: 102)
        case .shopBundleLegendary: return CGSize(width: 176, height: 102)
        case .shopBundleMega: return CGSize(width: 176, height: 102)
        case .shopBundleMini: return CGSize(width: 176, height: 102)
        case .shopBundleSpecial: return CGSize(width: 176, height: 102)
        case .shopCoins1: return CGSize(width: 102, height: 66)
        case .shopCoins2: return CGSize(width: 102, height: 66)
        case .shopCoins3: return CGSize(width: 102, height: 66)
        case .shopCoins4: return CGSize(width: 102, height: 66)
        case .shopCoins5: return CGSize(width: 102, height: 66)
        case .shopCoins6: return CGSize(width: 102, height: 66)
        case .shopSeal: return CGSize(width: 66, height: 66)
        case .socialScoreChip: return CGSize(width: 40, height: 44)
        case .tutorialHand: return CGSize(width: 102, height: 136)
        case .unlockBoxIcon: return CGSize(width: 132, height: 134)
        case .unlockCornerIcon: return CGSize(width: 100, height: 100)
        case .unlockDoorIcon: return CGSize(width: 128, height: 128)
        case .unlockElevatorIcon: return CGSize(width: 164, height: 112)
        case .unlockLinkedIcon: return CGSize(width: 150, height: 106)
        case .unlockPipeIcon: return CGSize(width: 156, height: 124)
        }
    }

    /// The manifest group (placeholder tint, preload sets).
    var group: String {
        switch self {
        case .avatar0: return "avatars"
        case .avatar1: return "avatars"
        case .avatar2: return "avatars"
        case .avatar3: return "avatars"
        case .avatar4: return "avatars"
        case .avatar5: return "avatars"
        case .avatar6: return "avatars"
        case .avatar7: return "avatars"
        case .avatar8: return "avatars"
        case .boosterFreezeIcon: return "boosters"
        case .boosterHintIcon: return "boosters"
        case .currencyCoinIcon: return "hud"
        case .eventBalloonRiseBadge: return "home"
        case .eventBalloonRiseCloudA: return "events-balloon"
        case .eventBalloonRiseCloudB: return "events-balloon"
        case .eventBalloonRiseHero: return "events-balloon"
        case .eventBalloonRiseLedge: return "events-balloon"
        case .eventBalloonRiseTowerFoot: return "events-balloon"
        case .eventBalloonRiseTowerShaft: return "events-balloon"
        case .eventBalloonRiseTowerTop: return "events-balloon"
        case .eventClawChallengeHeader: return "events-claw"
        case .eventClawChallengeToken: return "home"
        case .eventRocketRaceBackdrop: return "events-rocket"
        case .eventRocketRaceBadge: return "home"
        case .eventRocketRaceOffer: return "events-rocket"
        case .eventRocketRaceRacerMine: return "events-rocket"
        case .eventRocketRaceRacerOther: return "events-rocket"
        case .eventRocketRaceStage1: return "events-rocket"
        case .eventRocketRaceStage2: return "events-rocket"
        case .eventRocketRaceStage3: return "events-rocket"
        case .eventSkyJumpBackdrop: return "events-skyjump"
        case .eventSkyJumpBadge: return "home"
        case .eventSkyJumpIcon: return "profile-shop-settings"
        case .eventSkyJumpOffer: return "events-skyjump"
        case .eventSkyJumpPad: return "events-skyjump"
        case .eventSkyJumpPlatform: return "events-skyjump"
        case .eventSkyJumpPlatformFar: return "events-skyjump"
        case .eventSkyJumpPlatformFar2: return "events-skyjump"
        case .eventStreakRaceBadge: return "home"
        case .eventStreakRaceHeader: return "events-streak"
        case .fxFrostVignette: return "fx"
        case .fxSparkle: return "fx"
        case .fxSunburst: return "events-claw"
        case .homeBackdrop: return "home"
        case .homeCentrepiece: return "home"
        case .homeFloor: return "home"
        case .homeStand: return "home"
        case .homeStation: return "home"
        case .hudHeartFull: return "hud"
        case .hudHeartHalves: return "fx"
        case .hudHeartLost: return "hud"
        case .hudPlusBadge: return "hud"
        case .hudTimerIcon: return "hud"
        case .hudTimerIconFrozen: return "hud"
        case .hudTimerIconSmall: return "hud"
        case .iconBell: return "profile-shop-settings"
        case .iconCheck: return "events-claw"
        case .iconCheckBadge: return "profile-shop-settings"
        case .iconFinishFlag: return "events-streak"
        case .iconHaptic: return "popups"
        case .iconHapticLight: return "profile-shop-settings"
        case .iconInfo: return "popups"
        case .iconLock: return "events-claw"
        case .iconMusic: return "profile-shop-settings"
        case .iconOffSlash: return "profile-shop-settings"
        case .iconPencil: return "profile-shop-settings"
        case .iconPointer: return "popups"
        case .iconPointerDown: return "popups"
        case .iconSettings: return "home"
        case .iconSkull: return "loading-win"
        case .iconSkullBones: return "loading-win"
        case .iconSound: return "popups"
        case .iconSoundLight: return "profile-shop-settings"
        case .leaderboardPodium: return "leaderboard"
        case .livesHeart: return "home"
        case .livesHeartBig: return "popups"
        case .livesHeartGlossySmall: return "popups"
        case .livesLost: return "popups"
        case .livesUnlimited: return "popups"
        case .livesUnlimitedSmall: return "popups"
        case .loadingBackdrop: return "loading-win"
        case .loadingCast1: return "characters"
        case .loadingCast2: return "characters"
        case .loadingCast3: return "characters"
        case .loadingCast4: return "characters"
        case .loadingCast5: return "characters"
        case .loadingCast6: return "characters"
        case .logoMain: return "loading-win"
        case .logoPartLogoLetterA: return "logo"
        case .logoPartLogoLetterAExt: return "logo"
        case .logoPartLogoLetterAFace: return "logo"
        case .logoPartLogoLetterAFlat: return "logo"
        case .logoPartLogoLetterO: return "logo"
        case .logoPartLogoLetterOExt: return "logo"
        case .logoPartLogoLetterOFace: return "logo"
        case .logoPartLogoLetterOFlat: return "logo"
        case .logoPartLogoLetterR1: return "logo"
        case .logoPartLogoLetterR1Ext: return "logo"
        case .logoPartLogoLetterR1Face: return "logo"
        case .logoPartLogoLetterR1Flat: return "logo"
        case .logoPartLogoLetterR2: return "logo"
        case .logoPartLogoLetterR2Ext: return "logo"
        case .logoPartLogoLetterR2Face: return "logo"
        case .logoPartLogoLetterR2Flat: return "logo"
        case .logoPartLogoLetterW: return "logo"
        case .logoPartLogoLetterWExt: return "logo"
        case .logoPartLogoLetterWFace: return "logo"
        case .logoPartLogoLetterWFlat: return "logo"
        case .logoPartLogoOut: return "logo"
        case .logoPartLogoOutBang: return "logo"
        case .logoPartLogoOutBangExt: return "logo"
        case .logoPartLogoOutBangFace: return "logo"
        case .logoPartLogoOutO: return "logo"
        case .logoPartLogoOutOExt: return "logo"
        case .logoPartLogoOutOFace: return "logo"
        case .logoPartLogoOutT: return "logo"
        case .logoPartLogoOutTExt: return "logo"
        case .logoPartLogoOutTFace: return "logo"
        case .logoPartLogoOutU: return "logo"
        case .logoPartLogoOutUExt: return "logo"
        case .logoPartLogoOutUFace: return "logo"
        case .logoPartLogoPegs: return "logo"
        case .logoPartLogoSignBlue: return "logo"
        case .logoPartLogoSignPurple: return "logo"
        case .logoPartLogoSignPurpleBend100: return "logo"
        case .logoPartLogoSignPurpleBend25: return "logo"
        case .logoPartLogoSignPurpleBend50: return "logo"
        case .logoPartLogoSignPurpleBend75: return "logo"
        case .navHomeIcon: return "home"
        case .navLeaderboardIcon: return "home"
        case .navShopIcon: return "home"
        case .pagePattern: return "profile-shop-settings"
        case .popupOutOfTimeHeart: return "popups"
        case .popupOutOfTimeStopwatch: return "popups"
        case .profileStatFirstTry: return "profile-shop-settings"
        case .profileStatWeeklyWins: return "profile-shop-settings"
        case .puzzleBoardTrailStar: return "board"
        case .puzzleBoxRing: return "board"
        case .puzzleBoxSlab: return "board"
        case .puzzleCornerDownLeftPlate: return "board"
        case .puzzleCornerDownLeftSpring: return "board"
        case .puzzleCornerDownRightPlate: return "board"
        case .puzzleCornerDownRightSpring: return "board"
        case .puzzleCornerUpLeftPlate: return "board"
        case .puzzleCornerUpLeftSpring: return "board"
        case .puzzleCornerUpRightPlate: return "board"
        case .puzzleCornerUpRightSpring: return "board"
        case .puzzleCornerWedge: return "board"
        case .puzzleDoorShards: return "board"
        case .puzzleDoorW11H10: return "board"
        case .puzzleDoorW13H4: return "board"
        case .puzzleDoorW22H10: return "board"
        case .puzzleDoorW4H12: return "board"
        case .puzzleDoorW4H16: return "board"
        case .puzzleDoorW4H20: return "board"
        case .puzzleDoorW4H4: return "board"
        case .puzzleDoorW4H8: return "board"
        case .puzzleDoorW5H17: return "board"
        case .puzzleKeyOnArrow: return "board"
        case .puzzleLockHex: return "board"
        case .puzzlePipeCounter: return "board"
        case .puzzlePipeMouth: return "board"
        case .puzzlePipeShards: return "board"
        case .puzzleTapeH2: return "board"
        case .puzzleTapeH3: return "board"
        case .puzzleTapeH4: return "board"
        case .puzzleTapeV2: return "board"
        case .puzzleTapeV3: return "board"
        case .puzzleTapeV4: return "board"
        case .rank1Badge: return "events-streak"
        case .rank1Wings: return "events-rocket"
        case .rank2Badge: return "events-streak"
        case .rank3Badge: return "events-streak"
        case .rewardChest1: return "events-skyjump"
        case .rewardChest2: return "events-skyjump"
        case .rewardChest3: return "events-skyjump"
        case .rewardCoinBowl: return "events-streak"
        case .rewardCoins: return "popups"
        case .rewardCoinsSmall: return "events-claw"
        case .shopBundleElite: return "profile-shop-settings"
        case .shopBundleEpic: return "profile-shop-settings"
        case .shopBundleLegendary: return "profile-shop-settings"
        case .shopBundleMega: return "profile-shop-settings"
        case .shopBundleMini: return "profile-shop-settings"
        case .shopBundleSpecial: return "profile-shop-settings"
        case .shopCoins1: return "profile-shop-settings"
        case .shopCoins2: return "profile-shop-settings"
        case .shopCoins3: return "profile-shop-settings"
        case .shopCoins4: return "profile-shop-settings"
        case .shopCoins5: return "profile-shop-settings"
        case .shopCoins6: return "profile-shop-settings"
        case .shopSeal: return "profile-shop-settings"
        case .socialScoreChip: return "events-streak"
        case .tutorialHand: return "popups"
        case .unlockBoxIcon: return "popups"
        case .unlockCornerIcon: return "popups"
        case .unlockDoorIcon: return "popups"
        case .unlockElevatorIcon: return "popups"
        case .unlockLinkedIcon: return "popups"
        case .unlockPipeIcon: return "popups"
        }
    }
}

/// A puppet RIG slot (skin/art.json `rigs`): its folder under the bundle's Art/ (`PuppetRig.load`; its motion is
/// ui.json `puppet.<folder>`).
enum ArtRig: String, CaseIterable, Sendable {
    case eventBalloonRiseBadge = "event.balloonRise.badge"
    case eventRocketRaceBadge = "event.rocketRace.badge"
    case eventSkyJumpBadge = "event.skyJump.badge"
    case eventStreakRaceBadge = "event.streakRace.badge"
    case homeCentrepiece = "home.centrepiece"
    case homeCharacterLeft = "home.character.left"
    case homeCharacterMain = "home.character.main"
    case homeCharacterRight = "home.character.right"

    /// The rig folder (art/out/<folder>/rig.json -> Art/<folder>/rig.json).
    var folder: String {
        switch self {
        case .eventBalloonRiseBadge: return "badge_upaway_rig"
        case .eventRocketRaceBadge: return "badge_rocketrally_rig"
        case .eventSkyJumpBadge: return "badge_cloudhop_rig"
        case .eventStreakRaceBadge: return "badge_hotstreak_rig"
        case .homeCentrepiece: return "home_signpost_rig"
        case .homeCharacterLeft: return "char_dig_homeL_rig"
        case .homeCharacterMain: return "char_boss_home_rig"
        case .homeCharacterRight: return "char_dig_homeR_rig"
        }
    }
}
