#!/usr/bin/env python3
"""tools/skin/build.py — skin/colors.json -> the Swift colour constants (docs/SKIN.md).

    python3 tools/skin/build.py                   # validate colors.json, write the generated Swift files
    python3 tools/skin/build.py --check           # validate + fail (exit 1) if a generated file is stale
    python3 tools/skin/build.py --check-literals  # fail on any colour literal in the UI sources that is not a token
                                                  #   (outside tools/skin/literal_allowlist.json), any Skin.<name> the JSON
                                                  #   lacks, any token no source uses, any stale allow-list entry
    python3 tools/skin/build.py --selftest        # the lexer, naming, generation, colour maths and codemod on fixtures

colors.json
  {"palette": {"<family>.<L*>[b-z]": "#RRGGBB", …},     named base colours (one per distinct value)
   "tokens":  {"<area>.<file>.<scope>.<role>": "<palette name>" | "#RRGGBB", …}}
  A token id ending in ".hex" is a String token ("#RRGGBB", for the few call sites that take a hex string); every other
  token is a UInt32 0xRRGGBB. Token ids become Swift names by camel-casing the dotted parts (a.bC.d0 -> aBCD0).

Generated
  App/Shell/Components/SkinColors.generated.swift   `enum Skin { static let <name>: UInt32 = 0xRRGGBB … }` (no imports:
                                                    also compiled by art/ui/tools/swiftui_render.swift with GlossyChrome)
  Tests/AppTests/SkinColorsTable.generated.swift    token id -> constant table for SkinColorsTests (test target only)
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import skinlib as S  # noqa: E402

HEADER = """// GENERATED by tools/skin/build.py from skin/colors.json. Do not edit: edit the JSON (docs/SKIN.md), then run
//   python3 tools/skin/build.py
// One constant per colour token of the UI code. UInt32 0xRRGGBB constants: each call site converts one exactly as it
// converted the literal it replaced (Color(hex:), UIColor(rgb:), a [UInt32] gradient, a Tokens default …); the ".hex"
// tokens are "#RRGGBB" Strings (tuning-file string defaults). Plain `static let` constants: the compiler checks every use
// and folds the values; nothing is looked up at run time. No imports on purpose (swiftui_render.swift compiles it too).
"""


def generate(doc):
    groups = {}
    for t in sorted(doc["tokens"]):
        area_file = ".".join(t.split(".")[:2])
        groups.setdefault(area_file, []).append(t)
    out = [HEADER, "// swiftlint:disable all", "", "enum Skin {"]
    first = True
    for g, ids in groups.items():
        if not first:
            out.append("")
        first = False
        out.append(f"    // MARK: {g} ({len(ids)})")
        for t in ids:
            v = doc["tokens"][t]
            hx = S.resolve(doc, t)
            src = v if not v.startswith("#") else "literal"
            if S.is_string_token(t):
                out.append(f'    static let {S.swift_name(t)} = "{hx}"  // {t} = {src}')
            else:
                out.append(f"    static let {S.swift_name(t)}: UInt32 = 0x{hx[1:]}  // {t} = {src}")
    out.append("}")
    return "\n".join(out) + "\n"


def generate_test_table(doc):
    rgb = [t for t in sorted(doc["tokens"]) if not S.is_string_token(t)]
    hexs = [t for t in sorted(doc["tokens"]) if S.is_string_token(t)]
    out = ["// GENERATED by tools/skin/build.py from skin/colors.json. Do not edit.",
           "// Every token id with the value of its compiled constant (Skin.<name>), for SkinColorsTests.",
           "@testable import ArrowOut", "",
           "enum SkinColorsTable {"]
    # statements, not one giant literal: keeps the type checker linear
    out.append("    static func rgb() -> [String: UInt32] {")
    out.append(f"        var d = [String: UInt32](minimumCapacity: {len(rgb)})")
    out += [f'        d["{t}"] = Skin.{S.swift_name(t)}' for t in rgb]
    out.append("        return d")
    out.append("    }")
    out.append("")
    out.append("    static func hex() -> [String: String] {")
    out.append(f"        var d = [String: String](minimumCapacity: {len(hexs)})")
    out += [f'        d["{t}"] = Skin.{S.swift_name(t)}' for t in hexs]
    out.append("        return d")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def targets(doc):
    return [(S.GEN_SWIFT, generate(doc)), (S.GEN_TEST_SWIFT, generate_test_table(doc))]


def check_doc(doc):
    errs = S.validate(doc)
    art = S.uiart_names()
    for t in doc.get("tokens", {}):
        if S.swift_name(t) in art:
            errs.append(f"token {t}: its Swift name {S.swift_name(t)} is a UIArt id (the art-usage tests scan for those)")
    return errs


def check_literals(doc, files=None, allow=None, quiet=False):
    """-> list of problems (empty = clean)."""
    allow = S.load_allowlist() if allow is None else allow
    files = S.scanned_files() if files is None else files
    names = {S.swift_name(t): t for t in doc["tokens"]}
    used, used_allow, probs = set(), set(), []
    n_lit = n_ref = 0
    for p in files:
        text = open(p, encoding="utf-8").read()
        lx = S.swift_lex(text)
        r = S.rel(p)
        for o in S.scan_literals(p, lx):
            a = S.allowed(allow, r, o)
            if a:
                used_allow.add((a["file"], a["literal"]))
                continue
            n_lit += 1
            probs.append(f"{r}:{o['line']}: colour literal {o['text']} is not a skin token "
                         f"(run tools/skin/codemod.py, or allow-list it in tools/skin/literal_allowlist.json)")
        for m in re.finditer(r"\bSkin\.([A-Za-z_][A-Za-z0-9_]*)", lx.code):
            n_ref += 1
            if m.group(1) not in names:
                probs.append(f"{r}:{lx.line_of(m.start())}: Skin.{m.group(1)} is not a token of skin/colors.json")
            else:
                used.add(names[m.group(1)])
    for t in sorted(set(doc["tokens"]) - used):
        probs.append(f"token {t} is used by no source (remove it from skin/colors.json)")
    for a in allow:
        if (a["file"], a["literal"]) not in used_allow:
            probs.append(f"allow-list entry {a['file']} {a['literal']} matches nothing (remove it)")
    if not quiet:
        print(f"check-literals: {len(files)} files, {n_ref} Skin references, {len(used)} tokens used, "
              f"{len(used_allow)} allow-listed literals, {n_lit} un-tokened colour literals")
    return probs


# ============================================================================================ self-test

def selftest():
    import codemod as C
    fails = []

    def ok(cond, what):
        if not cond:
            fails.append(what)

    # lexer: comments (nested), strings (escapes, interpolation, multi-line, raw) are not code
    src = ('let a = 0x112233 // 0x445566\n/* 0x778899 /* nested 0xAABBCC */ 0xDDEEFF */\n'
           'let s = "0x010203 \\" \\(f(0x040506, "x")) #070809"\nlet r = #"0x0A0B0C "\\(x)" "#\n'
           'let m = """\n 0x0D0E0F \\(0x101112)\n"""\nlet h = "#A1B2C3"\n')
    lx = S.swift_lex(src)
    found = [m.group(0) for m in S.HEX_INT.finditer(lx.code)]
    ok(found == ["0x112233", "0x040506", "0x101112"], f"lexer: code literals {found}")
    strs = [c for (_, _, c, i) in lx.strings if not i]
    ok("#A1B2C3" in strs, f"lexer: string contents {strs}")
    ok(len(lx.code) == len(src) and lx.code.count("\n") == src.count("\n"), "lexer keeps length and lines")

    # names
    ok(S.swift_name("shop.shopView.priceButton.face.0") == "shopShopViewPriceButtonFace0", "swift_name")
    ok(C.lower_camel("HUDView") == "hudView" and C.lower_camel("S2Chrome") == "s2Chrome"
       and C.lower_camel("ShellLab+HUD") == "shellLabHUD", "lower_camel")

    # colour maths: every palette colour survives sRGB -> LCh -> sRGB
    doc = S.load_colors() if os.path.exists(S.COLORS_JSON) else {"palette": {}, "tokens": {}}
    for k, v in list(doc["palette"].items()) + [("x", "#000000"), ("y", "#FFFFFF"), ("z", "#00A2FF")]:
        L, Cc, h = S.lch(v)
        back, _ = S.lch_hex(L, Cc, h)
        ok(back == v, f"LCh round trip {k} {v} -> {back}")
        ok(S.palette_base_name(v).split(".")[0] in S.FAMILIES, f"family of {v}")

    # validation catches bad data
    bad = {"palette": {"teal.42": "#00a2ff", "Bad": "#000000"}, "tokens": {"a.b": "nope", "a.B": "#000000"}}
    errs = S.validate(bad)
    ok(len(errs) >= 4, f"validate: {errs}")

    # generation: every token's constant carries its resolved value
    tiny = {"palette": {"teal.42": "#00706B"}, "tokens": {"a.b.c": "teal.42", "a.b.d.hex": "#FFEEDD", "a.x": "#010203"}}
    g = generate(tiny)
    ok("static let aBC: UInt32 = 0x00706B" in g and 'static let aBDHex = "#FFEEDD"' in g
       and "static let aX: UInt32 = 0x010203" in g, "generate")
    t = generate_test_table(tiny)
    ok('d["a.b.c"] = Skin.aBC' in t and 'd["a.b.d.hex"] = Skin.aBDHex' in t, "generate_test_table")

    # codemod on a fixture: every literal replaced, values preserved, allow-list honoured, inline_back restores it
    fixture = ('import SwiftUI\nstruct PriceButton: View {\n    var outline: UInt32 = 0x0A0B0C\n'
               '    var body: some View {\n        let seed = UInt64(0xC0FFEE)\n'
               '        Capsule().fill(Color(hex: on ? 0x112233 : 0x445566)) // 0x778899 stays\n'
               '        Text("id #12").foregroundStyle(Color(hexString: t.string("k", "#ABCDEF"))!)\n'
               '            .background(Color(hex: t.color("price.face", 0x00A2FF)))\n'
               '        let st = [(0, 0x010101), (1.0, 0x020202)]\n'
               '        let star = UIColor(red: 1, green: 0.910, blue: 0.698, alpha: 1)\n    }\n}\n')
    with tempfile.TemporaryDirectory() as d:
        sub = os.path.join(d, "App", "Shell", "Shop")
        os.makedirs(sub)
        p = os.path.join(sub, "PriceButton.swift")
        with open(p, "w") as f:
            f.write(fixture)
        old_app, old_allow = S.APP, S.load_allowlist
        S.APP = d
        S.load_allowlist = lambda: [{"file": "App/Shell/Shop/PriceButton.swift", "literal": "0xC0FFEE", "reason": "seed"}]
        try:
            fdoc = {"palette": {}, "tokens": {}}
            edits, new = C.plan([p], fdoc)
            C.apply(edits)
            out = open(p).read()
            ok(len(new) == 8, f"codemod fixture: {len(new)} new tokens {sorted(new)}")
            ok("0xC0FFEE" in out and "0x778899 stays" in out and '"id #12"' in out, "codemod keeps allow-list, comments, "
               "non-colour strings")
            ok("shop.priceButton.price.face" in fdoc["tokens"], f"codemod: Tokens key names the token {sorted(fdoc['tokens'])}")
            ok("shop.priceButton.priceButton.fill.on" in fdoc["tokens"]
               and "shop.priceButton.priceButton.fill.notOn" in fdoc["tokens"], "codemod: ternary branches named")
            ok("UIColor(rgb: Skin." in out and ", alpha: 1)" in out, "codemod: decimal UIColor -> UIColor(rgb:alpha:)")
            back = C.inline_back(out, fdoc)
            expect = fixture.replace("UIColor(red: 1, green: 0.910, blue: 0.698, alpha: 1)", "UIColor(rgb: 0xFFE8B2, alpha: 1)")
            ok(back == expect, "codemod: inlining the tokens back gives the original source")
            probs = check_literals(fdoc, [p], S.load_allowlist(), quiet=True)
            ok(probs == [], f"check-literals on the rewritten fixture: {probs}")
            with open(p, "a") as f:
                f.write("let late = Color(hex: 0x999999)\nlet typo = Skin.nope\n")
            probs = check_literals(fdoc, [p], S.load_allowlist(), quiet=True)
            ok(any("0x999999" in x for x in probs) and any("Skin.nope" in x for x in probs), f"check-literals finds: {probs}")
        finally:
            S.APP, S.load_allowlist = old_app, old_allow

    for f in fails:
        print("SELFTEST FAIL:", f)
    print(f"selftest: {'OK' if not fails else f'{len(fails)} failures'}")
    return not fails


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--check-literals", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        sys.exit(0 if selftest() else 1)
    doc = S.load_colors()
    errs = check_doc(doc)
    if errs:
        print("\n".join("colors.json: " + e for e in errs))
        sys.exit(1)
    if a.check_literals:
        probs = check_literals(doc)
        for p in probs:
            print(p)
        sys.exit(1 if probs else 0)
    stale = []
    for path, text in targets(doc):
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if cur != text:
            stale.append(path)
            if not a.check:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)
    n_rgb = sum(1 for t in doc["tokens"] if not S.is_string_token(t))
    summary = (f"{len(doc['palette'])} palette colours, {len(doc['tokens'])} tokens ({n_rgb} UInt32, "
               f"{len(doc['tokens']) - n_rgb} String)")
    if a.check:
        if stale:
            print("stale (run python3 tools/skin/build.py): " + ", ".join(S.rel(p) for p in stale))
            sys.exit(1)
        print(f"skin colours up to date: {summary}")
    else:
        print(f"wrote {', '.join(S.rel(p) for p in stale) or 'nothing (up to date)'}: {summary}")


if __name__ == "__main__":
    main()
