#!/usr/bin/env python3
"""VERIFY V2: compare every capture of tools/capture/manifest.json with its reference over tools/compare/regions.json.
Copied from apps/matchfactory/tools/compare/compare_all.py (e10a076); only this docstring changed (design/REUSE.md).
References are research shots (LOOKED at and measured, never shipped); results go to build/compare (gitignored).

    tools/compare/compare_all.py [--captures build/compare/captures] [--out build/compare] [--only id,id]

Writes, under --out:
  sbs/<id>-<lang>.png       reference | ours, regions outlined and numbered (green dE <= 6, red above)
  results.json              every region row (side_by_side.measure) per capture and language
  results.md                the per-region tables, the fails first
For burst captures (a moment no freeze hook reaches) the burst frame closest to the reference (lowest mean dE) is used and named.
"""
import argparse, glob, json, os, sys

sys.path.insert(0, os.path.dirname(__file__))
import side_by_side as sbs

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--captures", default=os.path.join(ROOT, "build", "compare", "captures"))
    ap.add_argument("--out", default=os.path.join(ROOT, "build", "compare"))
    ap.add_argument("--only", default="")
    a = ap.parse_args()
    manifest = {e["id"]: e for e in json.load(open(os.path.join(ROOT, "tools", "capture", "manifest.json")))["captures"]}
    regions = {s["id"]: s["regions"] for s in json.load(open(os.path.join(ROOT, "tools", "compare", "regions.json")))["shots"]}
    only = [s for s in a.only.split(",") if s]
    os.makedirs(os.path.join(a.out, "sbs"), exist_ok=True)
    res_path = os.path.join(a.out, "results.json")
    results = json.load(open(res_path)) if (only and os.path.exists(res_path)) else {}
    for cid, e in manifest.items():
        if only and cid not in only:
            continue
        if cid not in regions:
            print("no regions for", cid); continue
        ref = sbs.load(os.path.join(ROOT, e["ref"]))
        for lang in e.get("langs", ["en", "tr"]):
            base = os.path.join(a.captures, f"{cid}-{lang}")
            if not os.path.exists(base + ".png"):
                results[f"{cid}-{lang}"] = {"missing": True}; print("missing", cid, lang); continue
            cands = [base + ".png"] + sorted(glob.glob(base + "@*.png"))
            best = None
            for c in cands:
                rows = sbs.measure(ref, sbs.load(c), regions[cid])
                score = sum(r["dE"] for r in rows) / max(1, len(rows))
                if best is None or score < best[0]:
                    best = (score, c, rows)
            _, cpath, rows = best
            meta = json.load(open(base + ".json")) if os.path.exists(base + ".json") else {}
            sbs.sbs_image(ref, sbs.load(cpath), rows, f"{cid} {lang}  vs {os.path.basename(e['ref'])}").save(
                os.path.join(a.out, "sbs", f"{cid}-{lang}.png"))
            results[f"{cid}-{lang}"] = {"id": cid, "lang": lang, "ref": e["ref"], "capture": os.path.relpath(cpath, ROOT),
                                        "ready": meta.get("ready"), "note": e.get("note", ""), "rows": rows}
            nf = sum(1 for r in rows if not r["pass"])
            print(f"{cid:<10} {lang}  {len(rows):>2} regions  {nf} over 6  worst {max(r['dE'] for r in rows):.1f}  ({os.path.basename(cpath)})")
    json.dump(results, open(res_path, "w"), indent=1)
    # markdown
    lines = ["# V2 per-region comparison (CIEDE2000 of the region mean; pass <= 6)", "",
             "Generated by tools/compare/compare_all.py. dL = L*(ours) - L*(ref); blk = median dE over 3 pt blocks (structure, advisory).", ""]
    for key in sorted(results):
        r = results[key]
        if r.get("missing"):
            lines.append(f"## {key}: MISSING"); continue
        lines += [f"## {key}  (ref {os.path.basename(r['ref'])}; {r['note']})", "",
                  "| # | region | kind | dE | dL | blk | ref | ours | |", "|---|---|---|---|---|---|---|---|---|"]
        for row in r["rows"]:
            lines.append(f"| {row['i']} | {row['name']} | {row['kind']} | {row['dE']:.1f} | {row['dL']:+.1f} | {row['dEblk']:.1f} | {row['ref']} | {row['ours']} | {'' if row['pass'] else '**over**'} |")
        lines.append("")
    open(os.path.join(a.out, "results.md"), "w").write("\n".join(lines))


if __name__ == "__main__":
    main()
