import XCTest
import CryptoKit
@testable import PathCore

// PUBLISH B2 (PLAN-P §4.4, owner item 13 "the international system works … for all countries"; design/publish/social-intl.md
// §6). The v2 world (SocialWorldModel.shipped = socialsim/v2.py) against the Python reference, bit for bit:
//   * Tests/Fixtures/soc_v2_intl.json (design/social/tools/v2/fixtures_v2.py): the model's parameters, 40 cohorts' country
//     blocks with per-member quantiles, lags, countries, cultures, names, avatars and levels, the native / Latin name draws
//     of every culture, the region map, 12 countries' boards, two LOCAL codes and the M9 shards;
//   * the v2-only property checks of design/social/tools/tests_v2.py (15-22), one to one (the shared checks 1-14 run on the
//     v2 world in SocialPropertyTests);
//   * the compiled tables = design/social/data_v2's files, and every Locale.Region.isoRegions code of THIS Foundation resolves.
// Exact equality everywhere; doubles are parsed from Python repr() strings (the same bits). Never edit a fixture to pass.

final class SocialIntlTests: XCTestCase {
    typealias F = SocFix
    static let tNow = SocialPropertyTests.tNowV2          // tests.py T_NOW for v2 (2026-12-25 01:00 UTC)

    static let intl: [String: Any] = {
        do { return try F.ownFixture("soc_v2_intl.json") } catch { fatalError("soc_v2_intl.json: \(error)") }
    }()

    // ------------------------------------------------------------------------------------------------ the model's parameters

    func testModelParametersEqualTheReference() throws {
        let fx = Self.intl
        let m = SocialWorldModel.shipped
        let intl = try XCTUnwrap(m.intl)
        XCTAssertEqual(F.str(fx["model"]), "v2")
        XCTAssertEqual(m.name, "shipped")
        XCTAssertEqual(m.epoch, F.i(fx["worldEpoch"]))
        XCTAssertEqual((m.epoch - SocialCalendar.epoch) % SocialCalendar.week, 0, "world weeks = event weeks")
        XCTAssertEqual(intl.strata, F.i(fx["strata"]))
        XCTAssertEqual(intl.shardTarget, F.obj(fx["shardTarget"]).mapValues { F.d($0) })
        XCTAssertEqual(intl.lagMinutes, F.d(fx["lagMin"]))
        XCTAssertEqual(intl.rowTilt, F.obj(fx["rowTilt"]).mapValues { F.obj($0).mapValues { F.d($0) } })
        XCTAssertEqual(intl.minShards, ["regular": 3, "returner": 3], "v2.py MIN_SHARDS (not in the fixture; pinned by its shards)")
        XCTAssertTrue(intl.countryBlocks && intl.jitter && intl.localByISO && intl.memberCulture, "M1 M2 M4 M5 on")
        XCTAssertEqual(m.nameStyle.nativeT, F.obj(fx["nativeT"]).mapValues { F.i($0) })
        XCTAssertEqual(m.nameStyle.kanaP, F.i(fx["kanaP"]))
        let dw = F.obj(fx["draw"])
        let draw = try XCTUnwrap(m.nameStyle.draw)
        XCTAssertEqual([draw.twoDigitP, draw.headP, draw.headN, draw.tailUniformP],
                       [F.i(dw["twoDigitP"]), F.i(dw["headP"]), F.i(dw["headN"]), F.i(dw["tailUniformP"])])
        XCTAssertTrue(draw.headScaled)
        XCTAssertEqual(draw.numberP, F.obj(dw["numberP"]).mapValues { F.i($0) })
        XCTAssertEqual(SocialWorldModel.intlCultures, F.arr(fx["cultures"]).map { F.str($0)! })
        XCTAssertEqual(Array(SocialWorldModel.intlCultures.prefix(16)), SocialWorldModel.cultures, "the old indices never move")
        let bk = F.arr(fx["buckets"]).map { F.arr($0) }
        XCTAssertEqual(intl.buckets, bk.map { F.str($0[0])! })
        XCTAssertEqual(intl.bucketOffsets, bk.map { F.i($0[1]) })
        let rows = F.arr(fx["countries"]).map { F.arr($0) }
        XCTAssertEqual(m.countries.count, rows.count)
        for (c, r) in zip(m.countries, rows) {
            XCTAssertEqual(c.iso, F.str(r[0])); XCTAssertEqual(c.weight.bitPattern, F.d(r[1]).bitPattern, c.iso)
            XCTAssertEqual(c.offsetMinutes, F.i(r[2])); XCTAssertEqual(c.bucket, F.str(r[4]))
            let mix = F.arr(r[3]).map { F.arr($0) }
            XCTAssertEqual(c.mix?.map(\.culture), mix.map { F.str($0[0])! }, c.iso)
            XCTAssertEqual(c.mix?.map(\.weight.bitPattern), mix.map { F.d($0[1]).bitPattern }, c.iso)
            XCTAssertEqual(c.culture, F.str(mix[0][0]))
            // every band's rows are within ±60 min of its ONE schedule offset (data.use_countries_v2's assertion)
            let bi = try XCTUnwrap(intl.buckets.firstIndex(of: c.bucket))
            XCTAssertLessThanOrEqual(abs(c.offsetMinutes - intl.bucketOffsets[bi]), 60, c.iso)
        }
        let regions = F.obj(fx["regions"])
        XCTAssertEqual(intl.regions.count, regions.count)
        for (code, v) in regions {
            let kv = F.arr(v)
            XCTAssertEqual(intl.regions[code]?.kind.rawValue, F.str(kv[0]), code)
            XCTAssertEqual(intl.regions[code]?.board, F.str(kv[1]), code)
        }
        SocTally.add(40 + rows.count * 6 + regions.count * 2)
    }

    /// The compiled tables (SocialIntlTables, generated by Tests/tools/soc_v2_tables.py) = design/social/data_v2's rows.
    func testTablesEqualTheTSVs() throws {
        func tsv(_ name: String) throws -> [[String]] {
            try String(contentsOf: F.designDataV2.appendingPathComponent(name), encoding: .utf8)
                .split(separator: "\n").map(String.init).filter { !$0.isEmpty && !$0.hasPrefix("#") }
                .map { $0.split(separator: "\t", omittingEmptySubsequences: false).map(String.init) }
        }
        let b = try tsv("buckets_v2.tsv")
        XCTAssertEqual(SocialIntlTables.buckets.map(\.name), b.map { $0[0] })
        XCTAssertEqual(SocialIntlTables.buckets.map(\.offset), b.map { Int($0[1])! })
        let c = try tsv("countries_v2.tsv")
        XCTAssertEqual(SocialIntlTables.countries.count, c.count)
        for (row, r) in zip(SocialIntlTables.countries, c) {
            XCTAssertEqual([row.iso, row.bucket], [r[0], r[4]])
            XCTAssertEqual(row.weight, Double(r[1])); XCTAssertEqual(row.offsetMinutes, Int(r[2]))
            // data.parse_mix, parsed here independently: 'nl:0.6,fr:0.4' / 'en'
            let parts = r[3].split(separator: ",").map { $0.split(separator: ":").map(String.init) }
            XCTAssertEqual(row.mix?.map(\.culture), parts.map { $0[0] }, row.iso)
            XCTAssertEqual(row.mix?.map(\.weight), parts.map { $0.count == 2 ? Double($0[1])! : 1.0 }, row.iso)
            XCTAssertEqual(row.culture, parts[0][0])
        }
        let rg = try tsv("regions_v2.tsv")
        XCTAssertEqual(SocialIntlTables.regions.count, rg.count)
        for r in rg { XCTAssertEqual(SocialIntlTables.regions[r[0]], SocialRegion(kind: SocialRegion.Kind(rawValue: r[1])!, board: r[2]), r[0]) }
        XCTAssertEqual(Set(SocialIntlTables.regions.values.map(\.kind)), [.row, .alias, .numeric])
    }

    // ------------------------------------------------------------------------------------------------ fixture sections

    static let T: Double = Double(F.i(intl["t"]))
    static let world: SocialPopulation = {
        let W = F.world("v2")
        W.extend(to: T + 9 * 86_400)
        return W
    }()

    func testBlocksMembersAndShards() throws {
        let fx = Self.intl
        let W = Self.world
        let T = Self.T
        let cs = W.cohorts
        for e in F.arr(fx["blocks"]) {
            let o = F.obj(e)
            let c = cs[F.i(o["idx"])]
            XCTAssertEqual([c.ck, c.p, c.b, c.a, c.day, c.n, c.gid0, c.off],
                           ["ck", "p", "b", "a", "day", "n", "gid0", "off"].map { F.i(o[$0]) }, "cohort \(c.idx)")
            XCTAssertTrue(F.same(c.v, F.d(o["v"])) && F.same(c.pace, F.d(o["pace"])), "cohort \(c.idx)")
            XCTAssertNil(c.iso); XCTAssertNil(c.culture)
            let want = F.arr(o["blocks"]).map { F.arr($0) }
            var got: [[String]] = []
            for bi in c.blockLo..<c.blockHi {
                let row = Int(W.blk[bi] >> 16), s0 = Int(W.blk[bi] & 0xFFFF)
                let e0 = bi + 1 < c.blockHi ? Int(W.blk[bi + 1] & 0xFFFF) : c.n
                got.append([W.bucketRows[c.b][row].iso, String(s0), String(e0)])
            }
            XCTAssertEqual(got, want.map { [F.str($0[0])!, String(F.i($0[1])), String(F.i($0[2]))] }, "blocks of cohort \(c.idx)")
            for me in F.arr(o["members"]) {
                let v = F.arr(me)
                let j = F.i(v[0])
                let (nm, st) = W.name(c, j)
                XCTAssertTrue(F.same(W.u(c, j), F.d(v[1])), "u \(c.idx)/\(j)")
                XCTAssertTrue(F.same(W.lag(c, j), F.d(v[2])), "lag \(c.idx)/\(j)")
                XCTAssertEqual([W.isoOf(c, j), W.cultureOf(c, j), nm, st], [F.str(v[3])!, F.str(v[4])!, F.str(v[5])!, F.str(v[6])!],
                               "member \(c.idx)/\(j)")
                XCTAssertEqual(W.avatar(c, j, style: st), F.i(v[7]))
                XCTAssertEqual(W.level(c, j, T), F.i(v[8]), "level \(c.idx)/\(j)")
                SocTally.add(9)
            }
            SocTally.add(10 + want.count * 3)
        }
        // M9: the join period 1 cohorts of band EUR_C (sharded weekly archetypes, one cohort per day for tourists)
        let eurc = try XCTUnwrap(W.buckets.firstIndex(of: "EUR_C"))
        let shards = cs.filter { $0.p == 1 && $0.b == eurc }.map { [$0.idx, $0.ck, $0.p, $0.b, $0.a, $0.n] }
        XCTAssertEqual(shards, F.arr(fx["shardsEURC1"]).map { F.arr($0).map { F.i($0) } })
        // the fixture's world was built to soc_v2_world.json's last board + 2 days (fixtures_v2.py reuses that World)
        let wf = try F.ownFixture("soc_v2_world.json")
        let tEnd = Double(F.i(F.obj(F.arr(wf["boards"]).last)["t"])) + 2 * 86_400
        W.extend(to: tEnd)
        let pEnd = SocialHash.floorDiv(Int(tEnd) - W.epoch, SocialCalendar.week)
        XCTAssertEqual(W.cohorts.filter { $0.p <= pEnd }.count, F.i(fx["cohortCount"]))
        XCTAssertEqual(W.gidLimit(tEnd), F.i(fx["members"]))
        SocTally.add(shards.count * 6 + 2)
    }

    func testNativeAndLatinDraws() throws {
        let fx = Self.intl
        let m = SocialWorldModel.shipped
        let draw = try XCTUnwrap(m.nameStyle.draw)
        let draws = F.arr(fx["draws"])
        XCTAssertGreaterThan(draws.count, 2000)
        var bad = 0
        var cultures = Set<String>()
        for e in draws {
            let v = F.arr(e)
            let st = F.str(v[0])!, cu = F.str(v[1])!
            cultures.insert(cu)
            if st == "given-build" {
                let got = SocialNames.build("given", F.i(v[2]), 0, cu, bank: F.bankV2, variants: m.nameStyle.variants, vr: F.i(v[3]),
                                            nativeT: m.nameStyle.nativeT, kanaP: m.nameStyle.kanaP)
                if got != F.str(v[4]) { bad += 1; if bad < 6 { XCTFail("build \(v) got \(got ?? "nil")") } }
                SocTally.add(1)
                continue
            }
            let key = F.u64(v[3])
            XCTAssertEqual(key, SocialHash.h64(SocialWorldModel.worldSeed, SocialLabels.nick, F.i(v[2])))
            let ix = SocialNames.drawIndex(st, cu, key: key, bank: F.bankV2, draw: draw)
            let wantIx = F.arr(v[4])
            XCTAssertEqual(ix?.index, F.i(wantIx[0]), "\(v)")
            XCTAssertEqual(ix?.token, wantIx[1] is NSNull ? nil : F.i(wantIx[1]), "\(v)")
            let got = SocialNames.drawn(st, cu, key: key, bank: F.bankV2, variants: m.nameStyle.variants, draw: draw,
                                        nativeT: m.nameStyle.nativeT, kanaP: m.nameStyle.kanaP)
            if got != F.str(v[5]) { bad += 1; if bad < 6 { XCTFail("drawn \(v) got \(got ?? "nil")") } }
            SocTally.add(4)
        }
        XCTAssertEqual(bad, 0, "draw mismatches")
        XCTAssertEqual(cultures.count, SocialWorldModel.intlCultures.count, "every culture of the v2 data is pinned")
    }

    func testCountryBoards() throws {
        let W = Self.world
        let boards = F.arr(Self.intl["boards"])
        XCTAssertEqual(boards.count, 24)
        for e in boards {
            let o = F.obj(e)
            let iso = F.str(o["iso"])!, t = Double(F.i(o["t"]))
            XCTAssertEqual(W.joined(t, iso: iso), F.i(o["joined"]), "\(iso) joined \(t)")
            XCTAssertEqual(W.rankOfLevel(62, t, iso: iso), F.i(o["rank62"]), "\(iso) rank62 \(t)")
            let top = W.top(t, 15, iso: iso)
            XCTAssertEqual(top.map(\.gid), F.arr(o["top"]).map { F.i(F.arr($0)[0]) }, "\(iso) top \(t)")
            XCTAssertEqual(top.map(\.P.bitPattern), F.arr(o["top"]).map { F.d(F.arr($0)[1]).bitPattern }, "\(iso) top P \(t)")
            let (ab, be) = W.neighbours(62, t, above: 6, below: 6, iso: iso)
            XCTAssertEqual(ab.map(\.gid), F.arr(o["above"]).map { F.i($0) }, "\(iso) above \(t)")
            XCTAssertEqual(be.map(\.gid), F.arr(o["below"]).map { F.i($0) }, "\(iso) below \(t)")
            let rows = F.arr(o["rows"]).map { F.arr($0) }
            for (r, w) in zip(top.prefix(5), rows) {
                XCTAssertEqual(W.gid(r.c, r.j), F.i(w[0]))
                XCTAssertEqual(W.name(r.c, r.j).name, F.str(w[1]), "\(iso) row")
                XCTAssertEqual(W.isoOf(r.c, r.j), F.str(w[2]))
                XCTAssertEqual(W.level(r.c, r.j, t), F.i(w[3]))
            }
            SocTally.add(4 + 30 + 12 + rows.count * 4)
        }
    }

    func testLocalPartitionsForUnknownCodes() throws {
        let T = Self.T
        for e in F.arr(Self.intl["local"]) {
            let o = F.obj(e)
            let code = F.str(o["code"])!
            let home = SocialWorldModel.shipped.homeBoard(forRegion: code)
            XCTAssertEqual(home.iso, code); XCTAssertTrue(home.local, "\(code) is no region: a LOCAL partition")
            let WL = SocialPopulation(model: .shipped, local: SocialLocalPartition(iso: code, offsetMinutes: 0, culture: "en"), names: F.bankV2)
            WL.extend(to: T)
            XCTAssertEqual(WL.cohorts.count, F.i(o["cohortCount"]))
            let lc = WL.cohorts.filter { $0.local && $0.n > 0 }.prefix(10)
            let want = F.arr(o["cohorts"]).map { F.arr($0) }
            XCTAssertEqual(lc.count, want.count)
            for (c, v) in zip(lc, want) {
                XCTAssertEqual([c.idx, c.ck, c.gid0, c.n, c.salt], (0..<5).map { F.i(v[$0]) }, "\(code) cohort \(c.idx)")
                let k = min(3, c.n)
                XCTAssertEqual((0..<k).map { WL.name(c, $0).name }, (0..<k).map { F.str(v[5 + $0])! }, "\(code) names")
                XCTAssertEqual(WL.level(c, c.n - 1, T), F.i(v[5 + k]))
                XCTAssertEqual(WL.isoOf(c, 0), code)
                SocTally.add(6 + k)
            }
            XCTAssertEqual(WL.joined(T, iso: code), F.i(o["joined"]))
            XCTAssertEqual(WL.rankOfLevel(62, T, iso: code), F.i(o["rank62"]))
            let top = WL.top(T, 10, iso: code)
            XCTAssertEqual(top.map(\.gid), F.arr(o["top"]).map { F.i(F.arr($0)[0]) })
            XCTAssertEqual(top.map(\.P.bitPattern), F.arr(o["top"]).map { F.d(F.arr($0)[1]).bitPattern })
            SocTally.add(24)
        }
    }

    // ------------------------------------------------------------------------------------------------ tests_v2.py 15-22

    /// iso -> every member (brute force over the whole world; the definition the unit queries must equal).
    func membersByIso(_ W: SocialPopulation, _ isos: Set<String>, _ tMax: Double) -> [String: [(SocialCohort, Int)]] {
        var out: [String: [(SocialCohort, Int)]] = [:]
        for c in W.cohorts where c.n > 0 && c.join0 - c.span <= tMax {
            for j in 0..<c.n {
                let iso = W.isoOf(c, j)
                if isos.contains(iso) { out[iso, default: []].append((c, j)) }
            }
        }
        return out
    }

    // 15. country queries over (cohort, block) units = brute force: 10 countries × 3 times
    func testCountryQueriesEqualBruteForce() {
        let W = F.world("v2")
        let tNow = Self.tNow
        W.extend(to: tNow + 8 * 86_400)
        let times = [tNow - 50 * 86_400, tNow - 9 * 86_400 - 3 * 3600, tNow]
        let isos = ["US", "TR", "SK", "SI", "JP", "KR", "BE", "CH", "BR", "IS"]
        let mem = membersByIso(W, Set(isos), tNow)
        var bad: [String] = []
        for iso in isos {
            for t in times {
                var all: [(P: Double, gid: Int)] = []
                for (c, j) in mem[iso] ?? [] { if let P = W.progress(c, j, t) { all.append((P, W.gid(c, j))) } }
                all.sort { $0.P != $1.P ? $0.P > $1.P : $0.gid < $1.gid }
                for x in [1, 2, 11, 40, 62, 300] where all.filter({ 1 + SocialHash.floorInt($0.P) >= x }).count != W.countAtLeast(x, t, iso: iso) {
                    bad.append("count \(iso) \(t) \(x)")
                }
                if W.top(t, 40, iso: iso).map(\.gid) != all.prefix(40).map(\.gid) { bad.append("top \(iso) \(t)") }
                for x in [5, 30, 62] {
                    let (ab, be) = W.neighbours(x, t, above: 6, below: 6, iso: iso)
                    let wantA = all.filter { 1 + SocialHash.floorInt($0.P) >= x + 1 }.sorted { $0.P != $1.P ? $0.P < $1.P : $0.gid < $1.gid }.prefix(6)
                    let wantB = all.filter { 1 + SocialHash.floorInt($0.P) <= x }.sorted { $0.P != $1.P ? $0.P > $1.P : $0.gid > $1.gid }.prefix(6)
                    if ab.map(\.gid) != wantA.map(\.gid) || be.map(\.gid) != wantB.map(\.gid) { bad.append("nb \(iso) \(t) \(x)") }
                }
                SocTally.add(6 + 40 + 36)
            }
            XCTAssertGreaterThan(mem[iso]?.count ?? 0, 0, "\(iso) has players")
        }
        XCTAssertEqual(bad, [], "v2 country count / top / neighbours = brute force")
    }

    // 16. blocks partition every shared cohort into contiguous ranges of its band's rows; country sizes follow the weights
    func testBlocksPartitionEveryCohortAndSharesFollowTheWeights() throws {
        let W = F.world("v2")
        W.extend(to: Self.tNow + 8 * 86_400)
        let intl = try XCTUnwrap(W.intl)
        var ok = true
        var size: [String: Int] = [:], expect: [String: Double] = [:]
        for c in W.cohorts where !c.local {
            let rows = W.bucketRows[c.b]
            var pos = 0
            for bi in c.blockLo..<c.blockHi {
                let ri = Int(W.blk[bi] >> 16), s0 = Int(W.blk[bi] & 0xFFFF)
                let e0 = bi + 1 < c.blockHi ? Int(W.blk[bi + 1] & 0xFFFF) : c.n
                ok = ok && s0 == pos && e0 > s0 && ri < rows.count
                pos = e0
                size[rows[ri].iso, default: 0] += e0 - s0
            }
            ok = ok && pos == c.n
            let akey = c.arch.key
            let wts = rows.map { r in intl.rowTilt[r.iso].map { r.weight * ($0[akey] ?? 1.0) } ?? r.weight }
            let tw = wts.reduce(0, +)
            for (r, w) in zip(rows, wts) { expect[r.iso, default: 0] += Double(c.n) * w / tw }
        }
        XCTAssertTrue(ok, "blocks tile [0, n) in order")
        let tot = Double(size.values.reduce(0, +))
        var dev: [String] = []
        for iso in ["US", "GB", "DE", "BR", "TR", "JP", "SK", "SI"] {
            let want = expect[iso]! / tot, got = Double(size[iso] ?? 0) / tot
            if abs(got - want) > 0.08 * want + 3.0 / tot.squareRoot() { dev.append("\(iso) \(got / want)") }
        }
        XCTAssertEqual(dev, [], "country shares follow the table weights (\(Int(tot)) players)")
    }

    // 17. jitter: u strictly increasing in j inside [0, 1]
    func testJitteredQuantilesStrictlyIncreasing() {
        let W = F.world("v2")
        W.extend(to: Self.tNow + 8 * 86_400)
        let cs = W.cohorts.filter { $0.n > 2 }
        var sample: [SocialCohort] = []
        var i = 0
        while i < cs.count && sample.count < 200 { sample.append(cs[i]); i += 37 }
        var ok = true
        for c in sample {
            let us = (0..<c.n).map { W.u(c, $0) }
            ok = ok && zip(us, us.dropFirst()).allSatisfy { 0.0 <= $0 && $0 < $1 && $1 <= 1.0 }
        }
        XCTAssertGreaterThan(sample.count, 100)          // tests_v2.py: [c for c in cohorts if n > 2][::37][:200]
        XCTAssertTrue(ok)
    }

    // 18. two unknown region codes: different LOCAL skeletons (sizes, levels, names); neither touches the shared world
    func testLocalSkeletonsDifferPerISOAndLeaveTheSharedWorldAlone() {
        let tNow = Self.tNow
        let W = F.world("v2")
        W.extend(to: tNow + 8 * 86_400)
        let engine = SocialEngine(installSeed: 1, config: .default, names: F.bankV2)
        let wz = engine.population(for: "ZZ"), wx = engine.population(for: "XA")
        XCTAssertFalse(wz === engine.shared || wx === engine.shared || wz === wx)
        XCTAssertTrue(engine.population(for: "TR") === engine.shared && engine.population(for: "IC") === engine.shared,
                      "rows and aliases play on the shared world")
        wz.extend(to: tNow); wx.extend(to: tNow)
        let la = wz.cohorts.filter(\.local), lb = wx.cohorts.filter(\.local)
        XCTAssertNotEqual(la.prefix(40).map(\.n), lb.prefix(40).map(\.n), "sizes differ")
        let na = la.prefix(60).flatMap { c in (0..<min(2, c.n)).map { wz.name(c, $0).name } }
        let nb = lb.prefix(60).flatMap { c in (0..<min(2, c.n)).map { wx.name(c, $0).name } }
        let same = zip(na, nb).filter { $0 == $1 }.count
        XCTAssertLessThan(same, na.count / 4, "names differ (\(same) of \(na.count) equal)")
        let lvA = wz.top(tNow, 10, iso: "ZZ").map { wz.level($0.c, $0.j, tNow) }
        let lvB = wx.top(tNow, 10, iso: "XA").map { wx.level($0.c, $0.j, tNow) }
        XCTAssertNotEqual(lvA, lvB, "levels differ")
        var byCk: [Int: SocialCohort] = [:]
        for c in wz.cohorts where !c.local { byCk[c.ck] = c }
        var i = 0
        var sharedSame = true
        while i < W.cohorts.count {
            let c = W.cohorts[i]
            i += 7
            guard c.p < wz.periodCount else { continue }
            guard let d = byCk[c.ck], d.n == c.n, d.gid0 == c.gid0,
                  wz.blk[d.blockLo..<d.blockHi].elementsEqual(W.blk[c.blockLo..<c.blockHi]) else { sharedSame = false; break }
            if c.n > 0 && wz.name(d, c.n - 1) != W.name(c, c.n - 1) { sharedSame = false; break }
        }
        XCTAssertTrue(sharedSame, "the shared world is byte-identical with a LOCAL partition")
    }

    // 19. every Locale.Region.isoRegions code resolves to a board; aliases point at rows; offsets within ±60 min
    func testEveryIsoRegionResolvesToARow() throws {
        let m = SocialWorldModel.shipped
        let intl = try XCTUnwrap(m.intl)
        let rowIsos = Set(m.countries.map(\.iso))
        // the build Mac's list the data was made from (design/social/data_v2/ios_regions.tsv) …
        let listed = try String(contentsOf: F.designDataV2.appendingPathComponent("ios_regions.tsv"), encoding: .utf8)
            .split(separator: "\n").filter { !$0.hasPrefix("#") && !$0.isEmpty }.map { String($0.split(separator: "\t")[0]) }
        // … and THIS Foundation's (a newer SDK may add a region: it must resolve too)
        let live = Locale.Region.isoRegions.map(\.identifier)
        XCTAssertGreaterThanOrEqual(listed.count, 280)
        var unresolved: [String] = []
        for code in Set(listed + live) {
            guard let r = intl.regions[code], rowIsos.contains(r.board) else { unresolved.append(code); continue }
            let home = m.homeBoard(forRegion: code)
            if home.local || home.iso != r.board { unresolved.append(code) }
        }
        XCTAssertEqual(unresolved.sorted(), [], "region codes without a board")
        let offs = m.countries.filter { r in abs(r.offsetMinutes - intl.bucketOffsets[intl.buckets.firstIndex(of: r.bucket)!]) > 60 }
        XCTAssertEqual(offs.map(\.iso), [])
        // aliases play on their parent's board; unknown 2-letter codes get a LOCAL partition; anything else the fallback
        XCTAssertEqual(m.homeBoard(forRegion: "ic").iso, intl.regions["IC"]?.board)
        XCTAssertEqual(m.homeBoard(forRegion: "ZZ").local, true)
        XCTAssertEqual(m.homeBoard(forRegion: nil).iso, "US")
        XCTAssertEqual(m.homeBoard(forRegion: "1234").iso, "US")
        XCTAssertEqual(m.boardCountry("IC"), intl.regions["IC"]?.board)
        XCTAssertEqual(m.boardCountry("TR"), "TR")
    }

    // 20. native-script names: right script, valid as a username, never blocked; every row culture has >= 300 names
    func testNativeScriptNamesAreValidUsernamesAndRowCulturesAreLarge() throws {
        let m = SocialWorldModel.shipped
        let d = try XCTUnwrap(F.bankV2.store)
        let json = try F.json(F.designDataV2.appendingPathComponent("social_names_v2.json"))
        let native = F.arr(json["nativeScript"]).map { F.str($0)! }
        XCTAssertEqual(native.count, 14)
        var bad = 0, checked = 0
        for cu in native {
            let toks = d.cultures[cu] ?? []
            for i in stride(from: 0, to: toks.count, by: max(1, toks.count / 60)) {
                for vr in 0..<4 {
                    let s = try XCTUnwrap(SocialNames.build("given", i, 0, cu, bank: F.bankV2, variants: m.nameStyle.variants, vr: vr,
                                                            nativeT: m.nameStyle.nativeT, kanaP: m.nameStyle.kanaP))
                    checked += 1
                    // a failing name is never printed (counts only; T6 rule)
                    if SocialNames.validateUsername(s, bank: F.bankV2) != s || SocialNames.isBlocked(s, bank: F.bankV2) { bad += 1 }
                }
            }
        }
        XCTAssertGreaterThan(checked, 3000)
        XCTAssertEqual(bad, 0, "native-script names that are not valid usernames or are blocked (of \(checked))")
        let used = Set(m.countries.flatMap { $0.mix?.map(\.culture) ?? [$0.culture] })
        let small = ["hy": 200, "ka": 200]          // every name Wikidata records for Armenia's / Georgia's adults (SOURCES.md)
        let short = used.filter { (d.cultures[$0]?.count ?? 0) < (small[$0] ?? 300) }
        XCTAssertEqual(short.sorted(), [])
    }

    // 21. per-member culture follows the row's mix (BE nl .6 / fr .4, CH de .65, CA en .78, US es .0858)
    func testMemberCultureFollowsTheRowMix() {
        let W = F.world("v2")
        W.extend(to: Self.tNow + 8 * 86_400)
        var dev: [String] = []
        for (iso, cu, want) in [("BE", "nl", 0.6), ("CH", "de", 0.65), ("CA", "en", 0.78), ("US", "es", 0.0858)] {
            var n = 0, k = 0
            for c in W.cohorts where !c.local && c.join0 - c.span <= Self.tNow {
                for bi in c.blockLo..<c.blockHi where W.bucketRows[c.b][Int(W.blk[bi] >> 16)].iso == iso {
                    let s0 = Int(W.blk[bi] & 0xFFFF), e0 = bi + 1 < c.blockHi ? Int(W.blk[bi + 1] & 0xFFFF) : c.n
                    for j in s0..<e0 {
                        n += 1
                        if W.cultureOf(c, j) == cu { k += 1 }
                    }
                }
                if n > 6000 { break }
            }
            let got = Double(k) / Double(max(1, n))
            if n == 0 || abs(got - want) > 3.5 * (want * (1 - want) / Double(n)).squareRoot() + 0.01 { dev.append("\(iso) \(cu) \(n) \(got)") }
        }
        XCTAssertEqual(dev, [])
    }

    // 22. the world epoch: nobody joins before it; period 0 starts at it; world weeks share the event weeks' boundaries
    func testWorldEpoch() {
        let W = F.world("v2")
        W.extend(to: Self.tNow + 8 * 86_400)
        let E = 1_788_764_400
        XCTAssertEqual(W.epoch, E)
        let firstJoin = W.cohorts.filter { $0.n > 0 && $0.p == 0 }.map { W.member($0, $0.n - 1).J }.min()!
        XCTAssertGreaterThanOrEqual(firstJoin, Double(E))
        XCTAssertEqual((E - SocialCalendar.epoch) % SocialCalendar.week, 0)
        XCTAssertEqual(W.gidLimit(Double(E - 1)), 0)
        XCTAssertEqual(W.joined(Double(E - 1)), 0)
        XCTAssertGreaterThan(W.joined(Double(E + 86_400)), 0)
        XCTAssertEqual(SocialCalendar.eventWeekStart(SocialCalendar.eventWeek(E)), E, "the world starts on an event week's start")
    }

    // ------------------------------------------------------------------------------------------------ the freeze (G9)

    /// design/social/FROZEN (Tests/tools/soc_freeze.py): the shipped world's defining files — the T6 data, the reference
    /// model, the generated Swift tables, the shipped name bank and the golden fixtures — hash to the frozen values. After
    /// v1.0 a change to any of them would rewrite every board players have already seen (social-intl P0-3).
    func testTheShippedWorldIsFrozen() throws {
        let text = try String(contentsOf: F.appRoot.appendingPathComponent("design/social/FROZEN"), encoding: .utf8)
        let rows = text.split(separator: "\n").filter { !$0.hasPrefix("#") && !$0.isEmpty }.map { $0.split(separator: "\t").map(String.init) }
        XCTAssertGreaterThanOrEqual(rows.count, 16)
        let paths = Set(rows.map { $0[1] })
        for must in ["design/social/data_v2/countries_v2.tsv", "design/social/data_v2/social_names_v2.json",
                     "Packages/PathCore/Sources/PathCore/Social/SocialIntlTables.swift", "App/Resources/Social/social_names.json",
                     "Packages/PathCore/Tests/Fixtures/soc_v2_world.json", "Packages/PathCore/Tests/Fixtures/soc_v2_intl.json",
                     "design/social/tools/socialsim/v2.py", "design/social/tools/socialsim/population.py"] {
            XCTAssertTrue(paths.contains(must), "\(must) is frozen")
        }
        for r in rows {
            let data = try Data(contentsOf: F.appRoot.appendingPathComponent(r[1]))
            let h = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            XCTAssertEqual(h, r[0], "\(r[1]) changed since the freeze")
        }
    }

    // ------------------------------------------------------------------------------------------------ the App's inputs

    /// validateUsername: 2 characters suffice for Han, Hangul and kana (social-intl P2-4), 3 elsewhere; 16 at most.
    func testUsernameRuleForCJK() {
        let bank = F.bankV2
        XCTAssertEqual(SocialNames.validateUsername("민수", bank: bank), "민수")
        XCTAssertEqual(SocialNames.validateUsername("小明", bank: bank), "小明")
        XCTAssertEqual(SocialNames.validateUsername("たろ", bank: bank), "たろ")
        XCTAssertEqual(SocialNames.validateUsername("タロ", bank: bank), "タロ")
        XCTAssertNil(SocialNames.validateUsername("민", bank: bank), "one character is too short everywhere")
        XCTAssertNil(SocialNames.validateUsername("ab", bank: bank), "Latin keeps its 3-character minimum")
        XCTAssertNil(SocialNames.validateUsername("Ωμ", bank: bank), "Greek is not Han/Hangul/kana")
        XCTAssertEqual(SocialNames.validateUsername("Ωμέγα", bank: bank), "Ωμέγα")
        XCTAssertNil(SocialNames.validateUsername(String(repeating: "민", count: 17), bank: bank))
        XCTAssertNil(SocialNames.validateUsername("민 수", bank: bank), "no spaces")
    }
}
